In [1]:
import tensorflow as tf
import time
import numpy as np
import os
import pickle5 as pickle
import argparse
import utilityarm as utility
import pandas as pd
from sklearn.metrics import *

In [2]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior() 

class BPR:

    def __init__(self, sess, dict_args, train_df, vali_df
                 , key_type, user_type_list, item_type_count):
       
        self.dataname = dict_args['dataname']

        self.key_type = key_type
        self.user_type_list = user_type_list
        self.item_type_count = item_type_count

        self.sess = sess
        #self.args = args

        self.num_cols = len(train_df['item_id'].unique())
        self.num_rows = len(train_df['user_id'].unique())

        self.hidden_neuron = dict_args['hidden_neuron']
        self.neg = dict_args['neg']
        self.batch_size = dict_args['batch_size']

        self.train_df = train_df
        self.vali_df = vali_df
        self.num_train = len(self.train_df)
        self.num_vali = len(self.vali_df)

        self.train_epoch = dict_args['train_epoch']

        self.lr = dict_args['lr'] # learning rate
        self.optimizer_method = dict_args['optimizer_method']
        self.display_step = dict_args['display_step']

        #self.num_genre = dict_args['num_type']

        self.reg = dict_args['reg'] # regularization term trade-off

        print('**********BPR**********')
        #print(self.args)
        self._prepare_model()

    def run(self):
        init = tf.global_variables_initializer()
        self.sess.run(init)
        for epoch_itr in range(1, self.train_epoch + 1):
            self.train_model(epoch_itr)
            if epoch_itr % self.display_step == 0:
                self.test_model(epoch_itr)
        return self.make_records()

    def _prepare_model(self):
        with tf.name_scope("input_data"):
            self.user_input = tf.placeholder(tf.int32, shape=[None, 1], name="user_input")
            self.item_input_pos = tf.placeholder(tf.int32, shape=[None, 1], name="item_input_pos")
            self.item_input_neg = tf.placeholder(tf.int32, shape=[None, 1], name="item_input_neg")

        with tf.variable_scope("BPR", reuse=tf.AUTO_REUSE):
            self.P = tf.get_variable(name="P", initializer=tf.truncated_normal(shape=[self.num_rows, self.hidden_neuron],
                                                                          mean=0, stddev=0.03), dtype=tf.float32)
            self.Q = tf.get_variable(name="Q", initializer=tf.truncated_normal(shape=[self.num_cols+20, self.hidden_neuron],
                                                                          mean=0, stddev=0.03), dtype=tf.float32)

        self.saver = tf.train.Saver([self.P, self.Q])

        p = tf.reduce_sum(tf.nn.embedding_lookup(self.P, self.user_input), 1)
        q_neg = tf.reduce_sum(tf.nn.embedding_lookup(self.Q, self.item_input_neg), 1)
        q_pos = tf.reduce_sum(tf.nn.embedding_lookup(self.Q, self.item_input_pos), 1)

        predict_pos = (tf.reduce_sum(p * q_pos, 1))
        predict_neg = (tf.reduce_sum(p * q_neg, 1))

        cost1 = tf.reduce_sum(tf.nn.softplus(-(predict_pos - predict_neg)))
        cost2 = self.reg * 0.5 * (self.l2_norm(self.P) + self.l2_norm(self.Q))  # regularization term

        self.cost = cost1 + cost2  # the loss function

        if self.optimizer_method == "Adam":
            optimizer = tf.train.AdamOptimizer(self.lr)
        elif self.optimizer_method == "Adadelta":
            optimizer = tf.train.AdadeltaOptimizer(self.lr)
        elif self.optimizer_method == "Adagrad":
            optimizer = tf.train.AdadeltaOptimizer(self.lr)
        elif self.optimizer_method == "RMSProp":
            optimizer = tf.train.RMSPropOptimizer(self.lr)
        elif self.optimizer_method == "GradientDescent":
            optimizer = tf.train.GradientDescentOptimizer(self.lr)
        elif self.optimizer_method == "Momentum":
            optimizer = tf.train.MomentumOptimizer(self.lr, 0.9)
        else:
            raise ValueError("Optimizer Key ERROR")

        with tf.variable_scope("Optimizer", reuse=tf.AUTO_REUSE):
            self.optimizer = optimizer.minimize(self.cost)

    def train_model(self, itr):
        NS_start_time = time.time() * 1000.0
        epoch_cost = 0
        num_sample, user_list, item_pos_list, item_neg_list = utility.negative_sample(self.train_df, self.num_rows,
                                                                                      self.num_cols, self.neg)
        NS_end_time = time.time() * 1000.0

        start_time = time.time() * 1000.0
        num_batch = int(len(user_list) / float(self.batch_size)) + 1
        random_idx = np.random.permutation(len(user_list))
        for i in range(num_batch):

            # get the indices of the current batch
            if i == num_batch - 1:
                batch_idx = random_idx[i * self.batch_size:]
            elif i < num_batch - 1:
                batch_idx = random_idx[(i * self.batch_size):((i + 1) * self.batch_size)]
            _, tmp_cost = self.sess.run(  # do the optimization by the minibatch
                [self.optimizer, self.cost],
                feed_dict={self.user_input: user_list[batch_idx, :],
                           self.item_input_pos: item_pos_list[batch_idx, :],
                           self.item_input_neg: item_neg_list[batch_idx, :]})
            epoch_cost += tmp_cost

        if itr % self.display_step == 0:
            print ("Training //", "Epoch %d //" % itr, " Total cost = {:.5f}".format(epoch_cost),
                   "Training time : %d ms" % (time.time() * 1000.0 - start_time),
                   "negative Sampling time : %d ms" % (NS_end_time - NS_start_time),
                   "negative samples : %d" % (num_sample))

        ckpt_save_path = "./"+self.dataname+"/BPR_check_points"
        if not os.path.exists(ckpt_save_path):
            os.makedirs(ckpt_save_path)
        self.saver.save(sess, ckpt_save_path + "/check_point.ckpt", global_step=itr)

    def test_model(self, itr):  # calculate the cost and rmse of testing set in each epoch
        if itr % self.display_step == 0:
            start_time = time.time() * 1000.0
            P, Q = self.sess.run([self.P, self.Q])
            Rec = np.matmul(P, Q.T)

            [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
#             utility.ranking_analysis(Rec, self.vali_df, self.train_df, self.key_type, self.user_type_list,
#                                      self.item_type_count)
            utility.test_model_per_user_type(Rec, self.vali_df, self.train_df, self.user_type_list, self.key_type)
            auc_global = utility.auc_per_user(Rec, self.vali_df, self.train_df)

            print("AUC global is: ", auc_global)
            
#             for k in self.key_type:
#                 print("AUC per %d is:\t[%.7f] "%(k, auc[k]))
#             print("AUC global is: ", auc_global)
            print (
                "Testing //", "Epoch %d //" % itr,
                "Testing time : %d ms" % (time.time() * 1000.0 - start_time))
            print("=" * 200)
        

            filename = './unfairBPR_results/epoch'+ str(itr) +'_Rec_' + self.dataname + '_BPR.npy'
            os.makedirs(os.path.dirname(filename), exist_ok=True)           
            with open(filename, "wb") as f:
                np.save(f, Rec)



    def make_records(self):  # record all the results' details into files
        P, Q = self.sess.run([self.P, self.Q])
        Rec = np.matmul(P, Q.T)

        [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
        return precision, recall, f_score, NDCG, Rec

    @staticmethod
    def l2_norm(tensor):
        return tf.reduce_sum(tf.square(tensor))

WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [3]:

#optimizer_method = ['Adam', 'Adadelta', 'Adagrad', 'RMSProp', 'GradientDescent','Momentum'], default='Adam')


train_epoch = 20
display_step = 1
lr = 0.01
reg = 0.1
optimizer_method = 'Adam'
hidden_neuron = 20
n = 1
neg = 5
batch_size = 256
dataname = 'amazon'

In [4]:
dict_args =  {"train_epoch": train_epoch,
            "display_step":display_step,
            "lr":lr,
            "reg":reg,
            "optimizer_method":optimizer_method,
            "hidden_neuron":hidden_neuron,
            "n":n,
            "neg":neg,
            "batch_size":batch_size,
            "dataname":dataname}
dict_args

{'train_epoch': 20,
 'display_step': 1,
 'lr': 0.01,
 'reg': 0.1,
 'optimizer_method': 'Adam',
 'hidden_neuron': 20,
 'n': 1,
 'neg': 5,
 'batch_size': 256,
 'dataname': 'amazon'}

In [5]:
with open('./training_df_amazon.pkl', 'rb') as f:
    train_df = pickle.load(f,encoding='latin1')

# with open('./' + dataname + '/valiing_df.pkl', 'rb') as f:
#     vali_df = pickle.load(f,encoding='latin1')  # for validation
    
with open('./testing_df_amazon.pkl', 'rb') as f:
    test_df = pickle.load(f,encoding='latin1')  # for validation
# vali_df = pickle.load(open('./' + dataname + '/testing_df.pkl'))  # for testing

with open('./key_type_amazon.pkl', 'rb') as f:
    key_type = pickle.load(f,encoding='latin1')
    
with open('./user_idd_type_list_amazon.pkl', 'rb') as f:
    user_idd_type_list = pickle.load(f,encoding='latin1')
    
with open('./type_user_vector_amazon.pkl', 'rb') as f:
    type_user_vector = pickle.load(f,encoding='latin1')

with open('./type_count_amazon.pkl', 'rb') as f:
    type_count = pickle.load(f,encoding='latin1')
    
with open('./item_type_count_amazon.pkl', 'rb') as f:
    item_type_count = pickle.load(f,encoding='latin1')

In [6]:
print(type_count)

[('Male', 5199), ('Female', 2446)]

In [7]:
train_df['item_id'].unique()

array([   0,    1,    2, ..., 2287,   29, 1177], dtype=int64)

In [8]:
train_df.head(20)

    user_id  item_id  rating
0         0        0     1.0
1         1        1     5.0
2         3        1     5.0
3         3        2     4.0
4         1        4     5.0
5         5        1     5.0
6         6        3     5.0
7         8        4     5.0
8         9        4     1.0
9        10        6     5.0
10       11        3     5.0
11       13        1     5.0
12       13        0     4.0
13       13        2     5.0
14       15        7     1.0
15       16        8     5.0
16       18        9     5.0
17       19        9     5.0
18       20       10     5.0
19       21        8     5.0

In [9]:
train_df.shape

(18968, 3)

In [10]:
test_df.head(20)

    user_id  item_id  rating
0         2        1     5.0
1         4        3     5.0
2         7        5     5.0
3        12        7     2.0
4        14        4     1.0
5        17        8     4.0
6        25        8     3.0
7        29        8     5.0
8        30        8     4.0
9        31       13     5.0
10       33       14     4.0
11       41        4     5.0
12       44       18     5.0
13       48       20     5.0
14       52       13     4.0
15       53       21     5.0
16       54       22     4.0
17       62       23     5.0
18       69       19     5.0
19       72       29     5.0

In [11]:
test_df.shape

(7819, 3)

In [12]:
print(len(user_idd_type_list))

7645

In [13]:
user_idd_type_list

[['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Male'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Female'],
 ['Male'],
 ['Male'],
 ...]

In [14]:
print(type_user_vector['Female'].shape)

(1, 7645)

In [15]:
type_user_vector

{'Female': array([[1., 0., 1., ..., 0., 1., 0.]]),
 'Male': array([[0., 1., 0., ..., 1., 0., 1.]])}

In [16]:
len(item_type_count)

2289

In [17]:
item_type_count

[{'Female': 2445, 'Male': 5198},
 {'Female': 2444, 'Male': 5193},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2439, 'Male': 5191},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2445, 'Male': 5186},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2444, 'Male': 5192},
 {'Female': 2434, 'Male': 5157},
 {'Female': 2442, 'Male': 5192},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2445, 'Male': 5191},
 {'Female': 2443, 'Male': 5199},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2443, 'Male': 5190},
 {'Female': 2445, 'Male': 5191},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2426, 'Male': 5143},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2433, 'Male': 5156},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2440, 'Male': 5180},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2441, 'Male': 5154},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2443, 'Male': 5193},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2445, 'Male': 5190},
 {'Female': 2442, 'Male': 5185},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2440, 'Male': 5197},
 {'Female': 2426, 'Male': 5106},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2443, 'Male': 5193},
 {'Female': 2443, 'Male': 5190},
 {'Female': 2445, 'Male': 5178},
 {'Female': 2439, 'Male': 5198},
 {'Female': 2443, 'Male': 5196},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2431, 'Male': 5083},
 {'Female': 2441, 'Male': 5184},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2442, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2443, 'Male': 5196},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2441, 'Male': 5186},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2441, 'Male': 5184},
 {'Female': 2435, 'Male': 5165},
 {'Female': 2434, 'Male': 5182},
 {'Female': 2443, 'Male': 5196},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2443, 'Male': 5195},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2442, 'Male': 5180},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2426, 'Male': 5144},
 {'Female': 2446, 'Male': 5192},
 {'Female': 2446, 'Male': 5192},
 {'Female': 2439, 'Male': 5163},
 {'Female': 2443, 'Male': 5192},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2440, 'Male': 5184},
 {'Female': 2444, 'Male': 5194},
 {'Female': 2440, 'Male': 5193},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2443, 'Male': 5180},
 {'Female': 2446, 'Male': 5190},
 {'Female': 2444, 'Male': 5193},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2443, 'Male': 5194},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2444, 'Male': 5198},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2444, 'Male': 5194},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2440, 'Male': 5183},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2444, 'Male': 5192},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2442, 'Male': 5196},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2439, 'Male': 5185},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2441, 'Male': 5186},
 {'Female': 2442, 'Male': 5194},
 {'Female': 2445, 'Male': 5187},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2442, 'Male': 5199},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2444, 'Male': 5189},
 {'Female': 2440, 'Male': 5194},
 {'Female': 2445, 'Male': 5192},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2441, 'Male': 5194},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2445, 'Male': 5193},
 {'Female': 2443, 'Male': 5185},
 {'Female': 2424, 'Male': 5096},
 {'Female': 2442, 'Male': 5188},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2438, 'Male': 5169},
 {'Female': 2423, 'Male': 5174},
 {'Female': 2439, 'Male': 5192},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2445, 'Male': 5193},
 {'Female': 2443, 'Male': 5195},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5187},
 {'Female': 2435, 'Male': 5186},
 {'Female': 2440, 'Male': 5182},
 {'Female': 2444, 'Male': 5194},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2439, 'Male': 5182},
 {'Female': 2441, 'Male': 5190},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2441, 'Male': 5185},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2446, 'Male': 5185},
 {'Female': 2443, 'Male': 5190},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2440, 'Male': 5199},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2444, 'Male': 5190},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2445, 'Male': 5193},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2440, 'Male': 5181},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2444, 'Male': 5198},
 {'Female': 2441, 'Male': 5197},
 {'Female': 2445, 'Male': 5199},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2444, 'Male': 5198},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2429, 'Male': 5137},
 {'Female': 2443, 'Male': 5186},
 {'Female': 2446, 'Male': 5191},
 {'Female': 2440, 'Male': 5190},
 {'Female': 2440, 'Male': 5189},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2440, 'Male': 5186},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2444, 'Male': 5194},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2440, 'Male': 5191},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2446, 'Male': 5191},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2436, 'Male': 5165},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2435, 'Male': 5179},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5199},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2444, 'Male': 5189},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5193},
 {'Female': 2432, 'Male': 5183},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2441, 'Male': 5197},
 {'Female': 2440, 'Male': 5196},
 {'Female': 2438, 'Male': 5196},
 {'Female': 2443, 'Male': 5194},
 {'Female': 2446, 'Male': 5191},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2443, 'Male': 5196},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2442, 'Male': 5198},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2429, 'Male': 5147},
 {'Female': 2443, 'Male': 5180},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2443, 'Male': 5192},
 {'Female': 2444, 'Male': 5198},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2438, 'Male': 5189},
 {'Female': 2444, 'Male': 5193},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2435, 'Male': 5180},
 {'Female': 2441, 'Male': 5173},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2442, 'Male': 5196},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2444, 'Male': 5193},
 {'Female': 2443, 'Male': 5187},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2446, 'Male': 5199},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2444, 'Male': 5193},
 {'Female': 2442, 'Male': 5190},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2442, 'Male': 5194},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5192},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2444, 'Male': 5185},
 {'Female': 2442, 'Male': 5192},
 {'Female': 2439, 'Male': 5180},
 {'Female': 2441, 'Male': 5193},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2444, 'Male': 5194},
 {'Female': 2430, 'Male': 5181},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2442, 'Male': 5187},
 {'Female': 2442, 'Male': 5193},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2443, 'Male': 5191},
 {'Female': 2437, 'Male': 5180},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2442, 'Male': 5181},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2437, 'Male': 5160},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2442, 'Male': 5180},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2444, 'Male': 5188},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2438, 'Male': 5194},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2443, 'Male': 5194},
 {'Female': 2441, 'Male': 5193},
 {'Female': 2440, 'Male': 5194},
 {'Female': 2440, 'Male': 5191},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2445, 'Male': 5189},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2437, 'Male': 5183},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2444, 'Male': 5192},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2438, 'Male': 5194},
 {'Female': 2442, 'Male': 5169},
 {'Female': 2442, 'Male': 5198},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2442, 'Male': 5193},
 {'Female': 2444, 'Male': 5191},
 {'Female': 2443, 'Male': 5199},
 {'Female': 2444, 'Male': 5187},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2439, 'Male': 5148},
 {'Female': 2445, 'Male': 5193},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2444, 'Male': 5192},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5189},
 {'Female': 2442, 'Male': 5193},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2439, 'Male': 5196},
 {'Female': 2428, 'Male': 5162},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5199},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2444, 'Male': 5191},
 {'Female': 2440, 'Male': 5199},
 {'Female': 2408, 'Male': 5122},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2424, 'Male': 5145},
 {'Female': 2443, 'Male': 5193},
 {'Female': 2443, 'Male': 5194},
 {'Female': 2445, 'Male': 5192},
 {'Female': 2444, 'Male': 5180},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2426, 'Male': 5125},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2436, 'Male': 5188},
 {'Female': 2440, 'Male': 5174},
 {'Female': 2439, 'Male': 5166},
 {'Female': 2441, 'Male': 5195},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2441, 'Male': 5196},
 {'Female': 2441, 'Male': 5195},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2446, 'Male': 5192},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2442, 'Male': 5195},
 {'Female': 2437, 'Male': 5191},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2443, 'Male': 5186},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2435, 'Male': 5181},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2444, 'Male': 5198},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2443, 'Male': 5186},
 {'Female': 2442, 'Male': 5193},
 {'Female': 2445, 'Male': 5199},
 {'Female': 2442, 'Male': 5195},
 {'Female': 2414, 'Male': 5024},
 {'Female': 2443, 'Male': 5192},
 {'Female': 2443, 'Male': 5192},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2444, 'Male': 5177},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2444, 'Male': 5192},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2443, 'Male': 5193},
 {'Female': 2443, 'Male': 5191},
 {'Female': 2444, 'Male': 5190},
 {'Female': 2436, 'Male': 5190},
 {'Female': 2443, 'Male': 5185},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2424, 'Male': 5114},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2428, 'Male': 5168},
 {'Female': 2444, 'Male': 5193},
 {'Female': 2443, 'Male': 5190},
 {'Female': 2440, 'Male': 5167},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2439, 'Male': 5188},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2443, 'Male': 5192},
 {'Female': 2445, 'Male': 5192},
 {'Female': 2445, 'Male': 5189},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2444, 'Male': 5191},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2443, 'Male': 5199},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2443, 'Male': 5199},
 {'Female': 2444, 'Male': 5187},
 {'Female': 2441, 'Male': 5195},
 {'Female': 2414, 'Male': 5139},
 {'Female': 2445, 'Male': 5191},
 {'Female': 2442, 'Male': 5190},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2432, 'Male': 5172},
 {'Female': 2439, 'Male': 5183},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2439, 'Male': 5166},
 {'Female': 2443, 'Male': 5196},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2442, 'Male': 5197},
 {'Female': 2441, 'Male': 5193},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2444, 'Male': 5192},
 {'Female': 2436, 'Male': 5182},
 {'Female': 2437, 'Male': 5163},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2442, 'Male': 5184},
 {'Female': 2442, 'Male': 5157},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5192},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2443, 'Male': 5191},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2438, 'Male': 5187},
 {'Female': 2444, 'Male': 5192},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2441, 'Male': 5186},
 {'Female': 2443, 'Male': 5188},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2422, 'Male': 5082},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2446, 'Male': 5199},
 {'Female': 2436, 'Male': 5198},
 {'Female': 2442, 'Male': 5193},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2439, 'Male': 5192},
 {'Female': 2446, 'Male': 5186},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2437, 'Male': 5154},
 {'Female': 2446, 'Male': 5192},
 {'Female': 2442, 'Male': 5132},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2443, 'Male': 5196},
 {'Female': 2445, 'Male': 5199},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2443, 'Male': 5196},
 {'Female': 2438, 'Male': 5179},
 {'Female': 2438, 'Male': 5195},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2445, 'Male': 5186},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2445, 'Male': 5191},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2441, 'Male': 5193},
 {'Female': 2446, 'Male': 5192},
 {'Female': 2438, 'Male': 5157},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2443, 'Male': 5194},
 {'Female': 2446, 'Male': 5190},
 {'Female': 2443, 'Male': 5187},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2444, 'Male': 5193},
 {'Female': 2443, 'Male': 5191},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2446, 'Male': 5188},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2443, 'Male': 5190},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2442, 'Male': 5197},
 {'Female': 2442, 'Male': 5193},
 {'Female': 2420, 'Male': 5184},
 {'Female': 2443, 'Male': 5197},
 {'Female': 2445, 'Male': 5199},
 {'Female': 2440, 'Male': 5197},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2445, 'Male': 5191},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2445, 'Male': 5199},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2436, 'Male': 5193},
 {'Female': 2444, 'Male': 5194},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2431, 'Male': 5191},
 {'Female': 2445, 'Male': 5196},
 {'Female': 2441, 'Male': 5183},
 {'Female': 2420, 'Male': 5164},
 {'Female': 2444, 'Male': 5198},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2421, 'Male': 5124},
 {'Female': 2445, 'Male': 5190},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2440, 'Male': 5195},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2445, 'Male': 5192},
 {'Female': 2445, 'Male': 5190},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2445, 'Male': 5188},
 {'Female': 2445, 'Male': 5194},
 {'Female': 2439, 'Male': 5164},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2443, 'Male': 5196},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2442, 'Male': 5194},
 {'Female': 2443, 'Male': 5194},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2446, 'Male': 5195},
 {'Female': 2443, 'Male': 5193},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2444, 'Male': 5196},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2444, 'Male': 5195},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2443, 'Male': 5193},
 {'Female': 2445, 'Male': 5184},
 {'Female': 2443, 'Male': 5191},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2441, 'Male': 5195},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2444, 'Male': 5197},
 {'Female': 2446, 'Male': 5191},
 {'Female': 2446, 'Male': 5193},
 {'Female': 2442, 'Male': 5198},
 {'Female': 2445, 'Male': 5191},
 {'Female': 2445, 'Male': 5195},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2443, 'Male': 5191},
 {'Female': 2445, 'Male': 5188},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2446, 'Male': 5197},
 {'Female': 2443, 'Male': 5195},
 {'Female': 2443, 'Male': 5198},
 {'Female': 2445, 'Male': 5197},
 {'Female': 2446, 'Male': 5196},
 {'Female': 2443, 'Male': 5191},
 {'Female': 2444, 'Male': 5199},
 {'Female': 2446, 'Male': 5198},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2446, 'Male': 5194},
 {'Female': 2444, 'Male': 5193},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2441, 'Male': 5183},
 {'Female': 2445, 'Male': 5198},
 {'Female': 2442, 'Male': 5194},
 {'Female': 2442, 'Male': 5185},
 {'Female': 2445, 'Male': 5198},

In [18]:
print(type_count)

[('Male', 5199), ('Female', 2446)]

In [19]:
num_item = len(train_df['item_id'].unique())
num_user = len(train_df['user_id'].unique())
num_type = len(key_type)
print('items number : ',num_item)
print('users number : ',num_user)
print('user types : ',key_type)

items number :  2271
users number :  7645
user types :  ['Female', 'Male']

In [20]:
dict_args["num_type"] = len(key_type)

In [21]:
user_type_list = [] #preprocessing to be sure that user types are really the right ones armielle 
for u in range(num_user):
    gl = user_idd_type_list[u]
    tmp = []
    for g in gl:
        if g in key_type:
            tmp.append(g)
    user_type_list.append(tmp)

print(len(user_type_list))

7645

In [22]:
len(user_type_list)

7645

In [23]:
print('*' * 50)
print('number of positive feedback: ' + str(len(train_df)))
print('estimated number of training samples: ' + str(neg * len(train_df)))
print('*' * 50)

**************************************************
number of positive feedback: 18968
estimated number of training samples: 94840
**************************************************

In [24]:
# generate user_type matrix
type_user_indicator = np.zeros((num_type, num_user))

for k in range(num_type):
    type_user_indicator[k,:] = type_user_vector[key_type[k]]

In [25]:
precision = np.zeros(4)
recall = np.zeros(4)
f1 = np.zeros(4)
ndcg = np.zeros(4)
RSP = np.zeros(4)
REO = np.zeros(4)

precision

array([0., 0., 0., 0.])

In [26]:
len(user_type_list)

7645

In [27]:
train_df['item_id'].unique()

array([   0,    1,    2, ..., 2287,   29, 1177], dtype=int64)

In [28]:
#tf.compat.v1.disable_eager_execution()

for i in range(n):
    #with tf.compat.v1.Session() as sess:
    with tf.Session() as sess:
        bpr = BPR(sess, dict_args, train_df, test_df, key_type, user_type_list, item_type_count)
        [prec_one, rec_one, f_one, ndcg_one, Rec] = bpr.run()

**********BPR**********
Training // Epoch 1 //  Total cost = 65987.17876 Training time : 3001 ms negative Sampling time : 12832 ms negative samples : 94840
precision_1	[0.0015697],	||	 precision_5	[0.0013865],	||	 precision_10	[0.0012034],	||	 precision_15	[0.0011162]
recall_1   	[0.0015697],	||	 recall_5   	[0.0068454],	||	 recall_10   	[0.0118814],	||	 recall_15   	[0.0165250]
f_measure_1	[0.0015697],	||	 f_measure_5	[0.0023060],	||	 f_measure_10	[0.0021854],	||	 f_measure_15	[0.0020911]
ndcg_1     	[0.0015697],	||	 ndcg_5     	[0.0042381],	||	 ndcg_10     	[0.0058536],	||	 ndcg_15     	[0.0070846]
Metrics for user type	 Female
precision_1	[0.0016353],	||	 precision_5	[0.0011447],	||	 precision_10	[0.0011447],	||	 precision_15	[0.0008994]
recall_1	[0.0016353],	||	 recall_5	[0.0057236],	||	 recall_10	[0.0114473],	||	 recall_15	[0.0134914]
ndcg_1	[0.0016353],	||	 ndcg_5	[0.0033915],	||	 ndcg_10	[0.0052582],	||	 ndcg_15	[0.0058052]
AUC per user type	[0.4953815]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0015003],	||	 precision_10	[0.0012310],	||	 precision_15	[0.0012182]
recall_1	[0.0015388],	||	 recall_5	[0.0073732],	||	 recall_10	[0.0120857],	||	 recall_15	[0.0179522]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0046365],	||	 ndcg_10	[0.0061338],	||	 ndcg_15	[0.0076866]
AUC per user type	[0.5022030]
AUC global is:  0.5000204618406315
Testing // Epoch 1 // Testing time : 93129 ms
========================================================================================================================================================================================================
Training // Epoch 2 //  Total cost = 65946.14176 Training time : 2061 ms negative Sampling time : 15200 ms negative samples : 94840
precision_1	[0.0013080],	||	 precision_5	[0.0011511],	||	 precision_10	[0.0010988],	||	 precision_15	[0.0010377]
recall_1   	[0.0013080],	||	 recall_5   	[0.0057554],	||	 recall_10   	[0.0109876],	||	 recall_15   	[0.0152256]
f_measure_1	[0.0013080],	||	 f_measure_5	[0.0019185],	||	 f_measure_10	[0.0019977],	||	 f_measure_15	[0.0019430]
ndcg_1     	[0.0013080],	||	 ndcg_5     	[0.0034882],	||	 ndcg_10     	[0.0051408],	||	 ndcg_15     	[0.0062789]
Metrics for user type	 Female
precision_1	[0.0008177],	||	 precision_5	[0.0009812],	||	 precision_10	[0.0010221],	||	 precision_15	[0.0011447]
recall_1	[0.0008177],	||	 recall_5	[0.0049060],	||	 recall_10	[0.0102208],	||	 recall_15	[0.0163123]
ndcg_1	[0.0008177],	||	 ndcg_5	[0.0028555],	||	 ndcg_10	[0.0045324],	||	 ndcg_15	[0.0061962]
AUC per user type	[0.5020743]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0012310],	||	 precision_10	[0.0011348],	||	 precision_15	[0.0009874]
recall_1	[0.0015388],	||	 recall_5	[0.0061550],	||	 recall_10	[0.0113483],	||	 recall_15	[0.0147144]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0037859],	||	 ndcg_10	[0.0054270],	||	 ndcg_15	[0.0063178]
AUC per user type	[0.4928358]
AUC global is:  0.49579160325922805
Testing // Epoch 2 // Testing time : 84811 ms
========================================================================================================================================================================================================
Training // Epoch 3 //  Total cost = 65988.81422 Training time : 638 ms negative Sampling time : 10873 ms negative samples : 94840
precision_1	[0.0018313],	||	 precision_5	[0.0013080],	||	 precision_10	[0.0011380],	||	 precision_15	[0.0011424]
recall_1   	[0.0018313],	||	 recall_5   	[0.0063876],	||	 recall_10   	[0.0112274],	||	 recall_15   	[0.0169828]
f_measure_1	[0.0018313],	||	 f_measure_5	[0.0021714],	||	 f_measure_10	[0.0020665],	||	 f_measure_15	[0.0021407]
ndcg_1     	[0.0018313],	||	 ndcg_5     	[0.0040946],	||	 ndcg_10     	[0.0056275],	||	 ndcg_15     	[0.0071632]
Metrics for user type	 Female
precision_1	[0.0024530],	||	 precision_5	[0.0010630],	||	 precision_10	[0.0009812],	||	 precision_15	[0.0009267]
recall_1	[0.0024530],	||	 recall_5	[0.0053148],	||	 recall_10	[0.0098119],	||	 recall_15	[0.0139002]
ndcg_1	[0.0024530],	||	 ndcg_5	[0.0040697],	||	 ndcg_10	[0.0054656],	||	 ndcg_15	[0.0065368]
AUC per user type	[0.4898550]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0014234],	||	 precision_10	[0.0012118],	||	 precision_15	[0.0012438]
recall_1	[0.0015388],	||	 recall_5	[0.0068924],	||	 recall_10	[0.0118933],	||	 recall_15	[0.0184330]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0041063],	||	 ndcg_10	[0.0057037],	||	 ndcg_15	[0.0074579]
AUC per user type	[0.4979096]
AUC global is:  0.4953325285524176
Testing // Epoch 3 // Testing time : 61123 ms
========================================================================================================================================================================================================
Training // Epoch 4 //  Total cost = 65944.49429 Training time : 608 ms negative Sampling time : 10772 ms negative samples : 94840
precision_1	[0.0057554],	||	 precision_5	[0.0020405],	||	 precision_10	[0.0016351],	||	 precision_15	[0.0013429]
recall_1   	[0.0057554],	||	 recall_5   	[0.0102027],	||	 recall_10   	[0.0162634],	||	 recall_15   	[0.0198605]
f_measure_1	[0.0057554],	||	 f_measure_5	[0.0034009],	||	 f_measure_10	[0.0029714],	||	 f_measure_15	[0.0025157]
ndcg_1     	[0.0057554],	||	 ndcg_5     	[0.0078774],	||	 ndcg_10     	[0.0098733],	||	 ndcg_15     	[0.0108278]
Metrics for user type	 Female
precision_1	[0.0057236],	||	 precision_5	[0.0022895],	||	 precision_10	[0.0017171],	||	 precision_15	[0.0013628]
recall_1	[0.0057236],	||	 recall_5	[0.0114473],	||	 recall_10	[0.0168983],	||	 recall_15	[0.0198624]
ndcg_1	[0.0057236],	||	 ndcg_5	[0.0085474],	||	 ndcg_10	[0.0103490],	||	 ndcg_15	[0.0111459]
AUC per user type	[0.5090065]
Metrics for user type	 Male
precision_1	[0.0057703],	||	 precision_5	[0.0019234],	||	 precision_10	[0.0015965],	||	 precision_15	[0.0013336]
recall_1	[0.0057703],	||	 recall_5	[0.0096172],	||	 recall_10	[0.0159646],	||	 recall_15	[0.0198596]
ndcg_1	[0.0057703],	||	 ndcg_5	[0.0075622],	||	 ndcg_10	[0.0096495],	||	 ndcg_15	[0.0106781]
AUC per user type	[0.4954945]
AUC global is:  0.4998176316155783
Testing // Epoch 4 // Testing time : 65789 ms
========================================================================================================================================================================================================
Training // Epoch 5 //  Total cost = 65997.14336 Training time : 602 ms negative Sampling time : 11682 ms negative samples : 94840
precision_1	[0.0009156],	||	 precision_5	[0.0012296],	||	 precision_10	[0.0011249],	||	 precision_15	[0.0010377]
recall_1   	[0.0009156],	||	 recall_5   	[0.0061478],	||	 recall_10   	[0.0112492],	||	 recall_15   	[0.0155657]
f_measure_1	[0.0009156],	||	 f_measure_5	[0.0020493],	||	 f_measure_10	[0.0020453],	||	 f_measure_15	[0.0019457]
ndcg_1     	[0.0009156],	||	 ndcg_5     	[0.0034415],	||	 ndcg_10     	[0.0050618],	||	 ndcg_15     	[0.0061977]
Metrics for user type	 Female
precision_1	[0.0012265],	||	 precision_5	[0.0007359],	||	 precision_10	[0.0006541],	||	 precision_15	[0.0007359]
recall_1	[0.0012265],	||	 recall_5	[0.0036795],	||	 recall_10	[0.0065413],	||	 recall_15	[0.0110384]
ndcg_1	[0.0012265],	||	 ndcg_5	[0.0023857],	||	 ndcg_10	[0.0032717],	||	 ndcg_15	[0.0044563]
AUC per user type	[0.4939380]
Metrics for user type	 Male
precision_1	[0.0007694],	||	 precision_5	[0.0014618],	||	 precision_10	[0.0013464],	||	 precision_15	[0.0011797]
recall_1	[0.0007694],	||	 recall_5	[0.0073091],	||	 recall_10	[0.0134641],	||	 recall_15	[0.0176957]
ndcg_1	[0.0007694],	||	 ndcg_5	[0.0039383],	||	 ndcg_10	[0.0059040],	||	 ndcg_15	[0.0070170]
AUC per user type	[0.5028843]
AUC global is:  0.5000219684831259
Testing // Epoch 5 // Testing time : 63826 ms
========================================================================================================================================================================================================
Training // Epoch 6 //  Total cost = 66002.86220 Training time : 739 ms negative Sampling time : 10719 ms negative samples : 94840
WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py:963: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.

precision_1	[0.0013080],	||	 precision_5	[0.0014127],	||	 precision_10	[0.0011903],	||	 precision_15	[0.0011598]
recall_1   	[0.0012034],	||	 recall_5   	[0.0068542],	||	 recall_10   	[0.0116939],	||	 recall_15   	[0.0171223]
f_measure_1	[0.0012535],	||	 f_measure_5	[0.0023426],	||	 f_measure_10	[0.0021607],	||	 f_measure_15	[0.0021724]
ndcg_1     	[0.0013080],	||	 ndcg_5     	[0.0039803],	||	 ndcg_10     	[0.0055213],	||	 ndcg_15     	[0.0069493]
Metrics for user type	 Female
precision_1	[0.0012265],	||	 precision_5	[0.0017989],	||	 precision_10	[0.0013900],	||	 precision_15	[0.0012265]
recall_1	[0.0008994],	||	 recall_5	[0.0083401],	||	 recall_10	[0.0132461],	||	 recall_15	[0.0177433]
ndcg_1	[0.0012265],	||	 ndcg_5	[0.0046977],	||	 ndcg_10	[0.0062123],	||	 ndcg_15	[0.0073886]
AUC per user type	[0.5105137]
Metrics for user type	 Male
precision_1	[0.0013464],	||	 precision_5	[0.0012310],	||	 precision_10	[0.0010964],	||	 precision_15	[0.0011284]
recall_1	[0.0013464],	||	 recall_5	[0.0061550],	||	 recall_10	[0.0109636],	||	 recall_15	[0.0168302]
ndcg_1	[0.0013464],	||	 ndcg_5	[0.0036428],	||	 ndcg_10	[0.0051961],	||	 ndcg_15	[0.0067426]
AUC per user type	[0.4993808]
AUC global is:  0.502942759181159
Testing // Epoch 6 // Testing time : 60516 ms
========================================================================================================================================================================================================
Training // Epoch 7 //  Total cost = 65978.64317 Training time : 691 ms negative Sampling time : 12401 ms negative samples : 94840
precision_1	[0.0014388],	||	 precision_5	[0.0008633],	||	 precision_10	[0.0008110],	||	 precision_15	[0.0008546]
recall_1   	[0.0014388],	||	 recall_5   	[0.0043165],	||	 recall_10   	[0.0080009],	||	 recall_15   	[0.0126226]
f_measure_1	[0.0014388],	||	 f_measure_5	[0.0014388],	||	 f_measure_10	[0.0014727],	||	 f_measure_15	[0.0016008]
ndcg_1     	[0.0014388],	||	 ndcg_5     	[0.0028610],	||	 ndcg_10     	[0.0040498],	||	 ndcg_15     	[0.0052809]
Metrics for user type	 Female
precision_1	[0.0012265],	||	 precision_5	[0.0010630],	||	 precision_10	[0.0007768],	||	 precision_15	[0.0009267]
recall_1	[0.0012265],	||	 recall_5	[0.0053148],	||	 recall_10	[0.0077678],	||	 recall_15	[0.0136277]
ndcg_1	[0.0012265],	||	 ndcg_5	[0.0031464],	||	 ndcg_10	[0.0039050],	||	 ndcg_15	[0.0054668]
AUC per user type	[0.4978742]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0007694],	||	 precision_10	[0.0008271],	||	 precision_15	[0.0008207]
recall_1	[0.0015388],	||	 recall_5	[0.0038469],	||	 recall_10	[0.0081105],	||	 recall_15	[0.0121498]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0027268],	||	 ndcg_10	[0.0041180],	||	 ndcg_15	[0.0051935]
AUC per user type	[0.4923608]
AUC global is:  0.494124770273924
Testing // Epoch 7 // Testing time : 65209 ms
========================================================================================================================================================================================================
Training // Epoch 8 //  Total cost = 65910.44618 Training time : 595 ms negative Sampling time : 14361 ms negative samples : 94840
precision_1	[0.0049706],	||	 precision_5	[0.0016481],	||	 precision_10	[0.0013996],	||	 precision_15	[0.0012296]
recall_1   	[0.0049706],	||	 recall_5   	[0.0080488],	||	 recall_10   	[0.0137170],	||	 recall_15   	[0.0180118]
f_measure_1	[0.0049706],	||	 f_measure_5	[0.0027360],	||	 f_measure_10	[0.0025400],	||	 f_measure_15	[0.0023020]
ndcg_1     	[0.0049706],	||	 ndcg_5     	[0.0065387],	||	 ndcg_10     	[0.0083586],	||	 ndcg_15     	[0.0095099]
Metrics for user type	 Female
precision_1	[0.0044971],	||	 precision_5	[0.0015536],	||	 precision_10	[0.0013083],	||	 precision_15	[0.0011992]
recall_1	[0.0044971],	||	 recall_5	[0.0074952],	||	 recall_10	[0.0125375],	||	 recall_15	[0.0171709]
ndcg_1	[0.0044971],	||	 ndcg_5	[0.0060599],	||	 ndcg_10	[0.0076850],	||	 ndcg_15	[0.0089325]
AUC per user type	[0.5018829]
Metrics for user type	 Male
precision_1	[0.0051933],	||	 precision_5	[0.0016926],	||	 precision_10	[0.0014426],	||	 precision_15	[0.0012438]
recall_1	[0.0051933],	||	 recall_5	[0.0083093],	||	 recall_10	[0.0142720],	||	 recall_15	[0.0184074]
ndcg_1	[0.0051933],	||	 ndcg_5	[0.0067640],	||	 ndcg_10	[0.0086754],	||	 ndcg_15	[0.0097815]
AUC per user type	[0.4966155]
AUC global is:  0.4983007709419753
Testing // Epoch 8 // Testing time : 61609 ms
========================================================================================================================================================================================================
Training // Epoch 9 //  Total cost = 66060.58112 Training time : 926 ms negative Sampling time : 26249 ms negative samples : 94840
precision_1	[0.0010464],	||	 precision_5	[0.0009418],	||	 precision_10	[0.0009680],	||	 precision_15	[0.0009244]
recall_1   	[0.0010464],	||	 recall_5   	[0.0046436],	||	 recall_10   	[0.0095487],	||	 recall_15   	[0.0135383]
f_measure_1	[0.0010464],	||	 f_measure_5	[0.0015660],	||	 f_measure_10	[0.0017577],	||	 f_measure_15	[0.0017305]
ndcg_1     	[0.0010464],	||	 ndcg_5     	[0.0028705],	||	 ndcg_10     	[0.0044570],	||	 ndcg_15     	[0.0055340]
Metrics for user type	 Female
precision_1	[0.0004088],	||	 precision_5	[0.0005724],	||	 precision_10	[0.0006541],	||	 precision_15	[0.0007359]
recall_1	[0.0004088],	||	 recall_5	[0.0026574],	||	 recall_10	[0.0063369],	||	 recall_15	[0.0106296]
ndcg_1	[0.0004088],	||	 ndcg_5	[0.0015397],	||	 ndcg_10	[0.0027345],	||	 ndcg_15	[0.0038853]
AUC per user type	[0.5054003]
Metrics for user type	 Male
precision_1	[0.0013464],	||	 precision_5	[0.0011156],	||	 precision_10	[0.0011156],	||	 precision_15	[0.0010130]
recall_1	[0.0013464],	||	 recall_5	[0.0055780],	||	 recall_10	[0.0110598],	||	 recall_15	[0.0149067]
ndcg_1	[0.0013464],	||	 ndcg_5	[0.0034966],	||	 ndcg_10	[0.0052674],	||	 ndcg_15	[0.0063097]
AUC per user type	[0.5040692]
AUC global is:  0.504495073106499
Testing // Epoch 9 // Testing time : 63574 ms
========================================================================================================================================================================================================
Training // Epoch 10 //  Total cost = 65946.47581 Training time : 591 ms negative Sampling time : 10902 ms negative samples : 94840
precision_1	[0.0006540],	||	 precision_5	[0.0011249],	||	 precision_10	[0.0011903],	||	 precision_15	[0.0011336]
recall_1   	[0.0006540],	||	 recall_5   	[0.0056246],	||	 recall_10   	[0.0118378],	||	 recall_15   	[0.0169392]
f_measure_1	[0.0006540],	||	 f_measure_5	[0.0018749],	||	 f_measure_10	[0.0021631],	||	 f_measure_15	[0.0021251]
ndcg_1     	[0.0006540],	||	 ndcg_5     	[0.0032658],	||	 ndcg_10     	[0.0052166],	||	 ndcg_15     	[0.0065583]
Metrics for user type	 Female
precision_1	[0.0008177],	||	 precision_5	[0.0011447],	||	 precision_10	[0.0011447],	||	 precision_15	[0.0009812]
recall_1	[0.0008177],	||	 recall_5	[0.0057236],	||	 recall_10	[0.0114473],	||	 recall_15	[0.0147179]
ndcg_1	[0.0008177],	||	 ndcg_5	[0.0033251],	||	 ndcg_10	[0.0051129],	||	 ndcg_15	[0.0059745]
AUC per user type	[0.5036323]
Metrics for user type	 Male
precision_1	[0.0005770],	||	 precision_5	[0.0011156],	||	 precision_10	[0.0012118],	||	 precision_15	[0.0012054]
recall_1	[0.0005770],	||	 recall_5	[0.0055780],	||	 recall_10	[0.0120215],	||	 recall_15	[0.0179842]
ndcg_1	[0.0005770],	||	 ndcg_5	[0.0032378],	||	 ndcg_10	[0.0052654],	||	 ndcg_15	[0.0068330]
AUC per user type	[0.4985237]
AUC global is:  0.5001581759175066
Testing // Epoch 10 // Testing time : 59586 ms
========================================================================================================================================================================================================
Training // Epoch 11 //  Total cost = 65953.38158 Training time : 557 ms negative Sampling time : 10373 ms negative samples : 94840
precision_1	[0.0054938],	||	 precision_5	[0.0021714],	||	 precision_10	[0.0018051],	||	 precision_15	[0.0015348]
recall_1   	[0.0054284],	||	 recall_5   	[0.0107914],	||	 recall_10   	[0.0179856],	||	 recall_15   	[0.0228908]
f_measure_1	[0.0054609],	||	 f_measure_5	[0.0036153],	||	 f_measure_10	[0.0032809],	||	 f_measure_15	[0.0028767]
ndcg_1     	[0.0054938],	||	 ndcg_5     	[0.0082477],	||	 ndcg_10     	[0.0105527],	||	 ndcg_15     	[0.0118452]

Metrics for user type	 Female
precision_1	[0.0040883],	||	 precision_5	[0.0017989],	||	 precision_10	[0.0014718],	||	 precision_15	[0.0013355]
recall_1	[0.0038839],	||	 recall_5	[0.0087899],	||	 recall_10	[0.0145135],	||	 recall_15	[0.0198283]
ndcg_1	[0.0040883],	||	 ndcg_5	[0.0064660],	||	 ndcg_10	[0.0083261],	||	 ndcg_15	[0.0097289]
AUC per user type	[0.5031700]
Metrics for user type	 Male
precision_1	[0.0061550],	||	 precision_5	[0.0023466],	||	 precision_10	[0.0019619],	||	 precision_15	[0.0016285]
recall_1	[0.0061550],	||	 recall_5	[0.0117330],	||	 recall_10	[0.0196192],	||	 recall_15	[0.0243316]
ndcg_1	[0.0061550],	||	 ndcg_5	[0.0090860],	||	 ndcg_10	[0.0116002],	||	 ndcg_15	[0.0128410]
AUC per user type	[0.5032750]
AUC global is:  0.5032413917838381
Testing // Epoch 11 // Testing time : 59292 ms
========================================================================================================================================================================================================
Training // Epoch 12 //  Total cost = 66015.27704 Training time : 532 ms negative Sampling time : 10739 ms negative samples : 94840
precision_1	[0.0011772],	||	 precision_5	[0.0008895],	||	 precision_10	[0.0008633],	||	 precision_15	[0.0008720]
recall_1   	[0.0011772],	||	 recall_5   	[0.0043427],	||	 recall_10   	[0.0084238],	||	 recall_15   	[0.0124504]
f_measure_1	[0.0011772],	||	 f_measure_5	[0.0014765],	||	 f_measure_10	[0.0015661],	||	 f_measure_15	[0.0016299]
ndcg_1     	[0.0011772],	||	 ndcg_5     	[0.0028851],	||	 ndcg_10     	[0.0041728],	||	 ndcg_15     	[0.0052526]
Metrics for user type	 Female
precision_1	[0.0004088],	||	 precision_5	[0.0010630],	||	 precision_10	[0.0008994],	||	 precision_15	[0.0008994]
recall_1	[0.0004088],	||	 recall_5	[0.0049877],	||	 recall_10	[0.0083401],	||	 recall_15	[0.0128373]
ndcg_1	[0.0004088],	||	 ndcg_5	[0.0026360],	||	 ndcg_10	[0.0036987],	||	 ndcg_15	[0.0048836]
AUC per user type	[0.4958510]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0008078],	||	 precision_10	[0.0008463],	||	 precision_15	[0.0008591]
recall_1	[0.0015388],	||	 recall_5	[0.0040392],	||	 recall_10	[0.0084632],	||	 recall_15	[0.0122684]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0030023],	||	 ndcg_10	[0.0043959],	||	 ndcg_15	[0.0054262]
AUC per user type	[0.5004565]
AUC global is:  0.49898298481831377
Testing // Epoch 12 // Testing time : 59493 ms
========================================================================================================================================================================================================
Training // Epoch 13 //  Total cost = 65927.96467 Training time : 583 ms negative Sampling time : 10904 ms negative samples : 94840
precision_1	[0.0015697],	||	 precision_5	[0.0010464],	||	 precision_10	[0.0008764],	||	 precision_15	[0.0008982]
recall_1   	[0.0015697],	||	 recall_5   	[0.0052322],	||	 recall_10   	[0.0087639],	||	 recall_15   	[0.0132985]
f_measure_1	[0.0015697],	||	 f_measure_5	[0.0017441],	||	 f_measure_10	[0.0015934],	||	 f_measure_15	[0.0016827]
ndcg_1     	[0.0015697],	||	 ndcg_5     	[0.0033719],	||	 ndcg_10     	[0.0045138],	||	 ndcg_15     	[0.0057250]
Metrics for user type	 Female
precision_1	[0.0012265],	||	 precision_5	[0.0009812],	||	 precision_10	[0.0007359],	||	 precision_15	[0.0007904]
recall_1	[0.0012265],	||	 recall_5	[0.0049060],	||	 recall_10	[0.0073590],	||	 recall_15	[0.0118561]
ndcg_1	[0.0012265],	||	 ndcg_5	[0.0029422],	||	 ndcg_10	[0.0037174],	||	 ndcg_15	[0.0049038]
AUC per user type	[0.5005133]
Metrics for user type	 Male
precision_1	[0.0017311],	||	 precision_5	[0.0010771],	||	 precision_10	[0.0009425],	||	 precision_15	[0.0009489]
recall_1	[0.0017311],	||	 recall_5	[0.0053857],	||	 recall_10	[0.0094249],	||	 recall_15	[0.0139770]
ndcg_1	[0.0017311],	||	 ndcg_5	[0.0035741],	||	 ndcg_10	[0.0048885],	||	 ndcg_15	[0.0061114]
AUC per user type	[0.4997276]
AUC global is:  0.49997895412894083
Testing // Epoch 13 // Testing time : 59356 ms
========================================================================================================================================================================================================
Training // Epoch 14 //  Total cost = 65995.93901 Training time : 715 ms negative Sampling time : 10674 ms negative samples : 94840
precision_1	[0.0009156],	||	 precision_5	[0.0012557],	||	 precision_10	[0.0010203],	||	 precision_15	[0.0009505]
recall_1   	[0.0009156],	||	 recall_5   	[0.0062132],	||	 recall_10   	[0.0099847],	||	 recall_15   	[0.0140397]
f_measure_1	[0.0009156],	||	 f_measure_5	[0.0020892],	||	 f_measure_10	[0.0018514],	||	 f_measure_15	[0.0017805]
ndcg_1     	[0.0009156],	||	 ndcg_5     	[0.0035934],	||	 ndcg_10     	[0.0048325],	||	 ndcg_15     	[0.0059018]
Metrics for user type	 Female
precision_1	[0.0004088],	||	 precision_5	[0.0012265],	||	 precision_10	[0.0008585],	||	 precision_15	[0.0008994]
recall_1	[0.0004088],	||	 recall_5	[0.0059280],	||	 recall_10	[0.0081085],	||	 recall_15	[0.0130144]
ndcg_1	[0.0004088],	||	 ndcg_5	[0.0033427],	||	 ndcg_10	[0.0041088],	||	 ndcg_15	[0.0054064]
AUC per user type	[0.5011090]
Metrics for user type	 Male
precision_1	[0.0011541],	||	 precision_5	[0.0012695],	||	 precision_10	[0.0010964],	||	 precision_15	[0.0009745]
recall_1	[0.0011541],	||	 recall_5	[0.0063474],	||	 recall_10	[0.0108675],	||	 recall_15	[0.0145220]
ndcg_1	[0.0011541],	||	 ndcg_5	[0.0037114],	||	 ndcg_10	[0.0051731],	||	 ndcg_15	[0.0061348]
AUC per user type	[0.4960079]
AUC global is:  0.497639997192185
Testing // Epoch 14 // Testing time : 58989 ms
========================================================================================================================================================================================================
Training // Epoch 15 //  Total cost = 65955.62320 Training time : 584 ms negative Sampling time : 10803 ms negative samples : 94840
precision_1	[0.0037933],	||	 precision_5	[0.0020144],	||	 precision_10	[0.0013865],	||	 precision_15	[0.0012383]
recall_1   	[0.0037933],	||	 recall_5   	[0.0100065],	||	 recall_10   	[0.0137999],	||	 recall_15   	[0.0185088]
f_measure_1	[0.0037933],	||	 f_measure_5	[0.0033537],	||	 f_measure_10	[0.0025199],	||	 f_measure_15	[0.0023213]
ndcg_1     	[0.0037933],	||	 ndcg_5     	[0.0069041],	||	 ndcg_10     	[0.0081005],	||	 ndcg_15     	[0.0093315]
Metrics for user type	 Female
precision_1	[0.0028618],	||	 precision_5	[0.0016353],	||	 precision_10	[0.0011856],	||	 precision_15	[0.0009812]
recall_1	[0.0028618],	||	 recall_5	[0.0081766],	||	 recall_10	[0.0118561],	||	 recall_15	[0.0147179]
ndcg_1	[0.0028618],	||	 ndcg_5	[0.0055202],	||	 ndcg_10	[0.0066583],	||	 ndcg_15	[0.0073956]
AUC per user type	[0.5022372]
Metrics for user type	 Male
precision_1	[0.0042316],	||	 precision_5	[0.0021927],	||	 precision_10	[0.0014811],	||	 precision_15	[0.0013592]
recall_1	[0.0042316],	||	 recall_5	[0.0108675],	||	 recall_10	[0.0147144],	||	 recall_15	[0.0202924]
ndcg_1	[0.0042316],	||	 ndcg_5	[0.0075553],	||	 ndcg_10	[0.0087791],	||	 ndcg_15	[0.0102423]
AUC per user type	[0.4989111]
AUC global is:  0.49997529511618655
Testing // Epoch 15 // Testing time : 71496 ms
========================================================================================================================================================================================================
Training // Epoch 16 //  Total cost = 65987.06747 Training time : 590 ms negative Sampling time : 10799 ms negative samples : 94840
precision_1	[0.0056246],	||	 precision_5	[0.0021714],	||	 precision_10	[0.0016220],	||	 precision_15	[0.0012993]
recall_1   	[0.0056246],	||	 recall_5   	[0.0107914],	||	 recall_10   	[0.0160562],	||	 recall_15   	[0.0193264]
f_measure_1	[0.0056246],	||	 f_measure_5	[0.0036153],	||	 f_measure_10	[0.0029463],	||	 f_measure_15	[0.0024349]
ndcg_1     	[0.0056246],	||	 ndcg_5     	[0.0082768],	||	 ndcg_10     	[0.0099902],	||	 ndcg_15     	[0.0108528]
Metrics for user type	 Female
precision_1	[0.0040883],	||	 precision_5	[0.0022895],	||	 precision_10	[0.0019624],	||	 precision_15	[0.0015263]
recall_1	[0.0040883],	||	 recall_5	[0.0114473],	||	 recall_10	[0.0193173],	||	 recall_15	[0.0225879]
ndcg_1	[0.0040883],	||	 ndcg_5	[0.0078579],	||	 ndcg_10	[0.0104683],	||	 ndcg_15	[0.0113351]
AUC per user type	[0.4981147]
Metrics for user type	 Male
precision_1	[0.0063474],	||	 precision_5	[0.0021158],	||	 precision_10	[0.0014618],	||	 precision_15	[0.0011925]
recall_1	[0.0063474],	||	 recall_5	[0.0104828],	||	 recall_10	[0.0145220],	||	 recall_15	[0.0177919]
ndcg_1	[0.0063474],	||	 ndcg_5	[0.0084739],	||	 ndcg_10	[0.0097652],	||	 ndcg_15	[0.0106259]
AUC per user type	[0.4887975]

AUC global is:  0.4917785170769817
Testing // Epoch 16 // Testing time : 62035 ms
========================================================================================================================================================================================================
Training // Epoch 17 //  Total cost = 65971.92554 Training time : 738 ms negative Sampling time : 18013 ms negative samples : 94840
precision_1	[0.0044474],	||	 precision_5	[0.0018313],	||	 precision_10	[0.0012688],	||	 precision_15	[0.0011424]
recall_1   	[0.0043427],	||	 recall_5   	[0.0089427],	||	 recall_10   	[0.0124744],	||	 recall_15   	[0.0169217]
f_measure_1	[0.0043944],	||	 f_measure_5	[0.0030400],	||	 f_measure_10	[0.0023033],	||	 f_measure_15	[0.0021402]
ndcg_1     	[0.0044474],	||	 ndcg_5     	[0.0066683],	||	 ndcg_10     	[0.0078040],	||	 ndcg_15     	[0.0089757]
Metrics for user type	 Female
precision_1	[0.0024530],	||	 precision_5	[0.0012265],	||	 precision_10	[0.0008585],	||	 precision_15	[0.0007904]
recall_1	[0.0024530],	||	 recall_5	[0.0061325],	||	 recall_10	[0.0085854],	||	 recall_15	[0.0118561]
ndcg_1	[0.0024530],	||	 ndcg_5	[0.0042717],	||	 ndcg_10	[0.0050420],	||	 ndcg_15	[0.0059027]
AUC per user type	[0.5082254]
Metrics for user type	 Male
precision_1	[0.0053857],	||	 precision_5	[0.0021158],	||	 precision_10	[0.0014618],	||	 precision_15	[0.0013079]
recall_1	[0.0052318],	||	 recall_5	[0.0102648],	||	 recall_10	[0.0143040],	||	 recall_15	[0.0193050]
ndcg_1	[0.0053857],	||	 ndcg_5	[0.0077959],	||	 ndcg_10	[0.0091035],	||	 ndcg_15	[0.0104214]
AUC per user type	[0.5046542]
AUC global is:  0.5057967897189002
Testing // Epoch 17 // Testing time : 68783 ms
========================================================================================================================================================================================================
Training // Epoch 18 //  Total cost = 66010.56207 Training time : 672 ms negative Sampling time : 11989 ms negative samples : 94840
precision_1	[0.0051014],	||	 precision_5	[0.0021714],	||	 precision_10	[0.0014781],	||	 precision_15	[0.0012470]
recall_1   	[0.0051014],	||	 recall_5   	[0.0108568],	||	 recall_10   	[0.0145716],	||	 recall_15   	[0.0184303]
f_measure_1	[0.0051014],	||	 f_measure_5	[0.0036189],	||	 f_measure_10	[0.0026839],	||	 f_measure_15	[0.0023360]
ndcg_1     	[0.0051014],	||	 ndcg_5     	[0.0080063],	||	 ndcg_10     	[0.0091824],	||	 ndcg_15     	[0.0101979]
Metrics for user type	 Female
precision_1	[0.0036795],	||	 precision_5	[0.0017989],	||	 precision_10	[0.0012674],	||	 precision_15	[0.0009812]
recall_1	[0.0036795],	||	 recall_5	[0.0089943],	||	 recall_10	[0.0120196],	||	 recall_15	[0.0140638]
ndcg_1	[0.0036795],	||	 ndcg_5	[0.0067440],	||	 ndcg_10	[0.0077335],	||	 ndcg_15	[0.0082774]
AUC per user type	[0.5058876]
Metrics for user type	 Male
precision_1	[0.0057703],	||	 precision_5	[0.0023466],	||	 precision_10	[0.0015772],	||	 precision_15	[0.0013721]
recall_1	[0.0057703],	||	 recall_5	[0.0117330],	||	 recall_10	[0.0157723],	||	 recall_15	[0.0204847]
ndcg_1	[0.0057703],	||	 ndcg_5	[0.0086001],	||	 ndcg_10	[0.0098641],	||	 ndcg_15	[0.0111015]
AUC per user type	[0.5029632]
AUC global is:  0.5038988730222084
Testing // Epoch 18 // Testing time : 64206 ms
========================================================================================================================================================================================================
Training // Epoch 19 //  Total cost = 65942.42021 Training time : 655 ms negative Sampling time : 11764 ms negative samples : 94840
precision_1	[0.0060170],	||	 precision_5	[0.0019882],	||	 precision_10	[0.0014650],	||	 precision_15	[0.0012993]
recall_1   	[0.0060170],	||	 recall_5   	[0.0098103],	||	 recall_10   	[0.0145193],	||	 recall_15   	[0.0192937]
f_measure_1	[0.0060170],	||	 f_measure_5	[0.0033064],	||	 f_measure_10	[0.0026615],	||	 f_measure_15	[0.0024347]
ndcg_1     	[0.0060170],	||	 ndcg_5     	[0.0079839],	||	 ndcg_10     	[0.0094680],	||	 ndcg_15     	[0.0107370]
Metrics for user type	 Female
precision_1	[0.0032706],	||	 precision_5	[0.0013900],	||	 precision_10	[0.0008994],	||	 precision_15	[0.0008449]
recall_1	[0.0032706],	||	 recall_5	[0.0067457],	||	 recall_10	[0.0087899],	||	 recall_15	[0.0124693]
ndcg_1	[0.0032706],	||	 ndcg_5	[0.0050537],	||	 ndcg_10	[0.0057200],	||	 ndcg_15	[0.0066968]
AUC per user type	[0.5008390]
Metrics for user type	 Male
precision_1	[0.0073091],	||	 precision_5	[0.0022697],	||	 precision_10	[0.0017311],	||	 precision_15	[0.0015131]
recall_1	[0.0073091],	||	 recall_5	[0.0112522],	||	 recall_10	[0.0172148],	||	 recall_15	[0.0225043]
ndcg_1	[0.0073091],	||	 ndcg_5	[0.0093625],	||	 ndcg_10	[0.0112313],	||	 ndcg_15	[0.0126379]
AUC per user type	[0.5093737]
AUC global is:  0.5066430414139659
Testing // Epoch 19 // Testing time : 65049 ms
========================================================================================================================================================================================================
Training // Epoch 20 //  Total cost = 66006.45820 Training time : 641 ms negative Sampling time : 12028 ms negative samples : 94840
precision_1	[0.0007848],	||	 precision_5	[0.0008371],	||	 precision_10	[0.0008371],	||	 precision_15	[0.0008197]
recall_1   	[0.0007194],	||	 recall_5   	[0.0039459],	||	 recall_10   	[0.0081317],	||	 recall_15   	[0.0120558]
f_measure_1	[0.0007507],	||	 f_measure_5	[0.0013813],	||	 f_measure_10	[0.0015180],	||	 f_measure_15	[0.0015350]
ndcg_1     	[0.0007848],	||	 ndcg_5     	[0.0022626],	||	 ndcg_10     	[0.0036147],	||	 ndcg_15     	[0.0046483]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0004088],	||	 precision_10	[0.0006541],	||	 precision_15	[0.0006814]
recall_1	[0.0000000],	||	 recall_5	[0.0020442],	||	 recall_10	[0.0065413],	||	 recall_15	[0.0102208]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0010545],	||	 ndcg_10	[0.0024867],	||	 ndcg_15	[0.0034651]
AUC per user type	[0.5059057]
Metrics for user type	 Male
precision_1	[0.0011541],	||	 precision_5	[0.0010387],	||	 precision_10	[0.0009233],	||	 precision_15	[0.0008848]
recall_1	[0.0010579],	||	 recall_5	[0.0048407],	||	 recall_10	[0.0088799],	||	 recall_15	[0.0129192]
ndcg_1	[0.0011541],	||	 ndcg_5	[0.0028309],	||	 ndcg_10	[0.0041454],	||	 ndcg_15	[0.0052049]
AUC per user type	[0.4965968]
AUC global is:  0.4995751679677168
Testing // Epoch 20 // Testing time : 65954 ms
========================================================================================================================================================================================================
precision_1	[0.0007848],	||	 precision_5	[0.0008371],	||	 precision_10	[0.0008371],	||	 precision_15	[0.0008197]
recall_1   	[0.0007194],	||	 recall_5   	[0.0039459],	||	 recall_10   	[0.0081317],	||	 recall_15   	[0.0120558]
f_measure_1	[0.0007507],	||	 f_measure_5	[0.0013813],	||	 f_measure_10	[0.0015180],	||	 f_measure_15	[0.0015350]
ndcg_1     	[0.0007848],	||	 ndcg_5     	[0.0022626],	||	 ndcg_10     	[0.0036147],	||	 ndcg_15     	[0.0046483]

In [31]:
list_recom_unfairbpr = []
list_recom_constiemfairadvbpr = []
list_recom_constiemfairadvbpr_bis = []
list_recom_constiemfairadvbpr_01 = []
list_recom_constiemfairadvbpr_02 = []
list_recom_constiemfairadvbpr_06 = []
list_recom_constiemfairadvbpr_07 = []
list_recom_constiemfairadvbpr_08 = []
list_recom_constiemfairadvbpr_09 = []
list_recom_constiemfairadvbpr_001 = []
list_recom_constiemfairadvbpr_0001 = []
list_recom_constiemfairadvbpr_00001 = []
list_recom_constiemfairadvbpr_000001 = []
list_recom_fairadvbpr = []
list_recom_iemfairadvbpr = []
list_recom_uemfairbpr = []

for itr in range(1, 20 + 1):
    filename = './unfairBPR_results/epoch'+ str(itr) +'_Rec_' + dataname + '_BPR.npy'
    with open(filename, "rb") as f:
        recom = np.load(f)
        list_recom_unfairbpr.append(recom)



for itr in range(1, 9 + 1):    
    filename2 = './fairAdvBPR_results/epoch'+ str(itr) +'_Rec_' + dataname + '_fairAdvBPR.npy'
    with open(filename2, "rb") as f:
        recom = np.load(f)
        list_recom_fairadvbpr.append(recom)
"""        
    filename3 = './IembfairAdvBPR_results/epoch'+ str(itr) +'_Rec_' + dataname + '_iembfairAdvBPR.npy'
    with open(filename3, "rb") as f:
        recom = np.load(f)
        list_recom_iemfairadvbpr.append(recom)
        
    filename4 = './UembfairAdvBPR_results/epoch'+ str(itr) +'_Rec_' + dataname + '_uembfairAdvBPR.npy'
    with open(filename4, "rb") as f:
        recom = np.load(f)
        list_recom_uemfairbpr.append(recom)

    filename5 = './const_IembfairAdvBPR_results_bis/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename5, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_bis.append(recom)

    filename6 = './const_IembfairAdvBPR_results_01/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename6, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_01.append(recom)
        
    filename7 = './const_IembfairAdvBPR_results_02/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename7, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_02.append(recom)
        
    filename8 = './const_IembfairAdvBPR_results_001/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename8, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_001.append(recom)
        
    filename9 = './const_IembfairAdvBPR_results_0001/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename9, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_0001.append(recom)
        
    filename10 = './const_IembfairAdvBPR_results_00001/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename10, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_00001.append(recom)
        
    filename11 = './const_IembfairAdvBPR_results_000001/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename11, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_000001.append(recom)
    

for itr in range(32, 51 + 1):
    filename1 = './const_IembfairAdvBPR_adv50_results_05/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename1, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr.append(recom) 
        
    filename2 = './const_IembfairAdvBPR_adv50_results_06/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename2, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_06.append(recom)    
        
    filename3 = './const_IembfairAdvBPR_adv50_results_07/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename3, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_07.append(recom)
        
    filename4 = './const_IembfairAdvBPR_adv50_results_08/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename4, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_08.append(recom)  
        
    filename5 = './const_IembfairAdvBPR_adv50_results_09/epoch'+ str(itr) +'_Rec_' + dataname + '_constfairAdvBPR.npy'
    with open(filename5, "rb") as f:
        recom = np.load(f)
        list_recom_constiemfairadvbpr_09.append(recom)    


"""

'        \n    filename3 = \'./IembfairAdvBPR_results/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_iembfairAdvBPR.npy\'\n    with open(filename3, "rb") as f:\n        recom = np.load(f)\n        list_recom_iemfairadvbpr.append(recom)\n        \n    filename4 = \'./UembfairAdvBPR_results/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_uembfairAdvBPR.npy\'\n    with open(filename4, "rb") as f:\n        recom = np.load(f)\n        list_recom_uemfairbpr.append(recom)\n\n    filename5 = \'./const_IembfairAdvBPR_results_bis/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename5, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_bis.append(recom)\n\n    filename6 = \'./const_IembfairAdvBPR_results_01/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename6, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_01.append(recom)\n        \n    filename7 = \'./const_IembfairAdvBPR_results_02/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename7, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_02.append(recom)\n        \n    filename8 = \'./const_IembfairAdvBPR_results_001/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename8, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_001.append(recom)\n        \n    filename9 = \'./const_IembfairAdvBPR_results_0001/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename9, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_0001.append(recom)\n        \n    filename10 = \'./const_IembfairAdvBPR_results_00001/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename10, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_00001.append(recom)\n        \n    filename11 = \'./const_IembfairAdvBPR_results_000001/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename11, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_000001.append(recom)\n    \n\nfor itr in range(32, 51 + 1):\n    filename1 = \'./const_IembfairAdvBPR_adv50_results_05/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename1, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr.append(recom) \n        \n    filename2 = \'./const_IembfairAdvBPR_adv50_results_06/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename2, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_06.append(recom)    \n        \n    filename3 = \'./const_IembfairAdvBPR_adv50_results_07/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename3, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_07.append(recom)\n        \n    filename4 = \'./const_IembfairAdvBPR_adv50_results_08/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename4, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_08.append(recom)  \n        \n    filename5 = \'./const_IembfairAdvBPR_adv50_results_09/epoch\'+ str(itr) +\'_Rec_\' + dataname + \'_constfairAdvBPR.npy\'\n    with open(filename5, "rb") as f:\n        recom = np.load(f)\n        list_recom_constiemfairadvbpr_09.append(recom)    \n\n\n'

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from colour import Color

def savepdf_barplot_color_gradient2(ymin = 0.5, ymax = 0.7, whis = 5, start_color='pink',end_color='blue',num_color=5, title='',axis_x = None, xlabel = '', axis_y1 = None, ylabel ='', plot_file = ''):
    
    fig = plt.figure()
    gs = fig.add_gridspec(1, 2, hspace=0, wspace=0)
    (ax1, ax2) = gs.subplots(sharex='col', sharey='row')
    
    red = Color(start_color)
    colors = list(red.range_to(Color(end_color), num_color))
    colors = [color.rgb for color in colors]
    
    X_axis = np.arange(len(axis_x))
    ax1.bar(X_axis, axis_y1, color=colors)
    ax1.hlines(y=axis_y1[0], xmin = 0, xmax = len(axis_x)-1, colors='black', linestyles='--', lw=1)
    
    plt.sca(ax1)
    plt.xticks(X_axis, axis_x, rotation =50)
    #plt.xlabel(xlabel)
    #fig.suptitle(title)
    plt.ylabel(ylabel, fontsize=18)
    plt.rcParams.update({'font.size': 13}) 
    plt.grid()
    
    plt.sca(ax2)
    ax2.boxplot(axis_y1, whis = whis)
    ax1.set_ylim(ymin, ymax)
    
    plt.tight_layout()
    plt.savefig(plot_file)

def savepdf_barplot_color_gradient(ymin = 0.5, ymax = 0.7, start_color='orange',end_color='yellow',num_color=3, title='',axis_x = None, xlabel = '', axis_y1 = None, axis_y2 = None, axis_y3 = None, ylabel ='',barwidth = 0.3, plot_file = '',legendy1 = '',legendy2 = '',legendy3 = ''):
    
    fig, ax1 = plt.subplots()
#     gs = fig.add_gridspec(1, 2, hspace=0, wspace=0)
#     (ax1, ax2) = gs.subplots(sharex='col', sharey='row')
    #fig.suptitle('Sharing x per column, y per row')
    
#     ax1.plot(x + 1, -y, 'tab:green')
#     ax2.plot(x + 2, -y**2, 'tab:red')

#     for ax in fig.get_axes():
#         ax.label_outer()
    
    red = Color(start_color)
    colors = list(red.range_to(Color(end_color), num_color))
    colors = [color.rgb for color in colors]
    
    X_axis = np.arange(len(axis_x))
    #ax1.bar(X_axis, axis_y1, color=colors)
    ax1.bar(2*X_axis - barwidth, axis_y1, width =barwidth, color=colors[num_color-num_color], label = legendy1)
    ax1.bar(2*X_axis + 0, axis_y2, width = barwidth, color=colors[num_color-2],label = legendy2)
    ax1.bar(2*X_axis + barwidth, axis_y3, width = barwidth, color=colors[num_color-1],label = legendy3)
    
    ax1.set_ylim(ymin, ymax)

    #plt.xlabel(xlabel, fontsize=22)
    plt.ylabel(ylabel, fontsize=18)
    #fig.suptitle(title)
    plt.grid()
    plt.legend(fontsize=12) 
    plt.rcParams.update({'font.size': 12})   
    #ax2 = ax1.twinx()
    #ax1.boxplot([[axis_y1[0],axis_y2[0],axis_y3[0]],[axis_y1[1],axis_y2[1],axis_y3[1]],[axis_y1[2],axis_y2[2],axis_y3[2]]], positions=[2*X_axis[0], 2*X_axis[1] , 2*X_axis[2] ])
    ax1.boxplot([[axis_y1[0],axis_y2[0],axis_y3[0]],[axis_y1[1],axis_y2[1],axis_y3[1]],[axis_y1[2],axis_y2[2],axis_y3[2]],[axis_y1[3],axis_y2[3],axis_y3[3]],[axis_y1[4],axis_y2[4],axis_y3[4]]], positions=[2*X_axis[0], 2*X_axis[1] , 2*X_axis[2], 2*X_axis[3], 2*X_axis[4]])
   
    #ax1.set_xticklabels(axis_x)
    plt.xticks(2*X_axis, axis_x)
    
    plt.tight_layout()
    plt.savefig(plot_file)
    
    
    
    
def savepdf_barplot_color_gradient3(ymin = 0.5, ymax = 0.7, title='',axis_x = None, xlabel = '', axis_y = None, ylabel ='',barwidth = 0.3, plot_file = ''):
    
    fig, ax1 = plt.subplots()
    
    X_axis = np.arange(len(axis_x))
    #ax1.bar(X_axis, axis_y1, color=colors)
    #ax1.bar(2*X_axis - barwidth, axis_y1, width =barwidth, color=colors[num_color-num_color], label = legendy1)
    ax1.bar(2*X_axis + 0, axis_y, width = barwidth, color='orange')
    #ax1.bar(2*X_axis + barwidth, axis_y3, width = barwidth, color=colors[num_color-1],label = legendy3)
    
    ax1.set_ylim(ymin, ymax)

    plt.ylabel(ylabel, fontsize=18)
    #fig.suptitle(title)
    plt.grid()
    plt.legend(fontsize=12) 
    plt.rcParams.update({'font.size': 12})   
    plt.xticks(2*X_axis, axis_x)
    
    plt.tight_layout()
    plt.savefig(plot_file)
    
def plotline_save_as_pdf(title='',axis_x = None, xlabel = '', axis_y1 = None, axis_y2 = None , axis_y3 = None, axis_y4 = None,axis_y5 = None, ylabel ='', linewidth=3, plot_file = '',legendy1='',legendy2='',legendy3='',legendy4='',legendy5=''):
    if axis_y1 is not None:
        plt.plot(axis_x, axis_y1, color='orange', linewidth = linewidth, label = legendy1)
    if axis_y2 is not None:
        plt.plot(axis_x, axis_y2, 'g', linewidth = linewidth, label = legendy2)
    if axis_y3 is not None:
        plt.plot(axis_x, axis_y3, 'b', linewidth = linewidth, label = legendy3)
    if axis_y4 is not None:
        plt.plot(axis_x, axis_y4, 'black', linewidth = linewidth, label = legendy4)
    if axis_y5 is not None:
        plt.plot(axis_x, axis_y5, 'red', linewidth = linewidth, label = legendy5)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.legend()
    plt.grid()

    plt.savefig(plot_file)

def plotline_save_as_pdf2(title='',axis_x1 = None,axis_x2 = None, xlabel = '', axis_y1 = None, axis_y2 = None , axis_y3 = None, axis_y4 = None,axis_y5 = None, ylabel ='', linewidth=3, plot_file = '',legendy1='',legendy2='',legendy3='',legendy4='',legendy5=''):
    if axis_y1 is not None:
        plt.plot(axis_x1, axis_y1, color='tab:orange', linewidth = linewidth, label = legendy1)
    if axis_y2 is not None:
        plt.plot(axis_x2, axis_y2, color='tab:green', linewidth = linewidth, label = legendy2)
    if axis_y3 is not None:
        plt.plot(axis_x2, axis_y3, color='tab:blue', linewidth = linewidth, label = legendy3)
    if axis_y4 is not None:
        plt.plot(axis_x2, axis_y4, color='tab:purple', linewidth = linewidth, label = legendy4)
    if axis_y5 is not None:
        plt.plot(axis_x2, axis_y5, color='tab:red', linewidth = linewidth, label = legendy5)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.legend()
    plt.grid()

    plt.savefig(plot_file)

In [ ]:
"""
auc_constiemfairadvbpr_01 = []
auc_constiemfairadvbpr_02 = []
auc_constiemfairadvbpr_06 = []
auc_constiemfairadvbpr_07 = []
auc_constiemfairadvbpr_08 = []
auc_constiemfairadvbpr_09 = []
auc_constiemfairadvbpr_001 = []
auc_constiemfairadvbpr_0001 = []
auc_constiemfairadvbpr_00001 = []
auc_constiemfairadvbpr_000001 = []

auc_per_type_constiemfairadvbpr_01 = []
auc_per_type_constiemfairadvbpr_02 = []
auc_per_type_constiemfairadvbpr_06 = []
auc_per_type_constiemfairadvbpr_07 = []
auc_per_type_constiemfairadvbpr_08 = []
auc_per_type_constiemfairadvbpr_09 = []
auc_per_type_constiemfairadvbpr_001 = []
auc_per_type_constiemfairadvbpr_0001 = []
auc_per_type_constiemfairadvbpr_00001 = []
auc_per_type_constiemfairadvbpr_000001 = []

for rec in list_recom_constiemfairadvbpr_01:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_01.append(auc)

    auc_per_type_constiemfairadvbpr_01.append(auc_per_user_type)
    
for rec in list_recom_constiemfairadvbpr_02:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_02.append(auc)

    auc_per_type_constiemfairadvbpr_02.append(auc_per_user_type)

for rec in list_recom_constiemfairadvbpr_001:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_001.append(auc)

    auc_per_type_constiemfairadvbpr_001.append(auc_per_user_type)
    
for rec in list_recom_constiemfairadvbpr_0001:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_0001.append(auc)

    auc_per_type_constiemfairadvbpr_0001.append(auc_per_user_type)

for rec in list_recom_constiemfairadvbpr_00001:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_00001.append(auc)

    auc_per_type_constiemfairadvbpr_00001.append(auc_per_user_type)

for rec in list_recom_constiemfairadvbpr_000001:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_000001.append(auc)

    auc_per_type_constiemfairadvbpr_000001.append(auc_per_user_type)

for rec in list_recom_constiemfairadvbpr_06:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_06.append(auc)

    auc_per_type_constiemfairadvbpr_06.append(auc_per_user_type)

for rec in list_recom_constiemfairadvbpr_07:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_07.append(auc)

    auc_per_type_constiemfairadvbpr_07.append(auc_per_user_type)

for rec in list_recom_constiemfairadvbpr_08:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_08.append(auc)

    auc_per_type_constiemfairadvbpr_08.append(auc_per_user_type)

for rec in list_recom_constiemfairadvbpr_09:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_constiemfairadvbpr_09.append(auc)

    auc_per_type_constiemfairadvbpr_09.append(auc_per_user_type)

"""

In [32]:
auc_plot_unfairbpr=[]
auc_plot_constiemfairbpr=[]
auc_plot_fairadvbpr=[]
auc_plot_iemfairadvbpr=[]
auc_plot_uemfairadvbpr=[]

precision_plot_unfairbpr=[]
precision_plot_constiemfairbpr=[]
precision_plot_fairadvbpr=[]
precision_plot_iemfairadvbpr=[]
precision_plot_uemfairadvbpr=[]

recall_plot_unfairbpr=[]
recall_plot_constiemfairbpr=[]
recall_plot_fairadvbpr=[]
recall_plot_iemfairadvbpr=[]
recall_plot_uemfairadvbpr=[]

ndcg_plot_unfairbpr=[]
ndcg_plot_constiemfairbpr=[]
ndcg_plot_fairadvbpr=[]
ndcg_plot_iemfairadvbpr=[]
ndcg_plot_uemfairadvbpr=[]

precision_perUserType_plot_unfairbpr=[]
precision_perUserType_plot_constiemfairbpr=[]
precision_perUserType_plot_fairadvbpr=[]
precision_perUserType_plot_iemfairadvbpr=[]
precision_perUserType_plot_uemfairadvbpr=[]

recall_perUserType_plot_unfairbpr=[]
recall_perUserType_plot_constiemfairbpr=[]
recall_perUserType_plot_fairadvbpr=[]
recall_perUserType_plot_iemfairadvbpr=[]
recall_perUserType_plot_uemfairadvbpr=[]

ndcg_perUserType_plot_unfairbpr=[]
ndcg_perUserType_plot_constiemfairbpr=[]
ndcg_perUserType_plot_fairadvbpr=[]
ndcg_perUserType_plot_iemfairadvbpr=[]
ndcg_perUserType_plot_uemfairadvbpr=[]

auc_perUserType_plot_unfairbpr=[]
auc_perUserType_plot_constiemfairbpr=[]
auc_perUserType_plot_fairadvbpr=[]
auc_perUserType_plot_iemfairadvbpr=[]
auc_perUserType_plot_uemfairadvbpr=[]

for rec in list_recom_unfairbpr:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_plot_unfairbpr.append(auc)
    precision_plot_unfairbpr.append(precision)
    recall_plot_unfairbpr.append(recall)
    ndcg_plot_unfairbpr.append(ndcg)
    
    precision_perUserType_plot_unfairbpr.append(precision_per_user_type)
    recall_perUserType_plot_unfairbpr.append(recall_per_user_type)
    ndcg_perUserType_plot_unfairbpr.append(ndcg_per_user_type)
    auc_perUserType_plot_unfairbpr.append(auc_per_user_type)

    """"
for rec in list_recom_constiemfairadvbpr:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_plot_constiemfairbpr.append(auc)
    precision_plot_constiemfairbpr.append(precision)
    recall_plot_constiemfairbpr.append(recall)
    ndcg_plot_constiemfairbpr.append(ndcg)
    
    precision_perUserType_plot_constiemfairbpr.append(precision_per_user_type)
    recall_perUserType_plot_constiemfairbpr.append(recall_per_user_type)
    ndcg_perUserType_plot_constiemfairbpr.append(ndcg_per_user_type)
    auc_perUserType_plot_constiemfairbpr.append(auc_per_user_type)
"""
    
for rec in list_recom_fairadvbpr:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_plot_fairadvbpr.append(auc)
    precision_plot_fairadvbpr.append(precision)
    recall_plot_fairadvbpr.append(recall)
    ndcg_plot_fairadvbpr.append(ndcg)
    
    precision_perUserType_plot_fairadvbpr.append(precision_per_user_type)
    recall_perUserType_plot_fairadvbpr.append(recall_per_user_type)
    ndcg_perUserType_plot_fairadvbpr.append(ndcg_per_user_type)
    auc_perUserType_plot_fairadvbpr.append(auc_per_user_type)
    
""""
for rec in list_recom_iemfairadvbpr:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_plot_iemfairadvbpr.append(auc)
    precision_plot_iemfairadvbpr.append(precision)
    recall_plot_iemfairadvbpr.append(recall)
    ndcg_plot_iemfairadvbpr.append(ndcg)
    
    precision_perUserType_plot_iemfairadvbpr.append(precision_per_user_type)
    recall_perUserType_plot_iemfairadvbpr.append(recall_per_user_type)
    ndcg_perUserType_plot_iemfairadvbpr.append(ndcg_per_user_type)
    auc_perUserType_plot_iemfairadvbpr.append(auc_per_user_type)

"""

# for rec in list_recom_uemfairbpr:
#     [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

#     [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
#     auc = utility.auc_per_user(rec, test_df, train_df)
#     auc_plot_uemfairadvbpr.append(auc)
#     precision_plot_uemfairadvbpr.append(precision)
#     recall_plot_uemfairadvbpr.append(recall)
#     ndcg_plot_uemfairadvbpr.append(ndcg)
    
#     precision_perUserType_plot_uemfairadvbpr.append(precision_per_user_type)
#     recall_perUserType_plot_uemfairadvbpr.append(recall_per_user_type)
#     ndcg_perUserType_plot_uemfairadvbpr.append(ndcg_per_user_type)
#     auc_perUserType_plot_uemfairadvbpr.append(auc_per_user_type)

""""
for rec in list_recom_uemfairbpr:
    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)

    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)
    auc = utility.auc_per_user(rec, test_df, train_df)
    auc_plot_uemfairadvbpr.append(auc)
    precision_plot_uemfairadvbpr.append(precision)
    recall_plot_uemfairadvbpr.append(recall)
    ndcg_plot_uemfairadvbpr.append(ndcg)
    
    precision_perUserType_plot_uemfairadvbpr.append(precision_per_user_type)
    recall_perUserType_plot_uemfairadvbpr.append(recall_per_user_type)
    ndcg_perUserType_plot_uemfairadvbpr.append(ndcg_per_user_type)
    auc_perUserType_plot_uemfairadvbpr.append(auc_per_user_type)
    
"""

precision_1	[0.0015697],	||	 precision_5	[0.0013865],	||	 precision_10	[0.0012034],	||	 precision_15	[0.0011162]
recall_1   	[0.0015697],	||	 recall_5   	[0.0068454],	||	 recall_10   	[0.0118814],	||	 recall_15   	[0.0165250]
f_measure_1	[0.0015697],	||	 f_measure_5	[0.0023060],	||	 f_measure_10	[0.0021854],	||	 f_measure_15	[0.0020911]
ndcg_1     	[0.0015697],	||	 ndcg_5     	[0.0042381],	||	 ndcg_10     	[0.0058536],	||	 ndcg_15     	[0.0070846]
Metrics for user type	 Female
precision_1	[0.0016353],	||	 precision_5	[0.0011447],	||	 precision_10	[0.0011447],	||	 precision_15	[0.0008994]
recall_1	[0.0016353],	||	 recall_5	[0.0057236],	||	 recall_10	[0.0114473],	||	 recall_15	[0.0134914]
ndcg_1	[0.0016353],	||	 ndcg_5	[0.0033915],	||	 ndcg_10	[0.0052582],	||	 ndcg_15	[0.0058052]
AUC per user type	[0.4953815]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0015003],	||	 precision_10	[0.0012310],	||	 precision_15	[0.0012182]
recall_1	[0.0015388],	||	 recall_5	[0.0073732],	||	 recall_10	[0.0120857],	||	 recall_15	[0.0179522]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0046365],	||	 ndcg_10	[0.0061338],	||	 ndcg_15	[0.0076866]
AUC per user type	[0.5022030]
precision_1	[0.0013080],	||	 precision_5	[0.0011511],	||	 precision_10	[0.0010988],	||	 precision_15	[0.0010377]
recall_1   	[0.0013080],	||	 recall_5   	[0.0057554],	||	 recall_10   	[0.0109876],	||	 recall_15   	[0.0152256]
f_measure_1	[0.0013080],	||	 f_measure_5	[0.0019185],	||	 f_measure_10	[0.0019977],	||	 f_measure_15	[0.0019430]
ndcg_1     	[0.0013080],	||	 ndcg_5     	[0.0034882],	||	 ndcg_10     	[0.0051408],	||	 ndcg_15     	[0.0062789]
Metrics for user type	 Female
precision_1	[0.0008177],	||	 precision_5	[0.0009812],	||	 precision_10	[0.0010221],	||	 precision_15	[0.0011447]
recall_1	[0.0008177],	||	 recall_5	[0.0049060],	||	 recall_10	[0.0102208],	||	 recall_15	[0.0163123]
ndcg_1	[0.0008177],	||	 ndcg_5	[0.0028555],	||	 ndcg_10	[0.0045324],	||	 ndcg_15	[0.0061962]
AUC per user type	[0.5020743]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0012310],	||	 precision_10	[0.0011348],	||	 precision_15	[0.0009874]
recall_1	[0.0015388],	||	 recall_5	[0.0061550],	||	 recall_10	[0.0113483],	||	 recall_15	[0.0147144]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0037859],	||	 ndcg_10	[0.0054270],	||	 ndcg_15	[0.0063178]
AUC per user type	[0.4928358]
precision_1	[0.0018313],	||	 precision_5	[0.0013080],	||	 precision_10	[0.0011380],	||	 precision_15	[0.0011424]
recall_1   	[0.0018313],	||	 recall_5   	[0.0063876],	||	 recall_10   	[0.0112274],	||	 recall_15   	[0.0169828]
f_measure_1	[0.0018313],	||	 f_measure_5	[0.0021714],	||	 f_measure_10	[0.0020665],	||	 f_measure_15	[0.0021407]
ndcg_1     	[0.0018313],	||	 ndcg_5     	[0.0040946],	||	 ndcg_10     	[0.0056275],	||	 ndcg_15     	[0.0071632]
Metrics for user type	 Female
precision_1	[0.0024530],	||	 precision_5	[0.0010630],	||	 precision_10	[0.0009812],	||	 precision_15	[0.0009267]
recall_1	[0.0024530],	||	 recall_5	[0.0053148],	||	 recall_10	[0.0098119],	||	 recall_15	[0.0139002]
ndcg_1	[0.0024530],	||	 ndcg_5	[0.0040697],	||	 ndcg_10	[0.0054656],	||	 ndcg_15	[0.0065368]
AUC per user type	[0.4898550]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0014234],	||	 precision_10	[0.0012118],	||	 precision_15	[0.0012438]
recall_1	[0.0015388],	||	 recall_5	[0.0068924],	||	 recall_10	[0.0118933],	||	 recall_15	[0.0184330]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0041063],	||	 ndcg_10	[0.0057037],	||	 ndcg_15	[0.0074579]
AUC per user type	[0.4979096]
precision_1	[0.0057554],	||	 precision_5	[0.0020405],	||	 precision_10	[0.0016351],	||	 precision_15	[0.0013429]
recall_1   	[0.0057554],	||	 recall_5   	[0.0102027],	||	 recall_10   	[0.0162634],	||	 recall_15   	[0.0198605]
f_measure_1	[0.0057554],	||	 f_measure_5	[0.0034009],	||	 f_measure_10	[0.0029714],	||	 f_measure_15	[0.0025157]
ndcg_1     	[0.0057554],	||	 ndcg_5     	[0.0078774],	||	 ndcg_10     	[0.0098733],	||	 ndcg_15     	[0.0108278]
Metrics for user type	 Female
precision_1	[0.0057236],	||	 precision_5	[0.0022895],	||	 precision_10	[0.0017171],	||	 precision_15	[0.0013628]
recall_1	[0.0057236],	||	 recall_5	[0.0114473],	||	 recall_10	[0.0168983],	||	 recall_15	[0.0198624]
ndcg_1	[0.0057236],	||	 ndcg_5	[0.0085474],	||	 ndcg_10	[0.0103490],	||	 ndcg_15	[0.0111459]
AUC per user type	[0.5090065]
Metrics for user type	 Male
precision_1	[0.0057703],	||	 precision_5	[0.0019234],	||	 precision_10	[0.0015965],	||	 precision_15	[0.0013336]
recall_1	[0.0057703],	||	 recall_5	[0.0096172],	||	 recall_10	[0.0159646],	||	 recall_15	[0.0198596]
ndcg_1	[0.0057703],	||	 ndcg_5	[0.0075622],	||	 ndcg_10	[0.0096495],	||	 ndcg_15	[0.0106781]
AUC per user type	[0.4954945]
precision_1	[0.0009156],	||	 precision_5	[0.0012296],	||	 precision_10	[0.0011249],	||	 precision_15	[0.0010377]
recall_1   	[0.0009156],	||	 recall_5   	[0.0061478],	||	 recall_10   	[0.0112492],	||	 recall_15   	[0.0155657]
f_measure_1	[0.0009156],	||	 f_measure_5	[0.0020493],	||	 f_measure_10	[0.0020453],	||	 f_measure_15	[0.0019457]
ndcg_1     	[0.0009156],	||	 ndcg_5     	[0.0034415],	||	 ndcg_10     	[0.0050618],	||	 ndcg_15     	[0.0061977]
Metrics for user type	 Female
precision_1	[0.0012265],	||	 precision_5	[0.0007359],	||	 precision_10	[0.0006541],	||	 precision_15	[0.0007359]
recall_1	[0.0012265],	||	 recall_5	[0.0036795],	||	 recall_10	[0.0065413],	||	 recall_15	[0.0110384]
ndcg_1	[0.0012265],	||	 ndcg_5	[0.0023857],	||	 ndcg_10	[0.0032717],	||	 ndcg_15	[0.0044563]
AUC per user type	[0.4939380]
Metrics for user type	 Male
precision_1	[0.0007694],	||	 precision_5	[0.0014618],	||	 precision_10	[0.0013464],	||	 precision_15	[0.0011797]
recall_1	[0.0007694],	||	 recall_5	[0.0073091],	||	 recall_10	[0.0134641],	||	 recall_15	[0.0176957]
ndcg_1	[0.0007694],	||	 ndcg_5	[0.0039383],	||	 ndcg_10	[0.0059040],	||	 ndcg_15	[0.0070170]
AUC per user type	[0.5028843]
precision_1	[0.0013080],	||	 precision_5	[0.0014127],	||	 precision_10	[0.0011903],	||	 precision_15	[0.0011598]
recall_1   	[0.0012034],	||	 recall_5   	[0.0068542],	||	 recall_10   	[0.0116939],	||	 recall_15   	[0.0171223]
f_measure_1	[0.0012535],	||	 f_measure_5	[0.0023426],	||	 f_measure_10	[0.0021607],	||	 f_measure_15	[0.0021724]
ndcg_1     	[0.0013080],	||	 ndcg_5     	[0.0039803],	||	 ndcg_10     	[0.0055213],	||	 ndcg_15     	[0.0069493]
Metrics for user type	 Female
precision_1	[0.0012265],	||	 precision_5	[0.0017989],	||	 precision_10	[0.0013900],	||	 precision_15	[0.0012265]
recall_1	[0.0008994],	||	 recall_5	[0.0083401],	||	 recall_10	[0.0132461],	||	 recall_15	[0.0177433]
ndcg_1	[0.0012265],	||	 ndcg_5	[0.0046977],	||	 ndcg_10	[0.0062123],	||	 ndcg_15	[0.0073886]
AUC per user type	[0.5105137]
Metrics for user type	 Male
precision_1	[0.0013464],	||	 precision_5	[0.0012310],	||	 precision_10	[0.0010964],	||	 precision_15	[0.0011284]
recall_1	[0.0013464],	||	 recall_5	[0.0061550],	||	 recall_10	[0.0109636],	||	 recall_15	[0.0168302]
ndcg_1	[0.0013464],	||	 ndcg_5	[0.0036428],	||	 ndcg_10	[0.0051961],	||	 ndcg_15	[0.0067426]
AUC per user type	[0.4993808]
precision_1	[0.0014388],	||	 precision_5	[0.0008633],	||	 precision_10	[0.0008110],	||	 precision_15	[0.0008546]
recall_1   	[0.0014388],	||	 recall_5   	[0.0043165],	||	 recall_10   	[0.0080009],	||	 recall_15   	[0.0126226]
f_measure_1	[0.0014388],	||	 f_measure_5	[0.0014388],	||	 f_measure_10	[0.0014727],	||	 f_measure_15	[0.0016008]
ndcg_1     	[0.0014388],	||	 ndcg_5     	[0.0028610],	||	 ndcg_10     	[0.0040498],	||	 ndcg_15     	[0.0052809]
Metrics for user type	 Female
precision_1	[0.0012265],	||	 precision_5	[0.0010630],	||	 precision_10	[0.0007768],	||	 precision_15	[0.0009267]
recall_1	[0.0012265],	||	 recall_5	[0.0053148],	||	 recall_10	[0.0077678],	||	 recall_15	[0.0136277]
ndcg_1	[0.0012265],	||	 ndcg_5	[0.0031464],	||	 ndcg_10	[0.0039050],	||	 ndcg_15	[0.0054668]
AUC per user type	[0.4978742]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0007694],	||	 precision_10	[0.0008271],	||	 precision_15	[0.0008207]
recall_1	[0.0015388],	||	 recall_5	[0.0038469],	||	 recall_10	[0.0081105],	||	 recall_15	[0.0121498]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0027268],	||	 ndcg_10	[0.0041180],	||	 ndcg_15	[0.0051935]
AUC per user type	[0.4923608]

precision_1	[0.0049706],	||	 precision_5	[0.0016481],	||	 precision_10	[0.0013996],	||	 precision_15	[0.0012296]
recall_1   	[0.0049706],	||	 recall_5   	[0.0080488],	||	 recall_10   	[0.0137170],	||	 recall_15   	[0.0180118]
f_measure_1	[0.0049706],	||	 f_measure_5	[0.0027360],	||	 f_measure_10	[0.0025400],	||	 f_measure_15	[0.0023020]
ndcg_1     	[0.0049706],	||	 ndcg_5     	[0.0065387],	||	 ndcg_10     	[0.0083586],	||	 ndcg_15     	[0.0095099]
Metrics for user type	 Female
precision_1	[0.0044971],	||	 precision_5	[0.0015536],	||	 precision_10	[0.0013083],	||	 precision_15	[0.0011992]
recall_1	[0.0044971],	||	 recall_5	[0.0074952],	||	 recall_10	[0.0125375],	||	 recall_15	[0.0171709]
ndcg_1	[0.0044971],	||	 ndcg_5	[0.0060599],	||	 ndcg_10	[0.0076850],	||	 ndcg_15	[0.0089325]
AUC per user type	[0.5018829]
Metrics for user type	 Male
precision_1	[0.0051933],	||	 precision_5	[0.0016926],	||	 precision_10	[0.0014426],	||	 precision_15	[0.0012438]
recall_1	[0.0051933],	||	 recall_5	[0.0083093],	||	 recall_10	[0.0142720],	||	 recall_15	[0.0184074]
ndcg_1	[0.0051933],	||	 ndcg_5	[0.0067640],	||	 ndcg_10	[0.0086754],	||	 ndcg_15	[0.0097815]
AUC per user type	[0.4966155]
precision_1	[0.0010464],	||	 precision_5	[0.0009418],	||	 precision_10	[0.0009680],	||	 precision_15	[0.0009244]
recall_1   	[0.0010464],	||	 recall_5   	[0.0046436],	||	 recall_10   	[0.0095487],	||	 recall_15   	[0.0135383]
f_measure_1	[0.0010464],	||	 f_measure_5	[0.0015660],	||	 f_measure_10	[0.0017577],	||	 f_measure_15	[0.0017305]
ndcg_1     	[0.0010464],	||	 ndcg_5     	[0.0028705],	||	 ndcg_10     	[0.0044570],	||	 ndcg_15     	[0.0055340]
Metrics for user type	 Female
precision_1	[0.0004088],	||	 precision_5	[0.0005724],	||	 precision_10	[0.0006541],	||	 precision_15	[0.0007359]
recall_1	[0.0004088],	||	 recall_5	[0.0026574],	||	 recall_10	[0.0063369],	||	 recall_15	[0.0106296]
ndcg_1	[0.0004088],	||	 ndcg_5	[0.0015397],	||	 ndcg_10	[0.0027345],	||	 ndcg_15	[0.0038853]
AUC per user type	[0.5054003]
Metrics for user type	 Male
precision_1	[0.0013464],	||	 precision_5	[0.0011156],	||	 precision_10	[0.0011156],	||	 precision_15	[0.0010130]
recall_1	[0.0013464],	||	 recall_5	[0.0055780],	||	 recall_10	[0.0110598],	||	 recall_15	[0.0149067]
ndcg_1	[0.0013464],	||	 ndcg_5	[0.0034966],	||	 ndcg_10	[0.0052674],	||	 ndcg_15	[0.0063097]
AUC per user type	[0.5040692]
precision_1	[0.0006540],	||	 precision_5	[0.0011249],	||	 precision_10	[0.0011903],	||	 precision_15	[0.0011336]
recall_1   	[0.0006540],	||	 recall_5   	[0.0056246],	||	 recall_10   	[0.0118378],	||	 recall_15   	[0.0169392]
f_measure_1	[0.0006540],	||	 f_measure_5	[0.0018749],	||	 f_measure_10	[0.0021631],	||	 f_measure_15	[0.0021251]
ndcg_1     	[0.0006540],	||	 ndcg_5     	[0.0032658],	||	 ndcg_10     	[0.0052166],	||	 ndcg_15     	[0.0065583]
Metrics for user type	 Female
precision_1	[0.0008177],	||	 precision_5	[0.0011447],	||	 precision_10	[0.0011447],	||	 precision_15	[0.0009812]
recall_1	[0.0008177],	||	 recall_5	[0.0057236],	||	 recall_10	[0.0114473],	||	 recall_15	[0.0147179]
ndcg_1	[0.0008177],	||	 ndcg_5	[0.0033251],	||	 ndcg_10	[0.0051129],	||	 ndcg_15	[0.0059745]
AUC per user type	[0.5036323]
Metrics for user type	 Male
precision_1	[0.0005770],	||	 precision_5	[0.0011156],	||	 precision_10	[0.0012118],	||	 precision_15	[0.0012054]
recall_1	[0.0005770],	||	 recall_5	[0.0055780],	||	 recall_10	[0.0120215],	||	 recall_15	[0.0179842]
ndcg_1	[0.0005770],	||	 ndcg_5	[0.0032378],	||	 ndcg_10	[0.0052654],	||	 ndcg_15	[0.0068330]
AUC per user type	[0.4985237]
precision_1	[0.0054938],	||	 precision_5	[0.0021714],	||	 precision_10	[0.0018051],	||	 precision_15	[0.0015348]
recall_1   	[0.0054284],	||	 recall_5   	[0.0107914],	||	 recall_10   	[0.0179856],	||	 recall_15   	[0.0228908]
f_measure_1	[0.0054609],	||	 f_measure_5	[0.0036153],	||	 f_measure_10	[0.0032809],	||	 f_measure_15	[0.0028767]
ndcg_1     	[0.0054938],	||	 ndcg_5     	[0.0082477],	||	 ndcg_10     	[0.0105527],	||	 ndcg_15     	[0.0118452]
Metrics for user type	 Female
precision_1	[0.0040883],	||	 precision_5	[0.0017989],	||	 precision_10	[0.0014718],	||	 precision_15	[0.0013355]
recall_1	[0.0038839],	||	 recall_5	[0.0087899],	||	 recall_10	[0.0145135],	||	 recall_15	[0.0198283]
ndcg_1	[0.0040883],	||	 ndcg_5	[0.0064660],	||	 ndcg_10	[0.0083261],	||	 ndcg_15	[0.0097289]
AUC per user type	[0.5031700]
Metrics for user type	 Male
precision_1	[0.0061550],	||	 precision_5	[0.0023466],	||	 precision_10	[0.0019619],	||	 precision_15	[0.0016285]
recall_1	[0.0061550],	||	 recall_5	[0.0117330],	||	 recall_10	[0.0196192],	||	 recall_15	[0.0243316]
ndcg_1	[0.0061550],	||	 ndcg_5	[0.0090860],	||	 ndcg_10	[0.0116002],	||	 ndcg_15	[0.0128410]
AUC per user type	[0.5032750]
precision_1	[0.0011772],	||	 precision_5	[0.0008895],	||	 precision_10	[0.0008633],	||	 precision_15	[0.0008720]
recall_1   	[0.0011772],	||	 recall_5   	[0.0043427],	||	 recall_10   	[0.0084238],	||	 recall_15   	[0.0124504]
f_measure_1	[0.0011772],	||	 f_measure_5	[0.0014765],	||	 f_measure_10	[0.0015661],	||	 f_measure_15	[0.0016299]
ndcg_1     	[0.0011772],	||	 ndcg_5     	[0.0028851],	||	 ndcg_10     	[0.0041728],	||	 ndcg_15     	[0.0052526]
Metrics for user type	 Female
precision_1	[0.0004088],	||	 precision_5	[0.0010630],	||	 precision_10	[0.0008994],	||	 precision_15	[0.0008994]
recall_1	[0.0004088],	||	 recall_5	[0.0049877],	||	 recall_10	[0.0083401],	||	 recall_15	[0.0128373]
ndcg_1	[0.0004088],	||	 ndcg_5	[0.0026360],	||	 ndcg_10	[0.0036987],	||	 ndcg_15	[0.0048836]
AUC per user type	[0.4958510]
Metrics for user type	 Male
precision_1	[0.0015388],	||	 precision_5	[0.0008078],	||	 precision_10	[0.0008463],	||	 precision_15	[0.0008591]
recall_1	[0.0015388],	||	 recall_5	[0.0040392],	||	 recall_10	[0.0084632],	||	 recall_15	[0.0122684]
ndcg_1	[0.0015388],	||	 ndcg_5	[0.0030023],	||	 ndcg_10	[0.0043959],	||	 ndcg_15	[0.0054262]
AUC per user type	[0.5004565]
precision_1	[0.0015697],	||	 precision_5	[0.0010464],	||	 precision_10	[0.0008764],	||	 precision_15	[0.0008982]
recall_1   	[0.0015697],	||	 recall_5   	[0.0052322],	||	 recall_10   	[0.0087639],	||	 recall_15   	[0.0132985]
f_measure_1	[0.0015697],	||	 f_measure_5	[0.0017441],	||	 f_measure_10	[0.0015934],	||	 f_measure_15	[0.0016827]
ndcg_1     	[0.0015697],	||	 ndcg_5     	[0.0033719],	||	 ndcg_10     	[0.0045138],	||	 ndcg_15     	[0.0057250]
Metrics for user type	 Female
precision_1	[0.0012265],	||	 precision_5	[0.0009812],	||	 precision_10	[0.0007359],	||	 precision_15	[0.0007904]
recall_1	[0.0012265],	||	 recall_5	[0.0049060],	||	 recall_10	[0.0073590],	||	 recall_15	[0.0118561]
ndcg_1	[0.0012265],	||	 ndcg_5	[0.0029422],	||	 ndcg_10	[0.0037174],	||	 ndcg_15	[0.0049038]
AUC per user type	[0.5005133]
Metrics for user type	 Male
precision_1	[0.0017311],	||	 precision_5	[0.0010771],	||	 precision_10	[0.0009425],	||	 precision_15	[0.0009489]
recall_1	[0.0017311],	||	 recall_5	[0.0053857],	||	 recall_10	[0.0094249],	||	 recall_15	[0.0139770]
ndcg_1	[0.0017311],	||	 ndcg_5	[0.0035741],	||	 ndcg_10	[0.0048885],	||	 ndcg_15	[0.0061114]
AUC per user type	[0.4997276]
precision_1	[0.0009156],	||	 precision_5	[0.0012557],	||	 precision_10	[0.0010203],	||	 precision_15	[0.0009505]
recall_1   	[0.0009156],	||	 recall_5   	[0.0062132],	||	 recall_10   	[0.0099847],	||	 recall_15   	[0.0140397]
f_measure_1	[0.0009156],	||	 f_measure_5	[0.0020892],	||	 f_measure_10	[0.0018514],	||	 f_measure_15	[0.0017805]
ndcg_1     	[0.0009156],	||	 ndcg_5     	[0.0035934],	||	 ndcg_10     	[0.0048325],	||	 ndcg_15     	[0.0059018]
Metrics for user type	 Female
precision_1	[0.0004088],	||	 precision_5	[0.0012265],	||	 precision_10	[0.0008585],	||	 precision_15	[0.0008994]
recall_1	[0.0004088],	||	 recall_5	[0.0059280],	||	 recall_10	[0.0081085],	||	 recall_15	[0.0130144]
ndcg_1	[0.0004088],	||	 ndcg_5	[0.0033427],	||	 ndcg_10	[0.0041088],	||	 ndcg_15	[0.0054064]
AUC per user type	[0.5011090]
Metrics for user type	 Male
precision_1	[0.0011541],	||	 precision_5	[0.0012695],	||	 precision_10	[0.0010964],	||	 precision_15	[0.0009745]
recall_1	[0.0011541],	||	 recall_5	[0.0063474],	||	 recall_10	[0.0108675],	||	 recall_15	[0.0145220]
ndcg_1	[0.0011541],	||	 ndcg_5	[0.0037114],	||	 ndcg_10	[0.0051731],	||	 ndcg_15	[0.0061348]
AUC per user type	[0.4960079]

precision_1	[0.0037933],	||	 precision_5	[0.0020144],	||	 precision_10	[0.0013865],	||	 precision_15	[0.0012383]
recall_1   	[0.0037933],	||	 recall_5   	[0.0100065],	||	 recall_10   	[0.0137999],	||	 recall_15   	[0.0185088]
f_measure_1	[0.0037933],	||	 f_measure_5	[0.0033537],	||	 f_measure_10	[0.0025199],	||	 f_measure_15	[0.0023213]
ndcg_1     	[0.0037933],	||	 ndcg_5     	[0.0069041],	||	 ndcg_10     	[0.0081005],	||	 ndcg_15     	[0.0093315]
Metrics for user type	 Female
precision_1	[0.0028618],	||	 precision_5	[0.0016353],	||	 precision_10	[0.0011856],	||	 precision_15	[0.0009812]
recall_1	[0.0028618],	||	 recall_5	[0.0081766],	||	 recall_10	[0.0118561],	||	 recall_15	[0.0147179]
ndcg_1	[0.0028618],	||	 ndcg_5	[0.0055202],	||	 ndcg_10	[0.0066583],	||	 ndcg_15	[0.0073956]
AUC per user type	[0.5022372]
Metrics for user type	 Male
precision_1	[0.0042316],	||	 precision_5	[0.0021927],	||	 precision_10	[0.0014811],	||	 precision_15	[0.0013592]
recall_1	[0.0042316],	||	 recall_5	[0.0108675],	||	 recall_10	[0.0147144],	||	 recall_15	[0.0202924]
ndcg_1	[0.0042316],	||	 ndcg_5	[0.0075553],	||	 ndcg_10	[0.0087791],	||	 ndcg_15	[0.0102423]
AUC per user type	[0.4989111]
precision_1	[0.0056246],	||	 precision_5	[0.0021714],	||	 precision_10	[0.0016220],	||	 precision_15	[0.0012993]
recall_1   	[0.0056246],	||	 recall_5   	[0.0107914],	||	 recall_10   	[0.0160562],	||	 recall_15   	[0.0193264]
f_measure_1	[0.0056246],	||	 f_measure_5	[0.0036153],	||	 f_measure_10	[0.0029463],	||	 f_measure_15	[0.0024349]
ndcg_1     	[0.0056246],	||	 ndcg_5     	[0.0082768],	||	 ndcg_10     	[0.0099902],	||	 ndcg_15     	[0.0108528]
Metrics for user type	 Female
precision_1	[0.0040883],	||	 precision_5	[0.0022895],	||	 precision_10	[0.0019624],	||	 precision_15	[0.0015263]
recall_1	[0.0040883],	||	 recall_5	[0.0114473],	||	 recall_10	[0.0193173],	||	 recall_15	[0.0225879]
ndcg_1	[0.0040883],	||	 ndcg_5	[0.0078579],	||	 ndcg_10	[0.0104683],	||	 ndcg_15	[0.0113351]
AUC per user type	[0.4981147]
Metrics for user type	 Male
precision_1	[0.0063474],	||	 precision_5	[0.0021158],	||	 precision_10	[0.0014618],	||	 precision_15	[0.0011925]
recall_1	[0.0063474],	||	 recall_5	[0.0104828],	||	 recall_10	[0.0145220],	||	 recall_15	[0.0177919]
ndcg_1	[0.0063474],	||	 ndcg_5	[0.0084739],	||	 ndcg_10	[0.0097652],	||	 ndcg_15	[0.0106259]
AUC per user type	[0.4887975]
precision_1	[0.0044474],	||	 precision_5	[0.0018313],	||	 precision_10	[0.0012688],	||	 precision_15	[0.0011424]
recall_1   	[0.0043427],	||	 recall_5   	[0.0089427],	||	 recall_10   	[0.0124744],	||	 recall_15   	[0.0169217]
f_measure_1	[0.0043944],	||	 f_measure_5	[0.0030400],	||	 f_measure_10	[0.0023033],	||	 f_measure_15	[0.0021402]
ndcg_1     	[0.0044474],	||	 ndcg_5     	[0.0066683],	||	 ndcg_10     	[0.0078040],	||	 ndcg_15     	[0.0089757]
Metrics for user type	 Female
precision_1	[0.0024530],	||	 precision_5	[0.0012265],	||	 precision_10	[0.0008585],	||	 precision_15	[0.0007904]
recall_1	[0.0024530],	||	 recall_5	[0.0061325],	||	 recall_10	[0.0085854],	||	 recall_15	[0.0118561]
ndcg_1	[0.0024530],	||	 ndcg_5	[0.0042717],	||	 ndcg_10	[0.0050420],	||	 ndcg_15	[0.0059027]
AUC per user type	[0.5082254]
Metrics for user type	 Male
precision_1	[0.0053857],	||	 precision_5	[0.0021158],	||	 precision_10	[0.0014618],	||	 precision_15	[0.0013079]
recall_1	[0.0052318],	||	 recall_5	[0.0102648],	||	 recall_10	[0.0143040],	||	 recall_15	[0.0193050]
ndcg_1	[0.0053857],	||	 ndcg_5	[0.0077959],	||	 ndcg_10	[0.0091035],	||	 ndcg_15	[0.0104214]
AUC per user type	[0.5046542]
precision_1	[0.0051014],	||	 precision_5	[0.0021714],	||	 precision_10	[0.0014781],	||	 precision_15	[0.0012470]
recall_1   	[0.0051014],	||	 recall_5   	[0.0108568],	||	 recall_10   	[0.0145716],	||	 recall_15   	[0.0184303]
f_measure_1	[0.0051014],	||	 f_measure_5	[0.0036189],	||	 f_measure_10	[0.0026839],	||	 f_measure_15	[0.0023360]
ndcg_1     	[0.0051014],	||	 ndcg_5     	[0.0080063],	||	 ndcg_10     	[0.0091824],	||	 ndcg_15     	[0.0101979]
Metrics for user type	 Female
precision_1	[0.0036795],	||	 precision_5	[0.0017989],	||	 precision_10	[0.0012674],	||	 precision_15	[0.0009812]
recall_1	[0.0036795],	||	 recall_5	[0.0089943],	||	 recall_10	[0.0120196],	||	 recall_15	[0.0140638]
ndcg_1	[0.0036795],	||	 ndcg_5	[0.0067440],	||	 ndcg_10	[0.0077335],	||	 ndcg_15	[0.0082774]
AUC per user type	[0.5058876]
Metrics for user type	 Male
precision_1	[0.0057703],	||	 precision_5	[0.0023466],	||	 precision_10	[0.0015772],	||	 precision_15	[0.0013721]
recall_1	[0.0057703],	||	 recall_5	[0.0117330],	||	 recall_10	[0.0157723],	||	 recall_15	[0.0204847]
ndcg_1	[0.0057703],	||	 ndcg_5	[0.0086001],	||	 ndcg_10	[0.0098641],	||	 ndcg_15	[0.0111015]
AUC per user type	[0.5029632]
precision_1	[0.0060170],	||	 precision_5	[0.0019882],	||	 precision_10	[0.0014650],	||	 precision_15	[0.0012993]
recall_1   	[0.0060170],	||	 recall_5   	[0.0098103],	||	 recall_10   	[0.0145193],	||	 recall_15   	[0.0192937]
f_measure_1	[0.0060170],	||	 f_measure_5	[0.0033064],	||	 f_measure_10	[0.0026615],	||	 f_measure_15	[0.0024347]
ndcg_1     	[0.0060170],	||	 ndcg_5     	[0.0079839],	||	 ndcg_10     	[0.0094680],	||	 ndcg_15     	[0.0107370]
Metrics for user type	 Female
precision_1	[0.0032706],	||	 precision_5	[0.0013900],	||	 precision_10	[0.0008994],	||	 precision_15	[0.0008449]
recall_1	[0.0032706],	||	 recall_5	[0.0067457],	||	 recall_10	[0.0087899],	||	 recall_15	[0.0124693]
ndcg_1	[0.0032706],	||	 ndcg_5	[0.0050537],	||	 ndcg_10	[0.0057200],	||	 ndcg_15	[0.0066968]
AUC per user type	[0.5008390]
Metrics for user type	 Male
precision_1	[0.0073091],	||	 precision_5	[0.0022697],	||	 precision_10	[0.0017311],	||	 precision_15	[0.0015131]
recall_1	[0.0073091],	||	 recall_5	[0.0112522],	||	 recall_10	[0.0172148],	||	 recall_15	[0.0225043]
ndcg_1	[0.0073091],	||	 ndcg_5	[0.0093625],	||	 ndcg_10	[0.0112313],	||	 ndcg_15	[0.0126379]
AUC per user type	[0.5093737]
precision_1	[0.0007848],	||	 precision_5	[0.0008371],	||	 precision_10	[0.0008371],	||	 precision_15	[0.0008197]
recall_1   	[0.0007194],	||	 recall_5   	[0.0039459],	||	 recall_10   	[0.0081317],	||	 recall_15   	[0.0120558]
f_measure_1	[0.0007507],	||	 f_measure_5	[0.0013813],	||	 f_measure_10	[0.0015180],	||	 f_measure_15	[0.0015350]
ndcg_1     	[0.0007848],	||	 ndcg_5     	[0.0022626],	||	 ndcg_10     	[0.0036147],	||	 ndcg_15     	[0.0046483]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0004088],	||	 precision_10	[0.0006541],	||	 precision_15	[0.0006814]
recall_1	[0.0000000],	||	 recall_5	[0.0020442],	||	 recall_10	[0.0065413],	||	 recall_15	[0.0102208]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0010545],	||	 ndcg_10	[0.0024867],	||	 ndcg_15	[0.0034651]
AUC per user type	[0.5059057]
Metrics for user type	 Male
precision_1	[0.0011541],	||	 precision_5	[0.0010387],	||	 precision_10	[0.0009233],	||	 precision_15	[0.0008848]
recall_1	[0.0010579],	||	 recall_5	[0.0048407],	||	 recall_10	[0.0088799],	||	 recall_15	[0.0129192]
ndcg_1	[0.0011541],	||	 ndcg_5	[0.0028309],	||	 ndcg_10	[0.0041454],	||	 ndcg_15	[0.0052049]
AUC per user type	[0.4965968]
precision_1	[0.0000000],	||	 precision_5	[0.0002354],	||	 precision_10	[0.0002747],	||	 precision_15	[0.0003052]
recall_1   	[0.0000000],	||	 recall_5   	[0.0011772],	||	 recall_10   	[0.0026597],	||	 recall_15   	[0.0044910]
f_measure_1	[0.0000000],	||	 f_measure_5	[0.0003924],	||	 f_measure_10	[0.0004980],	||	 f_measure_15	[0.0005716]
ndcg_1     	[0.0000000],	||	 ndcg_5     	[0.0005751],	||	 ndcg_10     	[0.0010642],	||	 ndcg_15     	[0.0015458]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0004088],	||	 precision_10	[0.0004497],	||	 precision_15	[0.0004088]
recall_1	[0.0000000],	||	 recall_5	[0.0020442],	||	 recall_10	[0.0044971],	||	 recall_15	[0.0061325]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0010473],	||	 ndcg_10	[0.0018298],	||	 ndcg_15	[0.0022670]
AUC per user type	[0.5113749]
Metrics for user type	 Male
precision_1	[0.0000000],	||	 precision_5	[0.0001539],	||	 precision_10	[0.0001923],	||	 precision_15	[0.0002565]
recall_1	[0.0000000],	||	 recall_5	[0.0007694],	||	 recall_10	[0.0017952],	||	 recall_15	[0.0037187]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0003530],	||	 ndcg_10	[0.0007040],	||	 ndcg_15	[0.0012064]
AUC per user type	[0.5010365]

precision_1	[0.0000000],	||	 precision_5	[0.0002093],	||	 precision_10	[0.0002616],	||	 precision_15	[0.0002703]
recall_1   	[0.0000000],	||	 recall_5   	[0.0010464],	||	 recall_10   	[0.0026161],	||	 recall_15   	[0.0039677]
f_measure_1	[0.0000000],	||	 f_measure_5	[0.0003488],	||	 f_measure_10	[0.0004757],	||	 f_measure_15	[0.0005062]
ndcg_1     	[0.0000000],	||	 ndcg_5     	[0.0005359],	||	 ndcg_10     	[0.0010237],	||	 ndcg_15     	[0.0013821]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0004088],	||	 precision_10	[0.0004906],	||	 precision_15	[0.0004088]
recall_1	[0.0000000],	||	 recall_5	[0.0020442],	||	 recall_10	[0.0049060],	||	 recall_15	[0.0061325]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0010545],	||	 ndcg_10	[0.0019483],	||	 ndcg_15	[0.0022739]
AUC per user type	[0.5097215]
Metrics for user type	 Male
precision_1	[0.0000000],	||	 precision_5	[0.0001154],	||	 precision_10	[0.0001539],	||	 precision_15	[0.0002052]
recall_1	[0.0000000],	||	 recall_5	[0.0005770],	||	 recall_10	[0.0015388],	||	 recall_15	[0.0029493]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0002919],	||	 ndcg_10	[0.0005886],	||	 ndcg_15	[0.0009625]
AUC per user type	[0.5009428]
precision_1	[0.0001308],	||	 precision_5	[0.0002093],	||	 precision_10	[0.0002616],	||	 precision_15	[0.0002180]
recall_1   	[0.0001308],	||	 recall_5   	[0.0010464],	||	 recall_10   	[0.0026161],	||	 recall_15   	[0.0032701]
f_measure_1	[0.0001308],	||	 f_measure_5	[0.0003488],	||	 f_measure_10	[0.0004757],	||	 f_measure_15	[0.0004088]
ndcg_1     	[0.0001308],	||	 ndcg_5     	[0.0005728],	||	 ndcg_10     	[0.0010753],	||	 ndcg_15     	[0.0012485]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0003271],	||	 precision_10	[0.0003271],	||	 precision_15	[0.0002180]
recall_1	[0.0000000],	||	 recall_5	[0.0016353],	||	 recall_10	[0.0032706],	||	 recall_15	[0.0032706]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0007610],	||	 ndcg_10	[0.0012709],	||	 ndcg_15	[0.0012709]
AUC per user type	[0.5089878]
Metrics for user type	 Male
precision_1	[0.0001923],	||	 precision_5	[0.0001539],	||	 precision_10	[0.0002308],	||	 precision_15	[0.0002180]
recall_1	[0.0001923],	||	 recall_5	[0.0007694],	||	 recall_10	[0.0023081],	||	 recall_15	[0.0032699]
ndcg_1	[0.0001923],	||	 ndcg_5	[0.0004843],	||	 ndcg_10	[0.0009833],	||	 ndcg_15	[0.0012379]
AUC per user type	[0.5005251]
precision_1	[0.0001308],	||	 precision_5	[0.0001308],	||	 precision_10	[0.0002354],	||	 precision_15	[0.0002180]
recall_1   	[0.0001308],	||	 recall_5   	[0.0006540],	||	 recall_10   	[0.0023545],	||	 recall_15   	[0.0032701]
f_measure_1	[0.0001308],	||	 f_measure_5	[0.0002180],	||	 f_measure_10	[0.0004281],	||	 f_measure_15	[0.0004088]
ndcg_1     	[0.0001308],	||	 ndcg_5     	[0.0003480],	||	 ndcg_10     	[0.0009169],	||	 ndcg_15     	[0.0011609]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0000818],	||	 precision_10	[0.0003271],	||	 precision_15	[0.0002726]
recall_1	[0.0000000],	||	 recall_5	[0.0004088],	||	 recall_10	[0.0032706],	||	 recall_15	[0.0040883]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0001582],	||	 ndcg_10	[0.0011016],	||	 ndcg_15	[0.0013136]
AUC per user type	[0.5088100]
Metrics for user type	 Male
precision_1	[0.0001923],	||	 precision_5	[0.0001539],	||	 precision_10	[0.0001923],	||	 precision_15	[0.0001923]
recall_1	[0.0001923],	||	 recall_5	[0.0007694],	||	 recall_10	[0.0019234],	||	 recall_15	[0.0028852]
ndcg_1	[0.0001923],	||	 ndcg_5	[0.0004373],	||	 ndcg_10	[0.0008300],	||	 ndcg_15	[0.0010890]
AUC per user type	[0.5015382]
precision_1	[0.0000000],	||	 precision_5	[0.0001831],	||	 precision_10	[0.0002616],	||	 precision_15	[0.0002878]
recall_1   	[0.0000000],	||	 recall_5   	[0.0008110],	||	 recall_10   	[0.0025114],	||	 recall_15   	[0.0042119]
f_measure_1	[0.0000000],	||	 f_measure_5	[0.0002988],	||	 f_measure_10	[0.0004739],	||	 f_measure_15	[0.0005387]
ndcg_1     	[0.0000000],	||	 ndcg_5     	[0.0003865],	||	 ndcg_10     	[0.0009432],	||	 ndcg_15     	[0.0013882]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0001635],	||	 precision_10	[0.0002453],	||	 precision_15	[0.0003543]
recall_1	[0.0000000],	||	 recall_5	[0.0008177],	||	 recall_10	[0.0024530],	||	 recall_15	[0.0053148]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0003521],	||	 ndcg_10	[0.0009028],	||	 ndcg_15	[0.0016399]
AUC per user type	[0.5106783]
Metrics for user type	 Male
precision_1	[0.0000000],	||	 precision_5	[0.0001923],	||	 precision_10	[0.0002693],	||	 precision_15	[0.0002565]
recall_1	[0.0000000],	||	 recall_5	[0.0008078],	||	 recall_10	[0.0025389],	||	 recall_15	[0.0036930]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0004026],	||	 ndcg_10	[0.0009622],	||	 ndcg_15	[0.0012698]
AUC per user type	[0.5039748]
precision_1	[0.0000000],	||	 precision_5	[0.0002093],	||	 precision_10	[0.0003663],	||	 precision_15	[0.0003401]
recall_1   	[0.0000000],	||	 recall_5   	[0.0009418],	||	 recall_10   	[0.0034707],	||	 recall_15   	[0.0049095]
f_measure_1	[0.0000000],	||	 f_measure_5	[0.0003425],	||	 f_measure_10	[0.0006626],	||	 f_measure_15	[0.0006361]
ndcg_1     	[0.0000000],	||	 ndcg_5     	[0.0004666],	||	 ndcg_10     	[0.0012912],	||	 ndcg_15     	[0.0016769]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0001635],	||	 precision_10	[0.0004088],	||	 precision_15	[0.0003271]
recall_1	[0.0000000],	||	 recall_5	[0.0008177],	||	 recall_10	[0.0040883],	||	 recall_15	[0.0049060]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0004161],	||	 ndcg_10	[0.0014600],	||	 ndcg_15	[0.0016752]
AUC per user type	[0.5138913]
Metrics for user type	 Male
precision_1	[0.0000000],	||	 precision_5	[0.0002308],	||	 precision_10	[0.0003462],	||	 precision_15	[0.0003462]
recall_1	[0.0000000],	||	 recall_5	[0.0010002],	||	 recall_10	[0.0031801],	||	 recall_15	[0.0049112]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0004903],	||	 ndcg_10	[0.0012118],	||	 ndcg_15	[0.0016777]
AUC per user type	[0.5069941]
precision_1	[0.0000000],	||	 precision_5	[0.0002354],	||	 precision_10	[0.0005101],	||	 precision_15	[0.0004971]
recall_1   	[0.0000000],	||	 recall_5   	[0.0009854],	||	 recall_10   	[0.0046348],	||	 recall_15   	[0.0069021]
f_measure_1	[0.0000000],	||	 f_measure_5	[0.0003801],	||	 f_measure_10	[0.0009191],	||	 f_measure_15	[0.0009273]
ndcg_1     	[0.0000000],	||	 ndcg_5     	[0.0004859],	||	 ndcg_10     	[0.0016505],	||	 ndcg_15     	[0.0022462]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0001635],	||	 precision_10	[0.0004497],	||	 precision_15	[0.0004361]
recall_1	[0.0000000],	||	 recall_5	[0.0008177],	||	 recall_10	[0.0041701],	||	 recall_15	[0.0062142]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0003342],	||	 ndcg_10	[0.0013908],	||	 ndcg_15	[0.0019260]
AUC per user type	[0.5149395]
Metrics for user type	 Male
precision_1	[0.0000000],	||	 precision_5	[0.0002693],	||	 precision_10	[0.0005386],	||	 precision_15	[0.0005257]
recall_1	[0.0000000],	||	 recall_5	[0.0010643],	||	 recall_10	[0.0048535],	||	 recall_15	[0.0072257]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0005572],	||	 ndcg_10	[0.0017727],	||	 ndcg_15	[0.0023969]
AUC per user type	[0.5098257]
precision_1	[0.0000000],	||	 precision_5	[0.0003139],	||	 precision_10	[0.0006279],	||	 precision_15	[0.0006104]
recall_1   	[0.0000000],	||	 recall_5   	[0.0012732],	||	 recall_10   	[0.0057903],	||	 recall_15   	[0.0086026]
f_measure_1	[0.0000000],	||	 f_measure_5	[0.0005037],	||	 f_measure_10	[0.0011329],	||	 f_measure_15	[0.0011400]
ndcg_1     	[0.0000000],	||	 ndcg_5     	[0.0006277],	||	 ndcg_10     	[0.0020450],	||	 ndcg_15     	[0.0027879]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0002453],	||	 precision_10	[0.0004497],	||	 precision_15	[0.0004361]
recall_1	[0.0000000],	||	 recall_5	[0.0012265],	||	 recall_10	[0.0041701],	||	 recall_15	[0.0062142]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0004745],	||	 ndcg_10	[0.0013937],	||	 ndcg_15	[0.0019506]
AUC per user type	[0.5163918]
Metrics for user type	 Male
precision_1	[0.0000000],	||	 precision_5	[0.0003462],	||	 precision_10	[0.0007117],	||	 precision_15	[0.0006924]
recall_1	[0.0000000],	||	 recall_5	[0.0012951],	||	 recall_10	[0.0065525],	||	 recall_15	[0.0097262]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0006998],	||	 ndcg_10	[0.0023514],	||	 ndcg_15	[0.0031819]
AUC per user type	[0.5139290]

precision_1	[0.0000000],	||	 precision_5	[0.0002354],	||	 precision_10	[0.0006148],	||	 precision_15	[0.0006104]
recall_1   	[0.0000000],	||	 recall_5   	[0.0009854],	||	 recall_10   	[0.0055941],	||	 recall_15   	[0.0086026]
f_measure_1	[0.0000000],	||	 f_measure_5	[0.0003801],	||	 f_measure_10	[0.0011078],	||	 f_measure_15	[0.0011400]
ndcg_1     	[0.0000000],	||	 ndcg_5     	[0.0005231],	||	 ndcg_10     	[0.0019823],	||	 ndcg_15     	[0.0027811]
Metrics for user type	 Female
precision_1	[0.0000000],	||	 precision_5	[0.0001635],	||	 precision_10	[0.0005315],	||	 precision_15	[0.0004361]
recall_1	[0.0000000],	||	 recall_5	[0.0008177],	||	 recall_10	[0.0049877],	||	 recall_15	[0.0062142]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0003342],	||	 ndcg_10	[0.0016369],	||	 ndcg_15	[0.0019543]
AUC per user type	[0.5189485]
Metrics for user type	 Male
precision_1	[0.0000000],	||	 precision_5	[0.0002693],	||	 precision_10	[0.0006540],	||	 precision_15	[0.0006924]
recall_1	[0.0000000],	||	 recall_5	[0.0010643],	||	 recall_10	[0.0058793],	||	 recall_15	[0.0097262]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0006119],	||	 ndcg_10	[0.0021447],	||	 ndcg_15	[0.0031701]
AUC per user type	[0.5171484]

'"\nfor rec in list_recom_uemfairbpr:\n    [precision, recall, f_score, ndcg] = utility.test_model_all(rec, test_df, train_df)\n\n    [precision_per_user_type, recall_per_user_type, ndcg_per_user_type, auc_per_user_type] = utility.test_model_per_user_type(rec, test_df, train_df, user_type_list, key_type)\n    auc = utility.auc_per_user(rec, test_df, train_df)\n    auc_plot_uemfairadvbpr.append(auc)\n    precision_plot_uemfairadvbpr.append(precision)\n    recall_plot_uemfairadvbpr.append(recall)\n    ndcg_plot_uemfairadvbpr.append(ndcg)\n    \n    precision_perUserType_plot_uemfairadvbpr.append(precision_per_user_type)\n    recall_perUserType_plot_uemfairadvbpr.append(recall_per_user_type)\n    ndcg_perUserType_plot_uemfairadvbpr.append(ndcg_per_user_type)\n    auc_perUserType_plot_uemfairadvbpr.append(auc_per_user_type)\n    \n'

In [ ]:
len(list_recom_constiemfairadvbpr)

In [ ]:
unfairness_constiemfairbpr_05 = []
unfairness_constiemfairbpr_000001 = []
unfairness_constiemfairbpr_00001 = []
unfairness_constiemfairbpr_0001 = []
unfairness_constiemfairbpr_001 = []
unfairness_constiemfairbpr_01 = []
unfairness_constiemfairbpr_02 = []
unfairness_constiemfairbpr_06 = []
unfairness_constiemfairbpr_07 = []
unfairness_constiemfairbpr_08 = []
unfairness_constiemfairbpr_09 = []


unfairness_constiemfairbpr_05.append((auc_perUserType_plot_constiemfairbpr[-1]['M']**2 - auc_perUserType_plot_constiemfairbpr[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_000001.append((auc_per_type_constiemfairadvbpr_000001[-1]['M']**2 - auc_per_type_constiemfairadvbpr_000001[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_00001.append((auc_per_type_constiemfairadvbpr_00001[-1]['M']**2 - auc_per_type_constiemfairadvbpr_00001[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_0001.append((auc_per_type_constiemfairadvbpr_0001[-1]['M']**2 - auc_per_type_constiemfairadvbpr_0001[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_001.append((auc_per_type_constiemfairadvbpr_001[-1]['M']**2 - auc_per_type_constiemfairadvbpr_001[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_01.append((auc_per_type_constiemfairadvbpr_01[-1]['M']**2 - auc_per_type_constiemfairadvbpr_01[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_02.append((auc_per_type_constiemfairadvbpr_02[-1]['M']**2 - auc_per_type_constiemfairadvbpr_02[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_06.append((auc_per_type_constiemfairadvbpr_06[-1]['M']**2 - auc_per_type_constiemfairadvbpr_06[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_07.append((auc_per_type_constiemfairadvbpr_07[-1]['M']**2 - auc_per_type_constiemfairadvbpr_07[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_08.append((auc_per_type_constiemfairadvbpr_08[-1]['M']**2 - auc_per_type_constiemfairadvbpr_08[-1]['F']**2)**2*100)
unfairness_constiemfairbpr_09.append((auc_per_type_constiemfairadvbpr_09[-1]['M']**2 - auc_per_type_constiemfairadvbpr_09[-1]['F']**2)**2*100)


def plotline_save_as_pdf4(title='',axis_x1 = None, xlabel = '', axis_y1 = None, axis_y2 = None, ylabel1 ='', ylabel2 ='', linewidth=2, plot_file = '',legendy1='', legendy2=''):
    
    fig, ax1 = plt.subplots()

    color = 'tab:red'
    ax1.set_xlabel(xlabel)
    ax1.set_ylabel(ylabel1, color=color)
    if axis_y1 is not None:
        #plt.plot(axis_x1, axis_y1, 'b', linewidth = linewidth, label = legendy1)
        lns1 = ax1.plot(axis_x1, axis_y1, color=color, linewidth = linewidth, label = legendy1)
        ax1.tick_params(axis='y', labelcolor=color)
    
    ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

    color = 'tab:blue'
    ax2.set_ylabel(ylabel2, color=color)  # we already handled the x-label with ax1
    
    if axis_y2 is not None:
       # plt.plot(axis_x1, axis_y2, 'red', linewidth = linewidth, label = legendy2)
        lns2 = ax2.plot(axis_x1, axis_y2, color=color, linewidth = linewidth, label = legendy2)
        ax2.tick_params(axis='y', labelcolor=color)

    lns = lns1 + lns2
    labs = [l.get_label() for l in lns]
    plt.legend(lns, labs, loc=0)
    plt.title(title)
    plt.grid()

    plt.savefig(plot_file)

plotline_save_as_pdf4(title='Unfairness Constant Impact',axis_x1 = np.arange(0,1.1,0.1), xlabel = 'Unfairness Constant', axis_y1 = [auc_constiemfairadvbpr_000001[-1], auc_constiemfairadvbpr_00001[-1], auc_constiemfairadvbpr_0001[-1], auc_constiemfairadvbpr_001[-1], auc_constiemfairadvbpr_01[-1], auc_constiemfairadvbpr_02[-1], auc_plot_constiemfairbpr[-1],auc_constiemfairadvbpr_06[-1], auc_constiemfairadvbpr_07[-1], auc_constiemfairadvbpr_08[-1], auc_constiemfairadvbpr_09[-1]], axis_y2 = [unfairness_constiemfairbpr_000001[-1], unfairness_constiemfairbpr_00001[-1], unfairness_constiemfairbpr_0001[-1], unfairness_constiemfairbpr_001[-1], unfairness_constiemfairbpr_01[-1], unfairness_constiemfairbpr_02[-1], unfairness_constiemfairbpr_05[-1],unfairness_constiemfairbpr_06[-1], unfairness_constiemfairbpr_07[-1], unfairness_constiemfairbpr_08[-1], unfairness_constiemfairbpr_09[-1]], ylabel1 ='AUC', ylabel2 ='Unfairness', linewidth=2, plot_file = './unfairBPR_plots/unfairness_const_impact_per_type.pdf',legendy1='AUC Trend', legendy2='Unfairness Trend')

In [ ]:
 plotline_save_as_pdf2(title='AUC On Testing',axis_x1 = range(1,40+1), axis_x2 = range(21,40+1), xlabel = 'Epoch', axis_y1 = auc_plot_unfairbpr, axis_y2 = auc_plot_constiemfairbpr , axis_y3 = auc_plot_fairadvbpr,axis_y4 = auc_plot_iemfairadvbpr,axis_y5 = auc_plot_uemfairadvbpr, ylabel ='AUC', linewidth=2, plot_file = './unfairBPR_plots/auc_all_methods.pdf',legendy1='UnfairBPR',legendy2='CFairAdvBPR',legendy3='fairAdvBPR',legendy4='iemfairadv',legendy5='uemfairadv')

In [ ]:
plotline_save_as_pdf2(title='Precision On Testing',axis_x1 = range(1,40+1), axis_x2 = range(21,40+1), xlabel = 'Epoch', axis_y1 = np.array(precision_plot_unfairbpr)[:,-1], axis_y2 = np.array(precision_plot_constiemfairbpr)[:,-1] , axis_y3 = np.array(precision_plot_fairadvbpr)[:,-1], axis_y4 = np.array(precision_plot_iemfairadvbpr)[:,-1], axis_y5 = np.array(precision_plot_uemfairadvbpr)[:,-1], ylabel ='Precision', linewidth=2, plot_file = './unfairBPR_plots/precisionat15_all_methods.pdf',legendy1='UnfairBPR',legendy2='CFairAdvBPR',legendy3='fairAdvBPR',legendy4='iemfairadv',legendy5='uemfairadv')

In [ ]:
plotline_save_as_pdf2(title='NDCG On Testing',axis_x1 = range(1,40+1), axis_x2 = range(21,40+1), xlabel = 'Epoch', axis_y1 = np.array(ndcg_plot_unfairbpr)[:,-1], axis_y2 = np.array(ndcg_plot_constiemfairbpr)[:,-1] , axis_y3 = np.array(ndcg_plot_fairadvbpr)[:,-1], axis_y4 = np.array(ndcg_plot_iemfairadvbpr)[:,-1], axis_y5 = np.array(ndcg_plot_uemfairadvbpr)[:,-1], ylabel ='NDCG', linewidth=2, plot_file = './unfairBPR_plots/ndcgat15_all_methods.pdf',legendy1='UnfairBPR',legendy2='CFairAdvBPR',legendy3='fairAdvBPR',legendy4='iemfairadv',legendy5='uemfairadv')

In [ ]:
#auc_plot_constiemfairbpr[-1]
#axis_y3 = [auc_perUserType_plot_unfairbpr[-1]['F'],auc_perUserType_plot_constiemfairbpr[-1]['F'],auc_perUserType_plot_fairadvbpr[-1]['F'],auc_perUserType_plot_iemfairadvbpr[-1]['F'],auc_perUserType_plot_uemfairadvbpr[-1]['F']]
#axis_y1 = [auc_plot_unfairbpr[-1],auc_plot_constiemfairbpr[-1],auc_plot_fairadvbpr[-1] ,auc_plot_iemfairadvbpr[-1], auc_plot_uemfairadvbpr[-1]]

In [ ]:

savepdf_barplot_color_gradient(ymin = 0.76, ymax = 0.835, start_color='purple',end_color='orange',num_color=3, title='AUC per User Type on Testing (Movielens)',axis_x = ['UnfairBPR','CFairAdvBPR','fairAdvBPR','iemFairAdv','uemFairAdv'], xlabel = '', axis_y1 = [auc_plot_unfairbpr[-1],auc_plot_constiemfairbpr[-1],auc_plot_fairadvbpr[-2] ,auc_plot_iemfairadvbpr[-1], auc_plot_uemfairadvbpr[-1]], axis_y2 = [auc_perUserType_plot_unfairbpr[-1]['M'],auc_perUserType_plot_constiemfairbpr[-1]['M'],auc_perUserType_plot_fairadvbpr[-2]['M'],auc_perUserType_plot_iemfairadvbpr[-1]['M'],auc_perUserType_plot_uemfairadvbpr[-1]['M']], axis_y3 = [auc_perUserType_plot_unfairbpr[-1]['F'],auc_perUserType_plot_constiemfairbpr[-1]['F'],auc_perUserType_plot_fairadvbpr[-2]['F'],auc_perUserType_plot_iemfairadvbpr[-1]['F'],auc_perUserType_plot_uemfairadvbpr[-1]['F']], ylabel ='AUC',barwidth = 0.3, plot_file = './unfairBPR_plots/auc_05_per_type.pdf',legendy1='Overall',legendy2='Male',legendy3='Female')

In [ ]:
unfairness_unfairbpr = []
unfairness_constiemfairbpr = []
unfairness_fairadvbpr = []
unfairness_iemfairadvbpr = []
unfairness_uemfairadvbpr = []

for i in range(len(auc_perUserType_plot_unfairbpr)):
    unfairness_unfairbpr.append((auc_perUserType_plot_unfairbpr[i]['M']**2 - auc_perUserType_plot_unfairbpr[i]['F']**2)**2*100)

for i in range(len(auc_perUserType_plot_constiemfairbpr)):
    unfairness_constiemfairbpr.append((auc_perUserType_plot_constiemfairbpr[i]['M']**2 - auc_perUserType_plot_constiemfairbpr[i]['F']**2)**2*100)

for i in range(len(auc_perUserType_plot_fairadvbpr)):
    unfairness_fairadvbpr.append((auc_perUserType_plot_fairadvbpr[i]['M']**2 - auc_perUserType_plot_fairadvbpr[i]['F']**2)**2*100)

for i in range(len(auc_perUserType_plot_iemfairadvbpr)):
    unfairness_iemfairadvbpr.append((auc_perUserType_plot_iemfairadvbpr[i]['M']**2 - auc_perUserType_plot_iemfairadvbpr[i]['F']**2)**2*100)
    
for i in range(len(auc_perUserType_plot_uemfairadvbpr)):
    unfairness_uemfairadvbpr.append((auc_perUserType_plot_uemfairadvbpr[i]['M']**2 - auc_perUserType_plot_uemfairadvbpr[i]['F']**2)**2*100)

In [ ]:
#savepdf_barplot_color_gradient3(ymin = 0.76, ymax = 0.835, title='Unfairness per User Type on Testing',axis_x = ['UnfairBPR','CFairAdvBPR','fairAdvBPR','iemFairAdv','uemFairAdv'], xlabel = '', axis_y = [auc_plot_unfairbpr[-1],auc_plot_constiemfairbpr[-1],auc_plot_fairadvbpr[-2] ,auc_plot_iemfairadvbpr[-1], auc_plot_uemfairadvbpr[-1]], ylabel ='Unfairness',barwidth = 0.3, plot_file = './unfairBPR_plots/unfairness_per_type.pdf')
plotline_save_as_pdf2(title='Unfairness per User Type on Testing (Gender)',axis_x1 = range(1,40+1), axis_x2 = range(21,40+1), xlabel = 'Epoch', axis_y1 = unfairness_unfairbpr, axis_y2 = unfairness_constiemfairbpr , axis_y3 = unfairness_fairadvbpr, axis_y4 = unfairness_iemfairadvbpr, axis_y5 = unfairness_uemfairadvbpr, ylabel ='Unfairness', linewidth=2, plot_file = './unfairBPR_plots/unfairness_per_type.pdf',legendy1='UnfairBPR',legendy2='CFairAdvBPR',legendy3='fairAdvBPR',legendy4='iemfairadv',legendy5='uemfairadv')

In [ ]:
savepdf_barplot_color_gradient(ymin = 0.1, ymax = 0.2, start_color='purple',end_color='orange',num_color=3, title='Precision per User Type on Testing (Movielens)',axis_x = ['UnfairBPR','CFairAdvBPR','fairAdvBPR','iemFairAdv','uemFairAdv'], xlabel = '', axis_y1 = [precision_plot_unfairbpr[-1][2], precision_plot_constiemfairbpr[-10][2],precision_plot_fairadvbpr[-1][2] ,precision_plot_iemfairadvbpr[-1][2], precision_plot_uemfairadvbpr[-1][2]], axis_y2 = [precision_perUserType_plot_unfairbpr[-1]['M'][0].tolist()[2],precision_perUserType_plot_constiemfairbpr[-1]['M'][0].tolist()[2],precision_perUserType_plot_fairadvbpr[-1]['M'][0].tolist()[2],precision_perUserType_plot_iemfairadvbpr[-1]['M'][0].tolist()[2],precision_perUserType_plot_uemfairadvbpr[-1]['M'][0].tolist()[2]], axis_y3 = [precision_perUserType_plot_unfairbpr[-1]['F'][0].tolist()[2], precision_perUserType_plot_constiemfairbpr[-10]['F'][0].tolist()[1],precision_perUserType_plot_fairadvbpr[-20]['F'][0].tolist()[2],precision_perUserType_plot_iemfairadvbpr[-20]['F'][0].tolist()[2],precision_perUserType_plot_uemfairadvbpr[-20]['F'][0].tolist()[2]], ylabel ='Precision',barwidth = 0.3, plot_file = './unfairBPR_plots/precision_05_per_type.pdf',legendy1='Overall',legendy2='Male',legendy3='Female')

In [ ]:
savepdf_barplot_color_gradient(ymin = 0.1, ymax = 0.25, start_color='purple',end_color='orange',num_color=3, title='NDCG per User Type on Testing (Movielens)',axis_x = ['UnfairBPR','CFairAdvBPR','fairAdvBPR','iemFairAdv','uemFairAdv'], xlabel = '', axis_y1 = [ndcg_plot_unfairbpr[-1][2],ndcg_plot_constiemfairbpr[1][2],ndcg_plot_fairadvbpr[-1][2] ,ndcg_plot_iemfairadvbpr[-1][2], ndcg_plot_uemfairadvbpr[-1][2]], axis_y2 = [ndcg_perUserType_plot_unfairbpr[-1]['M'][0].tolist()[2],ndcg_perUserType_plot_constiemfairbpr[1]['M'][0].tolist()[3],ndcg_perUserType_plot_fairadvbpr[-1]['M'][0].tolist()[2], ndcg_perUserType_plot_iemfairadvbpr[-1]['M'][0].tolist()[2],ndcg_perUserType_plot_uemfairadvbpr[-1]['M'][0].tolist()[2]], axis_y3 = [ndcg_perUserType_plot_unfairbpr[-1]['F'][0].tolist()[3], ndcg_perUserType_plot_constiemfairbpr[-20]['F'][0].tolist()[1],ndcg_perUserType_plot_fairadvbpr[-20]['F'][0].tolist()[2], ndcg_perUserType_plot_iemfairadvbpr[-20]['F'][0].tolist()[2], ndcg_perUserType_plot_uemfairadvbpr[-20]['F'][0].tolist()[2]], ylabel ='NDCG',barwidth = 0.3, plot_file = './unfairBPR_plots/ndcg_05_per_type.pdf',legendy1='Overall',legendy2='Male',legendy3='Female')

In [ ]:
precision_perUserType_plot_fairadvbpr[-1]