In [1]:
import tensorflow as tf
import time
import numpy as np
import os
import copy
import pickle5 as pickle
import argparse
import utilityarm as utility
import pandas as pd
from sklearn.metrics import *
import tensorflow.keras.backend as K

In [2]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior() 

class FairAdvBPR:

    def __init__(self, sess, dict_args, train_df, test_df, user_type, type_error_weight, key_type, user_type_list, item_type_count):
       
        self.dataname = dict_args['dataname']

        self.key_type = key_type
        self.user_type_list = user_type_list
        self.item_type_count = item_type_count
        self.layers = dict_args['layers']
        self.sess = sess
        
        self.num_cols = len(train_df['item_id'].unique())
        self.num_rows = len(train_df['user_id'].unique())

        self.hidden_neuron = dict_args['hidden_neuron']
        self.neg = dict_args['neg']
        self.batch_size = dict_args['batch_size']

        self.train_df = train_df
        self.vali_df = test_df
        self.num_train = len(self.train_df)
        self.num_vali = len(self.vali_df)

        self.train_epoch = dict_args['train_epoch']
        self.train_epoch_a = dict_args['train_epoch_a']

        self.lr_r = dict_args['lr_r'] # learning rate
        self.lr_a = dict_args['lr_a'] # learning rate
        self.alpha = dict_args['alpha'] # learning rate
        self.optimizer_method = dict_args['optimizer_method']
        self.display_step = dict_args['display_step']
        
        self.type_error_weight = type_error_weight
        self.num_type = dict_args['num_type']
        
        self.user_type = user_type
        self.type_count_list = []
        for k in range(self.num_type):
            self.type_count_list.append(np.sum(user_type[:,k]))

        
        self.reg = dict_args['reg'] # regularization term trade-off
        self.reg_s = dict_args['reg_s']

        print('**********fairAdvBPR**********')
        #print(self.args)
        self._prepare_model()

    def loadmodel(self, saver, checkpoint_dir):
        ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
            ckpt_name = os.path.basename(ckpt.model_checkpoint_path)
            saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
            return True
        else:
            return False
        
    def run(self):
        init = tf.global_variables_initializer()
        self.sess.run(init)

        saver = tf.train.Saver([self.P, self.Q])
        self.loadmodel(saver, "./"+self.dataname+"/BPR_check_points")

        for epoch_itr in range(1, self.train_epoch + 1 + self.train_epoch_a):
            self.train_model(epoch_itr)
            if epoch_itr % self.display_step == 0:
                self.test_model(epoch_itr)
        return self.make_records()

    def _prepare_model(self):
        with tf.name_scope("input_data"):
            self.user_input = tf.placeholder(tf.int32, shape=[None, 1], name="user_input")
            self.item_input_pos = tf.placeholder(tf.int32, shape=[None, 1], name="item_input_pos")
            self.item_input_neg = tf.placeholder(tf.int32, shape=[None, 1], name="item_input_neg")

            self.input_user_type = tf.placeholder(dtype=tf.float32, shape=[None, self.num_type]
                                                   , name="input_user_type")
            self.input_user_error_weight = tf.placeholder(dtype=tf.float32, shape=[None, 1]
                                                          , name="input_user_error_weight")

        with tf.variable_scope("BPR", reuse=tf.AUTO_REUSE):
            self.P = tf.get_variable(name="P",
                                     initializer=tf.truncated_normal(shape=[self.num_rows, self.hidden_neuron], mean=0,
                                                                     stddev=0.03), dtype=tf.float32)
            self.Q = tf.get_variable(name="Q",
                                     initializer=tf.truncated_normal(shape=[self.num_cols+1, self.hidden_neuron], mean=0,
                                                                     stddev=0.03), dtype=tf.float32)
        para_r = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="BPR")

        with tf.variable_scope("Adversarial", reuse=tf.AUTO_REUSE):
            num_layer = len(self.layers)
            adv_W = []
            adv_b = []
            for l in range(num_layer):
                if l == 0:
                    in_shape = 1
                else:
                    in_shape = self.layers[l - 1]
                adv_W.append(tf.get_variable(name="adv_W" + str(l),
                                             initializer=tf.truncated_normal(shape=[in_shape, self.layers[l]],
                                                                             mean=0, stddev=0.03), dtype=tf.float32))
                adv_b.append(tf.get_variable(name="adv_b" + str(l),
                                             initializer=tf.truncated_normal(shape=[1, self.layers[l]],
                                                                             mean=0, stddev=0.03), dtype=tf.float32))
            adv_W_out = tf.get_variable(name="adv_W_out",
                                        initializer=tf.truncated_normal(shape=[self.layers[-1], self.num_type],
                                                                        mean=0, stddev=0.03), dtype=tf.float32)

            adv_b_out = tf.get_variable(name="adv_b_out",
                                        initializer=tf.truncated_normal(shape=[1, self.num_type],
                                                                        mean=0, stddev=0.03), dtype=tf.float32)
        para_a = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="Adversarial")

        p = tf.reduce_sum(tf.nn.embedding_lookup(self.P, self.user_input), 1)
        q_neg = tf.reduce_sum(tf.nn.embedding_lookup(self.Q, self.item_input_neg), 1)
        q_pos = tf.reduce_sum(tf.nn.embedding_lookup(self.Q, self.item_input_pos), 1)

        predict_pos = tf.reduce_sum(p * q_pos, 1)
        predict_neg = tf.reduce_sum(p * q_neg, 1)

        r_cost1 = tf.reduce_sum(tf.nn.softplus(-(predict_pos - predict_neg)))
        r_cost2 = self.reg * 0.5 * (self.l2_norm(self.P) + self.l2_norm(self.Q))  # regularization term
        pred = tf.matmul(self.P, tf.transpose(self.Q))
        self.s_mean = tf.reduce_mean(pred, axis=1)
        self.s_std = tf.keras.backend.std(pred, axis=1)
        self.s_cost = tf.reduce_sum(tf.square(self.s_mean) + tf.square(self.s_std) - 2 * tf.log(self.s_std) - 1)
        self.r_cost = r_cost1 + r_cost2 + self.reg_s * 0.5 * self.s_cost

        adv_last = tf.reshape(predict_pos, [tf.shape(self.input_user_type)[0], 1])
        for l in range(num_layer):
            adv = tf.nn.relu(tf.matmul(adv_last, adv_W[l]) + adv_b[l])
            adv_last = adv
        self.adv_output = tf.nn.sigmoid(tf.matmul(adv_last, adv_W_out) + adv_b_out)
        self.a_cost = tf.reduce_sum(tf.square(self.adv_output - self.input_user_type) * self.input_user_error_weight)

        self.all_cost = self.r_cost - self.alpha * self.a_cost  # the loss function

        with tf.variable_scope("Optimizer", reuse=tf.AUTO_REUSE):
            self.r_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_r).minimize(self.r_cost, var_list=para_r)
            self.a_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_a).minimize(self.a_cost, var_list=para_a)
            self.all_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_r).minimize(self.all_cost, var_list=para_r)


    def train_model(self, itr):
        NS_start_time = time.time() * 1000.0
        epoch_r_cost = 0.0
        epoch_s_cost = 0.0
        epoch_s_mean = 0.0
        epoch_s_std = 0.0
        epoch_a_cost = 0.0
        num_sample, user_list, item_pos_list, item_neg_list = utility.negative_sample(self.train_df, self.num_rows,
                                                                                      self.num_cols, self.neg)
        NS_end_time = time.time() * 1000.0

        start_time = time.time() * 1000.0
        num_batch = int(num_sample / float(self.batch_size)) + 1
        random_idx = np.random.permutation(num_sample)
        for i in range(num_batch):
            # get the indices of the current batch
            if i == num_batch - 1:
                batch_idx = random_idx[i * self.batch_size:]
            elif i < num_batch - 1:
                batch_idx = random_idx[(i * self.batch_size):((i + 1) * self.batch_size)]

            if itr > self.train_epoch:
                random_idx_a = np.random.permutation(num_sample)
                print("boucle adversarial debut-- num batch ",i)
                for j in range(num_batch):
                    if j == num_batch - 1:
                        batch_idx_a = random_idx_a[j * self.batch_size:]
                    elif j < num_batch - 1:
                        batch_idx_a = random_idx_a[(j * self.batch_size):((j + 1) * self.batch_size)]
                    user_idx_list = ((user_list[batch_idx_a, :]).reshape((len(batch_idx_a)))).tolist()
                    _, tmp_a_cost = self.sess.run(  # do the optimization by the minibatch
                        [self.a_optimizer, self.a_cost],
                        feed_dict={self.user_input: user_list[batch_idx_a, :],
                                   self.item_input_pos: item_pos_list[batch_idx_a, :],
                                   self.item_input_neg: item_neg_list[batch_idx_a, :],
                                   self.input_user_type: self.user_type[user_idx_list,:],
                                   self.input_user_error_weight: self.type_error_weight[user_idx_list,:]})
                    epoch_a_cost += tmp_a_cost

                user_idx_list = ((user_list[batch_idx, :]).reshape((len(batch_idx)))).tolist()
                _, tmp_r_cost, tmp_s_cost, tmp_s_mean, tmp_s_std = self.sess.run(  # do the optimization by the minibatch
                    [self.all_optimizer, self.all_cost, self.s_cost, self.s_mean, self.s_std],
                    feed_dict={self.user_input: user_list[batch_idx, :],
                               self.item_input_pos: item_pos_list[batch_idx, :],
                               self.item_input_neg: item_neg_list[batch_idx, :],
                               self.input_user_type: self.user_type[user_idx_list, :],
                               self.input_user_error_weight: self.type_error_weight[user_idx_list, :]})
                epoch_r_cost += tmp_r_cost
                epoch_s_mean += np.mean(tmp_s_mean)
                epoch_s_std += np.mean(tmp_s_std)
                epoch_s_cost += tmp_s_cost
                print("boucle adversarial fin")
            else:
                user_idx_list = ((user_list[batch_idx, :]).reshape((len(batch_idx)))).tolist()
                _, tmp_r_cost, tmp_s_cost, tmp_s_mean, tmp_s_std = self.sess.run(  # do the optimization by the minibatch
                    [self.r_optimizer, self.r_cost, self.s_cost, self.s_mean, self.s_std],
                    feed_dict={self.user_input: user_list[batch_idx, :],
                               self.item_input_pos: item_pos_list[batch_idx, :],
                               self.item_input_neg: item_neg_list[batch_idx, :],
                               self.input_user_type: self.user_type[user_idx_list, :],
                               self.input_user_error_weight: self.type_error_weight[user_idx_list, :]})
                epoch_r_cost += tmp_r_cost
                epoch_s_mean += np.mean(tmp_s_mean)
                epoch_s_std += np.mean(tmp_s_std)
                epoch_s_cost += tmp_s_cost
        epoch_a_cost /= num_batch
        if itr % self.display_step == 0:
            print ("Training //", "Epoch %d //" % itr, " Total r_cost = %.5f" % epoch_r_cost,
                   " Total s_cost = %.5f" % epoch_s_cost,
                   " Total s_mean = %.5f" % epoch_s_mean,
                   " Total s_std = %.5f" % epoch_s_std,
                   " Total a_cost = %.5f" % epoch_a_cost,
                   "Training time : %d ms" % (time.time() * 1000.0 - start_time),
                   "negative Sampling time : %d ms" % (NS_end_time - NS_start_time),
                   "negative samples : %d" % (num_sample))
       
    def test_model(self, itr):  # calculate the cost and rmse of testing set in each epoch
        if itr % self.display_step == 0:
            start_time = time.time() * 1000.0
            P, Q = self.sess.run([self.P, self.Q])
            Rec = np.matmul(P, Q.T)

            [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
#             utility.ranking_analysis(Rec, self.vali_df, self.train_df, self.key_genre, self.item_genre_list,
#                                      self.user_genre_count)
            utility.test_model_per_user_type(Rec, self.vali_df, self.train_df, self.user_type_list, self.key_type)
            auc = utility.auc_per_user(Rec, self.vali_df, self.train_df)
            print("AUC global is: ", auc)

            filename = './fairAdvBPR_results/epoch'+ str(itr) +'_Rec_' + self.dataname + '_fairAdvBPR.npy'
            os.makedirs(os.path.dirname(filename), exist_ok=True)           
            with open(filename, "wb") as f:
                np.save(f, Rec)
            

    def make_records(self):  # record all the results' details into files
        P, Q = self.sess.run([self.P, self.Q])
        Rec = np.matmul(P, Q.T)

        [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
        return precision, recall, f_score, NDCG, Rec

#     def test_model(self, itr):  # calculate the cost and rmse of testing set in each epoch
#         if itr % self.display_step == 0:
#             start_time = time.time() * 1000.0
#             P, Q = self.sess.run([self.P, self.Q])
#             Rec = np.matmul(P, Q.T)

#             [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
# #             utility.ranking_analysis(Rec, self.vali_df, self.train_df, self.key_type, self.user_type_list,
# #                                      self.item_type_count)
#             utility.test_model_per_user_type(Rec, self.vali_df, self.train_df, self.user_type_list, self.key_type)
#             auc = utility.auc_per_user(Rec, self.vali_df, self.train_df)
#             print("AUC global is: ", auc)
#             print (
#                 "Testing //", "Epoch %d //" % itr,
#                 "Testing time : %d ms" % (time.time() * 1000.0 - start_time))
#             print("=" * 200)


    @staticmethod
    def l2_norm(tensor):
        return tf.reduce_sum(tf.square(tensor))

WARNING:tensorflow:From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [3]:

#optimizer_method = ['Adam', 'Adadelta', 'Adagrad', 'RMSProp', 'GradientDescent','Momentum'], default='Adam')


train_epoch = 1
train_epoch_a = 10 #default 20
display_step = 1
lr_r = 0.01
lr_a = 0.005
reg = 0.1
reg_s = 30
alpha = 1000
optimizer_method = 'Adam'
hidden_neuron = 20
n = 1
neg = 5
batch_size = 1024
layers = [50, 50, 50, 50]
dataname = 'modcloth'

In [4]:
# parser.add_argument('--train_epoch', type=int, default=0)
# parser.add_argument('--train_epoch_a', type=int, default=20)
# parser.add_argument('--display_step', type=int, default=1)
# parser.add_argument('--lr_r', type=float, default=0.01)
# parser.add_argument('--lr_a', type=float, default=0.005)
# parser.add_argument('--reg', type=float, default=0.1)
# parser.add_argument('--reg_s', type=float, default=30)
# parser.add_argument('--hidden_neuron', type=int, default=20)
# parser.add_argument('--n', type=int, default=1)
# parser.add_argument('--neg', type=int, default=5)
# parser.add_argument('--alpha', type=float, default=1000.0)
# parser.add_argument('--batch_size', type=int, default=1024)
# parser.add_argument('--layers', nargs='?', default='[50, 50, 50, 50]')
# parser.add_argument('--dataname', nargs='?', default='ml1m-6')

In [5]:
dict_args =  {"train_epoch": train_epoch,
              "train_epoch_a": train_epoch_a,
            "display_step":display_step,
            "lr_r":lr_r,
            "lr_a":lr_a,
            "reg":reg,
            "reg_s":reg_s,
            "alpha":alpha,
            "optimizer_method":optimizer_method,
            "hidden_neuron":hidden_neuron,
            "n":n,
            "neg":neg,
            "batch_size":batch_size,
            "layers":layers,
            "dataname":dataname}
dict_args

{'train_epoch': 1,
 'train_epoch_a': 10,
 'display_step': 1,
 'lr_r': 0.01,
 'lr_a': 0.005,
 'reg': 0.1,
 'reg_s': 30,
 'alpha': 1000,
 'optimizer_method': 'Adam',
 'hidden_neuron': 20,
 'n': 1,
 'neg': 5,
 'batch_size': 1024,
 'layers': [50, 50, 50, 50],
 'dataname': 'modcloth'}

In [6]:
with open('./training_df_modcloth.pkl', 'rb') as f:
    train_df = pickle.load(f,encoding='latin1')

# with open('./' + dataname + '/valiing_df.pkl', 'rb') as f:
#     vali_df = pickle.load(f,encoding='latin1')  # for validation
    
with open('./testing_df_modcloth.pkl', 'rb') as f:
    test_df = pickle.load(f,encoding='latin1')  # for validation
# vali_df = pickle.load(open('./' + dataname + '/testing_df.pkl'))  # for testing

with open('./key_type_modcloth.pkl', 'rb') as f:
    key_type = pickle.load(f,encoding='latin1')
    
with open('./user_idd_type_list_modcloth.pkl', 'rb') as f:
    user_idd_type_list = pickle.load(f,encoding='latin1')
    
with open('./type_user_vector_modcloth.pkl', 'rb') as f:
    type_user_vector = pickle.load(f,encoding='latin1')

with open('./type_count_modcloth.pkl', 'rb') as f:
    type_count = pickle.load(f,encoding='latin1')
    
with open('./item_type_count_modcloth.pkl', 'rb') as f:
    item_type_count = pickle.load(f,encoding='latin1')

In [7]:
train_df.head(20)

    user_id  item_id  rating
0         0        0       4
1         1        0       4
2         2        0       4
3         3        0       2
4         4        0       4
5         5        0       4
6         6        0       5
7         7        0       5
8         8        0       5
9         9        0       5
10       10        0       4
11       11        1       5
12       12        1       5
13       13        1       5
14       14        1       5
15       15        1       5
16       16        1       5
17       18        0       5
18       19        1       5
19       22        0       4

In [8]:
train_df.shape

(40354, 3)

In [9]:
test_df.head(20)

    user_id  item_id  rating
0        17        1       5
1        20        0       5
2        21        0       2
3        26        2       5
4        32        2       5
5        39        1       3
6        45        0       4
7        56        0       5
8        60        2       5
9        61        2       4
10       65        1       4
11       72        1       5
12       85        2       2
13       86        2       5
14       93        1       5
15       94        2       3
16       96        2       4
17       97        2       5
18      105        2       4
19      106        2       4

In [10]:
test_df.shape

(10894, 3)

In [11]:
print(len(user_idd_type_list))

6339

In [12]:
user_idd_type_list

[['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Large'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Large'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Large'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Large'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Large'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ['Small'],
 ...]

In [13]:
type_user_vector

{'Small': array([[1., 1., 1., ..., 0., 0., 1.]]),
 'Large': array([[0., 0., 0., ..., 1., 1., 0.]])}

In [14]:
len(item_type_count)

915

In [15]:
item_type_count

[{'Small': 4314, 'Large': 1684},
 {'Small': 4317, 'Large': 1678},
 {'Small': 4273, 'Large': 1660},
 {'Small': 4121, 'Large': 1628},
 {'Small': 4324, 'Large': 1673},
 {'Small': 4338, 'Large': 1676},
 {'Small': 4458, 'Large': 1697},
 {'Small': 4318, 'Large': 1677},
 {'Small': 4385, 'Large': 1704},
 {'Small': 4419, 'Large': 1682},
 {'Small': 4332, 'Large': 1671},
 {'Small': 4248, 'Large': 1662},
 {'Small': 4242, 'Large': 1669},
 {'Small': 4403, 'Large': 1680},
 {'Small': 4224, 'Large': 1643},
 {'Small': 4284, 'Large': 1654},
 {'Small': 4376, 'Large': 1692},
 {'Small': 4338, 'Large': 1644},
 {'Small': 4413, 'Large': 1697},
 {'Small': 4087, 'Large': 1576},
 {'Small': 4451, 'Large': 1670},
 {'Small': 4525, 'Large': 1693},
 {'Small': 4292, 'Large': 1645},
 {'Small': 4403, 'Large': 1687},
 {'Small': 4283, 'Large': 1649},
 {'Small': 4402, 'Large': 1699},
 {'Small': 4500, 'Large': 1698},
 {'Small': 4446, 'Large': 1683},
 {'Small': 4462, 'Large': 1687},
 {'Small': 4449, 'Large': 1700},
 {'Small': 4512, 'Large': 1703},
 {'Small': 4382, 'Large': 1682},
 {'Small': 4530, 'Large': 1715},
 {'Small': 4593, 'Large': 1719},
 {'Small': 4434, 'Large': 1675},
 {'Small': 4282, 'Large': 1629},
 {'Small': 4463, 'Large': 1680},
 {'Small': 4511, 'Large': 1696},
 {'Small': 4466, 'Large': 1714},
 {'Small': 4378, 'Large': 1681},
 {'Small': 4279, 'Large': 1653},
 {'Small': 4275, 'Large': 1701},
 {'Small': 4519, 'Large': 1713},
 {'Small': 4299, 'Large': 1655},
 {'Small': 4428, 'Large': 1682},
 {'Small': 4436, 'Large': 1695},
 {'Small': 4516, 'Large': 1716},
 {'Small': 4553, 'Large': 1708},
 {'Small': 4382, 'Large': 1690},
 {'Small': 4385, 'Large': 1722},
 {'Small': 4475, 'Large': 1710},
 {'Small': 4351, 'Large': 1662},
 {'Small': 4559, 'Large': 1717},
 {'Small': 4463, 'Large': 1661},
 {'Small': 4550, 'Large': 1720},
 {'Small': 4233, 'Large': 1668},
 {'Small': 4482, 'Large': 1686},
 {'Small': 4466, 'Large': 1714},
 {'Small': 4442, 'Large': 1684},
 {'Small': 4573, 'Large': 1692},
 {'Small': 4497, 'Large': 1706},
 {'Small': 4352, 'Large': 1638},
 {'Small': 4418, 'Large': 1664},
 {'Small': 4575, 'Large': 1698},
 {'Small': 4464, 'Large': 1681},
 {'Small': 4380, 'Large': 1673},
 {'Small': 4440, 'Large': 1713},
 {'Small': 4534, 'Large': 1705},
 {'Small': 4489, 'Large': 1725},
 {'Small': 4584, 'Large': 1708},
 {'Small': 4444, 'Large': 1648},
 {'Small': 4500, 'Large': 1711},
 {'Small': 4431, 'Large': 1678},
 {'Small': 4457, 'Large': 1717},
 {'Small': 4503, 'Large': 1706},
 {'Small': 4515, 'Large': 1718},
 {'Small': 4460, 'Large': 1680},
 {'Small': 4440, 'Large': 1670},
 {'Small': 4489, 'Large': 1704},
 {'Small': 4522, 'Large': 1699},
 {'Small': 4515, 'Large': 1687},
 {'Small': 4331, 'Large': 1640},
 {'Small': 4529, 'Large': 1713},
 {'Small': 4416, 'Large': 1657},
 {'Small': 4437, 'Large': 1688},
 {'Small': 4594, 'Large': 1703},
 {'Small': 4412, 'Large': 1671},
 {'Small': 4546, 'Large': 1720},
 {'Small': 4410, 'Large': 1682},
 {'Small': 4391, 'Large': 1687},
 {'Small': 4553, 'Large': 1704},
 {'Small': 4432, 'Large': 1677},
 {'Small': 4507, 'Large': 1717},
 {'Small': 4459, 'Large': 1670},
 {'Small': 4485, 'Large': 1693},
 {'Small': 4543, 'Large': 1707},
 {'Small': 4540, 'Large': 1709},
 {'Small': 4530, 'Large': 1696},
 {'Small': 4480, 'Large': 1689},
 {'Small': 4464, 'Large': 1720},
 {'Small': 4354, 'Large': 1578},
 {'Small': 4497, 'Large': 1712},
 {'Small': 4444, 'Large': 1683},
 {'Small': 4518, 'Large': 1701},
 {'Small': 4517, 'Large': 1694},
 {'Small': 4588, 'Large': 1721},
 {'Small': 4539, 'Large': 1704},
 {'Small': 4367, 'Large': 1661},
 {'Small': 4358, 'Large': 1708},
 {'Small': 4507, 'Large': 1696},
 {'Small': 4393, 'Large': 1676},
 {'Small': 4553, 'Large': 1704},
 {'Small': 4543, 'Large': 1696},
 {'Small': 4546, 'Large': 1688},
 {'Small': 4580, 'Large': 1711},
 {'Small': 4549, 'Large': 1710},
 {'Small': 4596, 'Large': 1722},
 {'Small': 4472, 'Large': 1690},
 {'Small': 4545, 'Large': 1705},
 {'Small': 4522, 'Large': 1710},
 {'Small': 4561, 'Large': 1715},
 {'Small': 4483, 'Large': 1683},
 {'Small': 4584, 'Large': 1715},
 {'Small': 4454, 'Large': 1677},
 {'Small': 4522, 'Large': 1701},
 {'Small': 4464, 'Large': 1683},
 {'Small': 4518, 'Large': 1707},
 {'Small': 4496, 'Large': 1689},
 {'Small': 4529, 'Large': 1699},
 {'Small': 4482, 'Large': 1720},
 {'Small': 4557, 'Large': 1704},
 {'Small': 4582, 'Large': 1723},
 {'Small': 4540, 'Large': 1714},
 {'Small': 4542, 'Large': 1706},
 {'Small': 4521, 'Large': 1694},
 {'Small': 4547, 'Large': 1707},
 {'Small': 4524, 'Large': 1707},
 {'Small': 4553, 'Large': 1709},
 {'Small': 4585, 'Large': 1719},
 {'Small': 4485, 'Large': 1690},
 {'Small': 4482, 'Large': 1699},
 {'Small': 4475, 'Large': 1681},
 {'Small': 4555, 'Large': 1723},
 {'Small': 4539, 'Large': 1696},
 {'Small': 4547, 'Large': 1713},
 {'Small': 4582, 'Large': 1722},
 {'Small': 4584, 'Large': 1725},
 {'Small': 4545, 'Large': 1712},
 {'Small': 4575, 'Large': 1718},
 {'Small': 4560, 'Large': 1708},
 {'Small': 4535, 'Large': 1707},
 {'Small': 4506, 'Large': 1689},
 {'Small': 4564, 'Large': 1721},
 {'Small': 4537, 'Large': 1707},
 {'Small': 4528, 'Large': 1704},
 {'Small': 4577, 'Large': 1721},
 {'Small': 4548, 'Large': 1701},
 {'Small': 4572, 'Large': 1723},
 {'Small': 4570, 'Large': 1712},
 {'Small': 4546, 'Large': 1710},
 {'Small': 4574, 'Large': 1714},
 {'Small': 4510, 'Large': 1701},
 {'Small': 4579, 'Large': 1724},
 {'Small': 4546, 'Large': 1725},
 {'Small': 4554, 'Large': 1707},
 {'Small': 4533, 'Large': 1712},
 {'Small': 4590, 'Large': 1723},
 {'Small': 4529, 'Large': 1704},
 {'Small': 4564, 'Large': 1715},
 {'Small': 4511, 'Large': 1697},
 {'Small': 4575, 'Large': 1716},
 {'Small': 4561, 'Large': 1702},
 {'Small': 4584, 'Large': 1721},
 {'Small': 4521, 'Large': 1699},
 {'Small': 4584, 'Large': 1724},
 {'Small': 4603, 'Large': 1721},
 {'Small': 4554, 'Large': 1709},
 {'Small': 4576, 'Large': 1717},
 {'Small': 4597, 'Large': 1719},
 {'Small': 4581, 'Large': 1715},
 {'Small': 4598, 'Large': 1722},
 {'Small': 4579, 'Large': 1723},
 {'Small': 4583, 'Large': 1719},
 {'Small': 4598, 'Large': 1720},
 {'Small': 4592, 'Large': 1722},
 {'Small': 4567, 'Large': 1723},
 {'Small': 4563, 'Large': 1708},
 {'Small': 4601, 'Large': 1722},
 {'Small': 4603, 'Large': 1723},
 {'Small': 4588, 'Large': 1715},
 {'Small': 4584, 'Large': 1710},
 {'Small': 4583, 'Large': 1719},
 {'Small': 4569, 'Large': 1716},
 {'Small': 4596, 'Large': 1720},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4585, 'Large': 1721},
 {'Small': 4584, 'Large': 1721},
 {'Small': 4595, 'Large': 1724},
 {'Small': 4557, 'Large': 1707},
 {'Small': 4525, 'Large': 1685},
 {'Small': 4593, 'Large': 1718},
 {'Small': 4604, 'Large': 1725},
 {'Small': 4589, 'Large': 1719},
 {'Small': 4609, 'Large': 1722},
 {'Small': 4587, 'Large': 1716},
 {'Small': 4580, 'Large': 1719},
 {'Small': 4575, 'Large': 1722},
 {'Small': 4602, 'Large': 1724},
 {'Small': 4606, 'Large': 1724},
 {'Small': 4520, 'Large': 1706},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4592, 'Large': 1720},
 {'Small': 4592, 'Large': 1717},
 {'Small': 4565, 'Large': 1712},
 {'Small': 4574, 'Large': 1718},
 {'Small': 4555, 'Large': 1714},
 {'Small': 4569, 'Large': 1706},
 {'Small': 4589, 'Large': 1720},
 {'Small': 4568, 'Large': 1714},
 {'Small': 4593, 'Large': 1723},
 {'Small': 4583, 'Large': 1720},
 {'Small': 4579, 'Large': 1720},
 {'Small': 4606, 'Large': 1724},
 {'Small': 4602, 'Large': 1723},
 {'Small': 4597, 'Large': 1721},
 {'Small': 4592, 'Large': 1721},
 {'Small': 4588, 'Large': 1717},
 {'Small': 4595, 'Large': 1724},
 {'Small': 4595, 'Large': 1724},
 {'Small': 4587, 'Large': 1723},
 {'Small': 4603, 'Large': 1723},
 {'Small': 4608, 'Large': 1721},
 {'Small': 4603, 'Large': 1725},
 {'Small': 4586, 'Large': 1722},
 {'Small': 4594, 'Large': 1722},
 {'Small': 4600, 'Large': 1724},
 {'Small': 4581, 'Large': 1722},
 {'Small': 4606, 'Large': 1720},
 {'Small': 4593, 'Large': 1724},
 {'Small': 4580, 'Large': 1723},
 {'Small': 4586, 'Large': 1724},
 {'Small': 4589, 'Large': 1717},
 {'Small': 4586, 'Large': 1722},
 {'Small': 4598, 'Large': 1719},
 {'Small': 4597, 'Large': 1723},
 {'Small': 4604, 'Large': 1720},
 {'Small': 4582, 'Large': 1720},
 {'Small': 4575, 'Large': 1715},
 {'Small': 4597, 'Large': 1725},
 {'Small': 4599, 'Large': 1721},
 {'Small': 4551, 'Large': 1715},
 {'Small': 4580, 'Large': 1718},
 {'Small': 4599, 'Large': 1725},
 {'Small': 4588, 'Large': 1718},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4590, 'Large': 1722},
 {'Small': 4588, 'Large': 1711},
 {'Small': 4569, 'Large': 1723},
 {'Small': 4579, 'Large': 1722},
 {'Small': 4595, 'Large': 1721},
 {'Small': 4594, 'Large': 1724},
 {'Small': 4595, 'Large': 1720},
 {'Small': 4591, 'Large': 1723},
 {'Small': 4594, 'Large': 1722},
 {'Small': 4591, 'Large': 1720},
 {'Small': 4604, 'Large': 1725},
 {'Small': 4565, 'Large': 1721},
 {'Small': 4556, 'Large': 1712},
 {'Small': 4587, 'Large': 1723},
 {'Small': 4604, 'Large': 1724},
 {'Small': 4607, 'Large': 1722},
 {'Small': 4600, 'Large': 1724},
 {'Small': 4584, 'Large': 1714},
 {'Small': 4576, 'Large': 1720},
 {'Small': 4606, 'Large': 1722},
 {'Small': 4596, 'Large': 1725},
 {'Small': 4591, 'Large': 1717},
 {'Small': 4574, 'Large': 1719},
 {'Small': 4608, 'Large': 1723},
 {'Small': 4588, 'Large': 1720},
 {'Small': 4605, 'Large': 1723},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4576, 'Large': 1717},
 {'Small': 4591, 'Large': 1723},
 {'Small': 4609, 'Large': 1723},
 {'Small': 4586, 'Large': 1721},
 {'Small': 4599, 'Large': 1725},
 {'Small': 4596, 'Large': 1723},
 {'Small': 4599, 'Large': 1724},
 {'Small': 4604, 'Large': 1724},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4584, 'Large': 1723},
 {'Small': 4604, 'Large': 1725},
 {'Small': 4588, 'Large': 1723},
 {'Small': 4612, 'Large': 1723},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4614, 'Large': 1724},
 {'Small': 4605, 'Large': 1724},
 {'Small': 4609, 'Large': 1724},
 {'Small': 4602, 'Large': 1724},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4602, 'Large': 1725},
 {'Small': 4609, 'Large': 1724},
 {'Small': 4607, 'Large': 1721},
 {'Small': 4601, 'Large': 1723},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4603, 'Large': 1722},
 {'Small': 4608, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4611, 'Large': 1723},
 {'Small': 4580, 'Large': 1725},
 {'Small': 4579, 'Large': 1724},
 {'Small': 4570, 'Large': 1718},
 {'Small': 4604, 'Large': 1722},
 {'Small': 4579, 'Large': 1721},
 {'Small': 4593, 'Large': 1724},
 {'Small': 4609, 'Large': 1720},
 {'Small': 4613, 'Large': 1725},
 {'Small': 4610, 'Large': 1722},
 {'Small': 4555, 'Large': 1712},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4590, 'Large': 1721},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4583, 'Large': 1721},
 {'Small': 4613, 'Large': 1723},
 {'Small': 4606, 'Large': 1723},
 {'Small': 4604, 'Large': 1724},
 {'Small': 4610, 'Large': 1722},
 {'Small': 4606, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4605, 'Large': 1722},
 {'Small': 4606, 'Large': 1723},
 {'Small': 4579, 'Large': 1717},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4607, 'Large': 1725},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4578, 'Large': 1721},
 {'Small': 4605, 'Large': 1722},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4597, 'Large': 1723},
 {'Small': 4608, 'Large': 1725},
 {'Small': 4612, 'Large': 1724},
 {'Small': 4593, 'Large': 1720},
 {'Small': 4588, 'Large': 1722},
 {'Small': 4606, 'Large': 1723},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4609, 'Large': 1723},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4613, 'Large': 1723},
 {'Small': 4608, 'Large': 1723},
 {'Small': 4603, 'Large': 1724},
 {'Small': 4601, 'Large': 1724},
 {'Small': 4611, 'Large': 1723},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4591, 'Large': 1724},
 {'Small': 4571, 'Large': 1719},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4599, 'Large': 1724},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4608, 'Large': 1725},
 {'Small': 4608, 'Large': 1725},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4602, 'Large': 1722},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4607, 'Large': 1722},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4562, 'Large': 1718},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4605, 'Large': 1721},
 {'Small': 4603, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4605, 'Large': 1724},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4606, 'Large': 1724},
 {'Small': 4609, 'Large': 1724},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4599, 'Large': 1723},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4607, 'Large': 1725},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4609, 'Large': 1724},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4600, 'Large': 1724},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4609, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4612, 'Large': 1723},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4602, 'Large': 1725},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4606, 'Large': 1724},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4591, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4605, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4605, 'Large': 1725},
 {'Small': 4606, 'Large': 1724},
 {'Small': 4600, 'Large': 1724},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4606, 'Large': 1723},
 {'Small': 4600, 'Large': 1723},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4613, 'Large': 1725},
 {'Small': 4612, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4601, 'Large': 1723},
 {'Small': 4608, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4598, 'Large': 1724},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4597, 'Large': 1724},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4613, 'Large': 1725},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4599, 'Large': 1720},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4613, 'Large': 1724},
 {'Small': 4603, 'Large': 1723},
 {'Small': 4612, 'Large': 1724},
 {'Small': 4602, 'Large': 1724},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4583, 'Large': 1725},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4608, 'Large': 1723},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4605, 'Large': 1724},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4595, 'Large': 1721},
 {'Small': 4609, 'Large': 1724},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4609, 'Large': 1724},
 {'Small': 4612, 'Large': 1724},
 {'Small': 4606, 'Large': 1722},
 {'Small': 4611, 'Large': 1722},
 {'Small': 4609, 'Large': 1723},
 {'Small': 4585, 'Large': 1724},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4589, 'Large': 1720},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4567, 'Large': 1720},
 {'Small': 4602, 'Large': 1724},
 {'Small': 4589, 'Large': 1717},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4604, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4606, 'Large': 1723},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4605, 'Large': 1725},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4602, 'Large': 1724},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4552, 'Large': 1719},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4575, 'Large': 1720},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4609, 'Large': 1724},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4612, 'Large': 1725},
 {'Small': 4594, 'Large': 1720},
 {'Small': 4597, 'Large': 1720},
 {'Small': 4612, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4600, 'Large': 1723},
 {'Small': 4612, 'Large': 1724},
 {'Small': 4605, 'Large': 1725},
 {'Small': 4612, 'Large': 1724},
 {'Small': 4593, 'Large': 1723},
 {'Small': 4605, 'Large': 1723},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4609, 'Large': 1723},
 {'Small': 4601, 'Large': 1724},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4596, 'Large': 1724},
 {'Small': 4607, 'Large': 1723},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4589, 'Large': 1721},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4598, 'Large': 1723},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4603, 'Large': 1725},
 {'Small': 4607, 'Large': 1725},
 {'Small': 4592, 'Large': 1721},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4556, 'Large': 1715},
 {'Small': 4607, 'Large': 1723},
 {'Small': 4572, 'Large': 1717},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4592, 'Large': 1722},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4602, 'Large': 1721},
 {'Small': 4603, 'Large': 1721},
 {'Small': 4600, 'Large': 1720},
 {'Small': 4601, 'Large': 1717},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4611, 'Large': 1724},
 {'Small': 4603, 'Large': 1725},
 {'Small': 4603, 'Large': 1724},
 {'Small': 4612, 'Large': 1724},
 {'Small': 4578, 'Large': 1721},
 {'Small': 4603, 'Large': 1725},
 {'Small': 4593, 'Large': 1725},
 {'Small': 4598, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4596, 'Large': 1719},
 {'Small': 4613, 'Large': 1722},
 {'Small': 4599, 'Large': 1721},
 {'Small': 4592, 'Large': 1720},
 {'Small': 4597, 'Large': 1722},
 {'Small': 4536, 'Large': 1715},
 {'Small': 4605, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4608, 'Large': 1724},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4602, 'Large': 1725},
 {'Small': 4608, 'Large': 1723},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4583, 'Large': 1722},
 {'Small': 4608, 'Large': 1725},
 {'Small': 4594, 'Large': 1721},
 {'Small': 4576, 'Large': 1720},
 {'Small': 4591, 'Large': 1722},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4609, 'Large': 1725},
 {'Small': 4606, 'Large': 1722},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4610, 'Large': 1723},
 {'Small': 4605, 'Large': 1725},
 {'Small': 4607, 'Large': 1725},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4606, 'Large': 1725},
 {'Small': 4606, 'Large': 1723},
 {'Small': 4594, 'Large': 1724},
 {'Small': 4600, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4607, 'Large': 1724},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4608, 'Large': 1725},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4595, 'Large': 1723},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4610, 'Large': 1725},
 {'Small': 4611, 'Large': 1725},
 {'Small': 4610, 'Large': 1724},
 {'Small': 4586, 'Large': 1722},
 {'Small': 4597, 'Large': 1725},
 {'Small': 4607, 'Large': 1725},
 {'Small': 4611, 'Large': 1724},

In [16]:
print(type_count)

[('Small', 4614), ('Large', 1725)]

In [17]:
num_item = len(train_df['item_id'].unique())
num_user = len(train_df['user_id'].unique())
num_type = len(key_type)
print('items number : ',num_item)
print('users number : ',num_user)
print('user types : ',key_type)

items number :  915
users number :  6339
user types :  ['Small', 'Large']

In [18]:
dict_args["num_type"] = len(key_type)

In [19]:
user_type_list = [] #preprocessing to be sure that user types are really the right ones armielle 
for u in range(num_user):
    gl = user_idd_type_list[u]
    tmp = []
    for g in gl:
        if g in key_type:
            tmp.append(g)
    user_type_list.append(tmp)

print(len(user_type_list))

6339

In [20]:
# genreate user_type matrix
user_type = np.zeros((num_user, num_type))
for u in range(num_user):
    gl = user_type_list[u]
    for k in range(num_type):
        if key_type[k] in gl:
            user_type[u, k] = 1.0

In [21]:
len(user_type_list)

6339

In [22]:
print('*' * 50)
print('number of positive feedback: ' + str(len(train_df)))
print('estimated number of training samples: ' + str(neg * len(train_df)))
print('*' * 50)

**************************************************
number of positive feedback: 40354
estimated number of training samples: 201770
**************************************************

In [23]:
key_type

['Small', 'Large']

In [24]:
type_count

[('Small', 4614), ('Large', 1725)]

In [25]:
type_count = dict(type_count)

In [26]:
type_count_mean_reciprocal = []
for k in key_type:
    type_count_mean_reciprocal.append(1.0 / type_count[k])
type_count_mean_reciprocal = (np.array(type_count_mean_reciprocal)).reshape((num_type, 1))
type_error_weight = np.dot(user_type, type_count_mean_reciprocal)

In [27]:
# generate user_type matrix
type_user_indicator = np.zeros((num_type, num_user))

for k in range(num_type):
    type_user_indicator[k,:] = type_user_vector[key_type[k]]

In [28]:
precision = np.zeros(4)
recall = np.zeros(4)
f1 = np.zeros(4)
ndcg = np.zeros(4)
RSP = np.zeros(4)
REO = np.zeros(4)

precision

array([0., 0., 0., 0.])

In [29]:
len(user_type_list)

6339

In [ ]:
#tf.compat.v1.disable_eager_execution()

for i in range(n):
    #with tf.compat.v1.Session() as sess:
    with tf.Session() as sess:
        fairadvbpr = FairAdvBPR(sess, dict_args, train_df, test_df, user_type, type_error_weight, key_type, user_type_list, item_type_count)
        [prec_one, rec_one, f_one, ndcg_one, Rec] = fairadvbpr.run()

**********fairAdvBPR**********
INFO:tensorflow:Restoring parameters from ./modcloth/BPR_check_points\check_point.ckpt-20
Training // Epoch 1 //  Total r_cost = 5047316.12256  Total s_cost = 327312.91584  Total s_mean = -7.60876  Total s_std = 182.78925  Total a_cost = 0.00000 Training time : 26670 ms negative Sampling time : 12739 ms negative samples : 201770
precision_1	[0.0358101],	||	 precision_5	[0.0285850],	||	 precision_10	[0.0245307],	||	 precision_15	[0.0223589]
recall_1   	[0.0161647],	||	 recall_5   	[0.0653450],	||	 recall_10   	[0.1134043],	||	 recall_15   	[0.1580776]
f_measure_1	[0.0222746],	||	 f_measure_5	[0.0397718],	||	 f_measure_10	[0.0403362],	||	 f_measure_15	[0.0391766]
ndcg_1     	[0.0358101],	||	 ndcg_5     	[0.0538884],	||	 ndcg_10     	[0.0676796],	||	 ndcg_15     	[0.0793029]
Metrics for user type	 Small
precision_1	[0.0424794],	||	 precision_5	[0.0337668],	||	 precision_10	[0.0292805],	||	 precision_15	[0.0265135]
recall_1	[0.0169771],	||	 recall_5	[0.0672811],	||	 recall_10	[0.1191664],	||	 recall_15	[0.1640668]
ndcg_1	[0.0424794],	||	 ndcg_5	[0.0593588],	||	 ndcg_10	[0.0737754],	||	 ndcg_15	[0.0852643]
AUC per user type	[0.8091787]
Metrics for user type	 Large
precision_1	[0.0179710],	||	 precision_5	[0.0147246],	||	 precision_10	[0.0118261],	||	 precision_15	[0.0112464]
recall_1	[0.0139917],	||	 recall_5	[0.0601663],	||	 recall_10	[0.0979920],	||	 recall_15	[0.1420578]
ndcg_1	[0.0179710],	||	 ndcg_5	[0.0392564],	||	 ndcg_10	[0.0513745],	||	 ndcg_15	[0.0633574]
AUC per user type	[0.8064226]
AUC global is:  0.8084286721391423
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9
boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23
boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44
boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58
boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78
boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93
boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102
boucle adversarial fin
boucle adversarial debut-- num batch  103

boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116
boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137
boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151
boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171
boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185
boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
Training // Epoch 2 //  Total r_cost = 111579.95923  Total s_cost = 621.38294  Total s_mean = -0.01032  Total s_std = 197.86663  Total a_cost = 25.25510 Training time : 413327 ms negative Sampling time : 18180 ms negative samples : 201770
precision_1	[0.0400694],	||	 precision_5	[0.0306357],	||	 precision_10	[0.0268812],	||	 precision_15	[0.0247147]
recall_1   	[0.0201408],	||	 recall_5   	[0.0775216],	||	 recall_10   	[0.1389464],	||	 recall_15   	[0.1954406]
f_measure_1	[0.0268070],	||	 f_measure_5	[0.0439162],	||	 f_measure_10	[0.0450474],	||	 f_measure_15	[0.0438805]
ndcg_1     	[0.0400694],	||	 ndcg_5     	[0.0618900],	||	 ndcg_10     	[0.0800170],	||	 ndcg_15     	[0.0947592]
Metrics for user type	 Small
precision_1	[0.0463806],	||	 precision_5	[0.0345037],	||	 precision_10	[0.0309710],	||	 precision_15	[0.0285941]
recall_1	[0.0203084],	||	 recall_5	[0.0736081],	||	 recall_10	[0.1388280],	||	 recall_15	[0.1979877]
ndcg_1	[0.0463806],	||	 ndcg_5	[0.0642644],	||	 ndcg_10	[0.0831132],	||	 ndcg_15	[0.0983793]
AUC per user type	[0.8375121]
Metrics for user type	 Large
precision_1	[0.0231884],	||	 precision_5	[0.0202899],	||	 precision_10	[0.0159420],	||	 precision_15	[0.0143382]
recall_1	[0.0196922],	||	 recall_5	[0.0879896],	||	 recall_10	[0.1392633],	||	 recall_15	[0.1886279]
ndcg_1	[0.0231884],	||	 ndcg_5	[0.0555390],	||	 ndcg_10	[0.0717353],	||	 ndcg_15	[0.0850762]
AUC per user type	[0.8385379]
AUC global is:  0.8377912303896289
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9

boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23
boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44
boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58
boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78
boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93
boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102
boucle adversarial fin
boucle adversarial debut-- num batch  103
boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116
boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137

boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151
boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171
boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185
boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
Training // Epoch 3 //  Total r_cost = 96164.39655  Total s_cost = 87.61936  Total s_mean = -0.00371  Total s_std = 197.89646  Total a_cost = 25.58707 Training time : 370521 ms negative Sampling time : 23196 ms negative samples : 201770
precision_1	[0.0399117],	||	 precision_5	[0.0304464],	||	 precision_10	[0.0267550],	||	 precision_15	[0.0241994]
recall_1   	[0.0201687],	||	 recall_5   	[0.0749367],	||	 recall_10   	[0.1372745],	||	 recall_15   	[0.1912255]
f_measure_1	[0.0267963],	||	 f_measure_5	[0.0433002],	||	 f_measure_10	[0.0447819],	||	 f_measure_15	[0.0429620]
ndcg_1     	[0.0399117],	||	 ndcg_5     	[0.0609900],	||	 ndcg_10     	[0.0793249],	||	 ndcg_15     	[0.0932141]
Metrics for user type	 Small
precision_1	[0.0459471],	||	 precision_5	[0.0347638],	||	 precision_10	[0.0309926],	||	 precision_15	[0.0281896]
recall_1	[0.0201301],	||	 recall_5	[0.0721910],	||	 recall_10	[0.1381401],	||	 recall_15	[0.1964281]
ndcg_1	[0.0459471],	||	 ndcg_5	[0.0637613],	||	 ndcg_10	[0.0826019],	||	 ndcg_15	[0.0974025]
AUC per user type	[0.8386816]
Metrics for user type	 Large
precision_1	[0.0237681],	||	 precision_5	[0.0188986],	||	 precision_10	[0.0154203],	||	 precision_15	[0.0135266]
recall_1	[0.0202719],	||	 recall_5	[0.0822809],	||	 recall_10	[0.1349591],	||	 recall_15	[0.1773097]
ndcg_1	[0.0237681],	||	 ndcg_5	[0.0535773],	||	 ndcg_10	[0.0705594],	||	 ndcg_15	[0.0820111]
AUC per user type	[0.8401205]
AUC global is:  0.8390731626021647
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9
boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23
boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44

boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58
boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78
boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93
boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102
boucle adversarial fin
boucle adversarial debut-- num batch  103
boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116
boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137
boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151
boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171

boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185
boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
Training // Epoch 4 //  Total r_cost = 94053.95639  Total s_cost = 96.67075  Total s_mean = -0.00182  Total s_std = 197.89921  Total a_cost = 25.61134 Training time : 12662955 ms negative Sampling time : 24329 ms negative samples : 201770
precision_1	[0.0400694],	||	 precision_5	[0.0318978],	||	 precision_10	[0.0267550],	||	 precision_15	[0.0242625]
recall_1   	[0.0203766],	||	 recall_5   	[0.0829476],	||	 recall_10   	[0.1385220],	||	 recall_15   	[0.1899533]
f_measure_1	[0.0270151],	||	 f_measure_5	[0.0460766],	||	 f_measure_10	[0.0448478],	||	 f_measure_15	[0.0430290]
ndcg_1     	[0.0400694],	||	 ndcg_5     	[0.0647348],	||	 ndcg_10     	[0.0807805],	||	 ndcg_15     	[0.0940962]
Metrics for user type	 Small
precision_1	[0.0461638],	||	 precision_5	[0.0369311],	||	 precision_10	[0.0310577],	||	 precision_15	[0.0281462]
recall_1	[0.0204157],	||	 recall_5	[0.0836973],	||	 recall_10	[0.1397435],	||	 recall_15	[0.1925475]
ndcg_1	[0.0461638],	||	 ndcg_5	[0.0692811],	||	 ndcg_10	[0.0847566],	||	 ndcg_15	[0.0982460]
AUC per user type	[0.8390699]
Metrics for user type	 Large
precision_1	[0.0237681],	||	 precision_5	[0.0184348],	||	 precision_10	[0.0152464],	||	 precision_15	[0.0138744]
recall_1	[0.0202719],	||	 recall_5	[0.0809421],	||	 recall_10	[0.1352549],	||	 recall_15	[0.1830143]
ndcg_1	[0.0237681],	||	 ndcg_5	[0.0525744],	||	 ndcg_10	[0.0701454],	||	 ndcg_15	[0.0829962]
AUC per user type	[0.8407565]
AUC global is:  0.8395288806840986
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9
boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23
boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44
boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58
boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78

boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93
boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102
boucle adversarial fin
boucle adversarial debut-- num batch  103
boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116
boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137
boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151
boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171
boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185
boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
Training // Epoch 5 //  Total r_cost = 93488.93816  Total s_cost = 102.78612  Total s_mean = -0.00205  Total s_std = 197.89948  Total a_cost = 25.61693 Training time : 378962 ms negative Sampling time : 24918 ms negative samples : 201770
precision_1	[0.0403849],	||	 precision_5	[0.0312352],	||	 precision_10	[0.0268181],	||	 precision_15	[0.0240522]
recall_1   	[0.0202919],	||	 recall_5   	[0.0785875],	||	 recall_10   	[0.1358296],	||	 recall_15   	[0.1864286]
f_measure_1	[0.0270115],	||	 f_measure_5	[0.0447029],	||	 f_measure_10	[0.0447924],	||	 f_measure_15	[0.0426073]
ndcg_1     	[0.0403849],	||	 ndcg_5     	[0.0630390],	||	 ndcg_10     	[0.0799225],	||	 ndcg_15     	[0.0929359]

Metrics for user type	 Small
precision_1	[0.0465973],	||	 precision_5	[0.0364543],	||	 precision_10	[0.0315778],	||	 precision_15	[0.0280740]
recall_1	[0.0202994],	||	 recall_5	[0.0795319],	||	 recall_10	[0.1412487],	||	 recall_15	[0.1913549]
ndcg_1	[0.0465973],	||	 ndcg_5	[0.0677687],	||	 ndcg_10	[0.0853481],	||	 ndcg_15	[0.0980199]
AUC per user type	[0.8394103]
Metrics for user type	 Large
precision_1	[0.0237681],	||	 precision_5	[0.0172754],	||	 precision_10	[0.0140870],	||	 precision_15	[0.0132947]
recall_1	[0.0202719],	||	 recall_5	[0.0760613],	||	 recall_10	[0.1213346],	||	 recall_15	[0.1732517]
ndcg_1	[0.0237681],	||	 ndcg_5	[0.0503881],	||	 ndcg_10	[0.0654102],	||	 ndcg_15	[0.0793376]
AUC per user type	[0.8401084]
AUC global is:  0.8396002662578665
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9
boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23
boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44
boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58
boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78
boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93
boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102
boucle adversarial fin
boucle adversarial debut-- num batch  103
boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116

boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137
boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151
boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171
boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185
boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
Training // Epoch 6 //  Total r_cost = 93363.31921  Total s_cost = 100.10229  Total s_mean = -0.00139  Total s_std = 197.89950  Total a_cost = 25.61706 Training time : 388599 ms negative Sampling time : 24963 ms negative samples : 201770
precision_1	[0.0402272],	||	 precision_5	[0.0325603],	||	 precision_10	[0.0272914],	||	 precision_15	[0.0240311]
recall_1   	[0.0203053],	||	 recall_5   	[0.0840466],	||	 recall_10   	[0.1392273],	||	 recall_15   	[0.1875480]
f_measure_1	[0.0269880],	||	 f_measure_5	[0.0469369],	||	 f_measure_10	[0.0456370],	||	 f_measure_15	[0.0426034]
ndcg_1     	[0.0402272],	||	 ndcg_5     	[0.0653609],	||	 ndcg_10     	[0.0811802],	||	 ndcg_15     	[0.0935012]
Metrics for user type	 Small
precision_1	[0.0463806],	||	 precision_5	[0.0381014],	||	 precision_10	[0.0317512],	||	 precision_15	[0.0278861]
recall_1	[0.0203178],	||	 recall_5	[0.0864637],	||	 recall_10	[0.1410345],	||	 recall_15	[0.1902058]
ndcg_1	[0.0463806],	||	 ndcg_5	[0.0707229],	||	 ndcg_10	[0.0857664],	||	 ndcg_15	[0.0980988]
AUC per user type	[0.8389560]
Metrics for user type	 Large
precision_1	[0.0237681],	||	 precision_5	[0.0177391],	||	 precision_10	[0.0153623],	||	 precision_15	[0.0137198]
recall_1	[0.0202719],	||	 recall_5	[0.0775815],	||	 recall_10	[0.1343934],	||	 recall_15	[0.1804388]
ndcg_1	[0.0237681],	||	 ndcg_5	[0.0510187],	||	 ndcg_10	[0.0689130],	||	 ndcg_15	[0.0812035]
AUC per user type	[0.8410849]
AUC global is:  0.8395353582342711
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9
boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23

boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44
boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58
boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78
boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93
boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102
boucle adversarial fin
boucle adversarial debut-- num batch  103
boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116
boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137
boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151

boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171
boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185
boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
Training // Epoch 7 //  Total r_cost = 93567.84239  Total s_cost = 104.34937  Total s_mean = -0.00164  Total s_std = 197.89839  Total a_cost = 25.62188 Training time : 396675 ms negative Sampling time : 23165 ms negative samples : 201770
precision_1	[0.0403849],	||	 precision_5	[0.0318347],	||	 precision_10	[0.0268339],	||	 precision_15	[0.0247989]
recall_1   	[0.0202617],	||	 recall_5   	[0.0806881],	||	 recall_10   	[0.1377784],	||	 recall_15   	[0.1973311]
f_measure_1	[0.0269848],	||	 f_measure_5	[0.0456562],	||	 f_measure_10	[0.0449192],	||	 f_measure_15	[0.0440606]
ndcg_1     	[0.0403849],	||	 ndcg_5     	[0.0641779],	||	 ndcg_10     	[0.0804282],	||	 ndcg_15     	[0.0959194]
Metrics for user type	 Small
precision_1	[0.0465973],	||	 precision_5	[0.0368010],	||	 precision_10	[0.0314694],	||	 precision_15	[0.0288831]
recall_1	[0.0202579],	||	 recall_5	[0.0808439],	||	 recall_10	[0.1421985],	||	 recall_15	[0.2030407]
ndcg_1	[0.0465973],	||	 ndcg_5	[0.0684451],	||	 ndcg_10	[0.0853226],	||	 ndcg_15	[0.1009454]
AUC per user type	[0.8395239]
Metrics for user type	 Large
precision_1	[0.0237681],	||	 precision_5	[0.0185507],	||	 precision_10	[0.0144348],	||	 precision_15	[0.0138744]
recall_1	[0.0202719],	||	 recall_5	[0.0802713],	||	 recall_10	[0.1259554],	||	 recall_15	[0.1820592]
ndcg_1	[0.0237681],	||	 ndcg_5	[0.0527641],	||	 ndcg_10	[0.0673368],	||	 ndcg_15	[0.0824762]
AUC per user type	[0.8406754]
AUC global is:  0.8398372776134622
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9
boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23
boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44
boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58

boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78
boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93
boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102
boucle adversarial fin
boucle adversarial debut-- num batch  103
boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116
boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137
boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151
boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171
boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185

boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
Training // Epoch 8 //  Total r_cost = 93438.87857  Total s_cost = 104.19465  Total s_mean = -0.00119  Total s_std = 197.89880  Total a_cost = 25.62203 Training time : 404964 ms negative Sampling time : 19388 ms negative samples : 201770
precision_1	[0.0400694],	||	 precision_5	[0.0313614],	||	 precision_10	[0.0269128],	||	 precision_15	[0.0243677]
recall_1   	[0.0202172],	||	 recall_5   	[0.0806339],	||	 recall_10   	[0.1389478],	||	 recall_15   	[0.1904886]
f_measure_1	[0.0268747],	||	 f_measure_5	[0.0451589],	||	 f_measure_10	[0.0450917],	||	 f_measure_15	[0.0432081]
ndcg_1     	[0.0400694],	||	 ndcg_5     	[0.0636031],	||	 ndcg_10     	[0.0805896],	||	 ndcg_15     	[0.0939208]
Metrics for user type	 Small
precision_1	[0.0461638],	||	 precision_5	[0.0364109],	||	 precision_10	[0.0315128],	||	 precision_15	[0.0283341]
recall_1	[0.0201968],	||	 recall_5	[0.0817167],	||	 recall_10	[0.1425094],	||	 recall_15	[0.1942076]
ndcg_1	[0.0461638],	||	 ndcg_5	[0.0681958],	||	 ndcg_10	[0.0853019],	||	 ndcg_15	[0.0984989]
AUC per user type	[0.8392754]
Metrics for user type	 Large
precision_1	[0.0237681],	||	 precision_5	[0.0178551],	||	 precision_10	[0.0146087],	||	 precision_15	[0.0137585]
recall_1	[0.0202719],	||	 recall_5	[0.0777376],	||	 recall_10	[0.1294210],	||	 recall_15	[0.1805409]
ndcg_1	[0.0237681],	||	 ndcg_5	[0.0513187],	||	 ndcg_10	[0.0679851],	||	 ndcg_15	[0.0816752]
AUC per user type	[0.8413356]
AUC global is:  0.8398360337287099
boucle adversarial debut-- num batch  0
boucle adversarial fin
boucle adversarial debut-- num batch  1
boucle adversarial fin
boucle adversarial debut-- num batch  2
boucle adversarial fin
boucle adversarial debut-- num batch  3
boucle adversarial fin
boucle adversarial debut-- num batch  4
boucle adversarial fin
boucle adversarial debut-- num batch  5
boucle adversarial fin
boucle adversarial debut-- num batch  6
boucle adversarial fin
boucle adversarial debut-- num batch  7
boucle adversarial fin
boucle adversarial debut-- num batch  8
boucle adversarial fin
boucle adversarial debut-- num batch  9
boucle adversarial fin
boucle adversarial debut-- num batch  10
boucle adversarial fin
boucle adversarial debut-- num batch  11
boucle adversarial fin
boucle adversarial debut-- num batch  12
boucle adversarial fin
boucle adversarial debut-- num batch  13
boucle adversarial fin
boucle adversarial debut-- num batch  14
boucle adversarial fin
boucle adversarial debut-- num batch  15
boucle adversarial fin
boucle adversarial debut-- num batch  16
boucle adversarial fin
boucle adversarial debut-- num batch  17
boucle adversarial fin
boucle adversarial debut-- num batch  18
boucle adversarial fin
boucle adversarial debut-- num batch  19
boucle adversarial fin
boucle adversarial debut-- num batch  20
boucle adversarial fin
boucle adversarial debut-- num batch  21
boucle adversarial fin
boucle adversarial debut-- num batch  22
boucle adversarial fin
boucle adversarial debut-- num batch  23
boucle adversarial fin
boucle adversarial debut-- num batch  24
boucle adversarial fin
boucle adversarial debut-- num batch  25
boucle adversarial fin
boucle adversarial debut-- num batch  26
boucle adversarial fin
boucle adversarial debut-- num batch  27
boucle adversarial fin
boucle adversarial debut-- num batch  28
boucle adversarial fin
boucle adversarial debut-- num batch  29
boucle adversarial fin
boucle adversarial debut-- num batch  30
boucle adversarial fin
boucle adversarial debut-- num batch  31
boucle adversarial fin
boucle adversarial debut-- num batch  32
boucle adversarial fin
boucle adversarial debut-- num batch  33
boucle adversarial fin
boucle adversarial debut-- num batch  34
boucle adversarial fin
boucle adversarial debut-- num batch  35
boucle adversarial fin
boucle adversarial debut-- num batch  36
boucle adversarial fin
boucle adversarial debut-- num batch  37
boucle adversarial fin
boucle adversarial debut-- num batch  38
boucle adversarial fin
boucle adversarial debut-- num batch  39
boucle adversarial fin
boucle adversarial debut-- num batch  40
boucle adversarial fin
boucle adversarial debut-- num batch  41
boucle adversarial fin
boucle adversarial debut-- num batch  42
boucle adversarial fin
boucle adversarial debut-- num batch  43
boucle adversarial fin
boucle adversarial debut-- num batch  44
boucle adversarial fin
boucle adversarial debut-- num batch  45
boucle adversarial fin
boucle adversarial debut-- num batch  46
boucle adversarial fin
boucle adversarial debut-- num batch  47
boucle adversarial fin
boucle adversarial debut-- num batch  48
boucle adversarial fin
boucle adversarial debut-- num batch  49
boucle adversarial fin
boucle adversarial debut-- num batch  50
boucle adversarial fin
boucle adversarial debut-- num batch  51
boucle adversarial fin
boucle adversarial debut-- num batch  52
boucle adversarial fin
boucle adversarial debut-- num batch  53
boucle adversarial fin
boucle adversarial debut-- num batch  54
boucle adversarial fin
boucle adversarial debut-- num batch  55
boucle adversarial fin
boucle adversarial debut-- num batch  56
boucle adversarial fin
boucle adversarial debut-- num batch  57
boucle adversarial fin
boucle adversarial debut-- num batch  58
boucle adversarial fin
boucle adversarial debut-- num batch  59
boucle adversarial fin
boucle adversarial debut-- num batch  60
boucle adversarial fin
boucle adversarial debut-- num batch  61
boucle adversarial fin
boucle adversarial debut-- num batch  62
boucle adversarial fin
boucle adversarial debut-- num batch  63
boucle adversarial fin
boucle adversarial debut-- num batch  64
boucle adversarial fin
boucle adversarial debut-- num batch  65
boucle adversarial fin
boucle adversarial debut-- num batch  66
boucle adversarial fin
boucle adversarial debut-- num batch  67
boucle adversarial fin
boucle adversarial debut-- num batch  68
boucle adversarial fin
boucle adversarial debut-- num batch  69
boucle adversarial fin
boucle adversarial debut-- num batch  70
boucle adversarial fin
boucle adversarial debut-- num batch  71
boucle adversarial fin
boucle adversarial debut-- num batch  72
boucle adversarial fin
boucle adversarial debut-- num batch  73
boucle adversarial fin
boucle adversarial debut-- num batch  74
boucle adversarial fin
boucle adversarial debut-- num batch  75
boucle adversarial fin
boucle adversarial debut-- num batch  76
boucle adversarial fin
boucle adversarial debut-- num batch  77
boucle adversarial fin
boucle adversarial debut-- num batch  78
boucle adversarial fin
boucle adversarial debut-- num batch  79
boucle adversarial fin
boucle adversarial debut-- num batch  80
boucle adversarial fin
boucle adversarial debut-- num batch  81
boucle adversarial fin
boucle adversarial debut-- num batch  82
boucle adversarial fin
boucle adversarial debut-- num batch  83
boucle adversarial fin
boucle adversarial debut-- num batch  84
boucle adversarial fin
boucle adversarial debut-- num batch  85
boucle adversarial fin
boucle adversarial debut-- num batch  86
boucle adversarial fin
boucle adversarial debut-- num batch  87
boucle adversarial fin
boucle adversarial debut-- num batch  88
boucle adversarial fin
boucle adversarial debut-- num batch  89
boucle adversarial fin
boucle adversarial debut-- num batch  90
boucle adversarial fin
boucle adversarial debut-- num batch  91
boucle adversarial fin
boucle adversarial debut-- num batch  92
boucle adversarial fin
boucle adversarial debut-- num batch  93

boucle adversarial fin
boucle adversarial debut-- num batch  94
boucle adversarial fin
boucle adversarial debut-- num batch  95
boucle adversarial fin
boucle adversarial debut-- num batch  96
boucle adversarial fin
boucle adversarial debut-- num batch  97
boucle adversarial fin
boucle adversarial debut-- num batch  98
boucle adversarial fin
boucle adversarial debut-- num batch  99
boucle adversarial fin
boucle adversarial debut-- num batch  100
boucle adversarial fin
boucle adversarial debut-- num batch  101
boucle adversarial fin
boucle adversarial debut-- num batch  102
boucle adversarial fin
boucle adversarial debut-- num batch  103
boucle adversarial fin
boucle adversarial debut-- num batch  104
boucle adversarial fin
boucle adversarial debut-- num batch  105
boucle adversarial fin
boucle adversarial debut-- num batch  106
boucle adversarial fin
boucle adversarial debut-- num batch  107
boucle adversarial fin
boucle adversarial debut-- num batch  108
boucle adversarial fin
boucle adversarial debut-- num batch  109
boucle adversarial fin
boucle adversarial debut-- num batch  110
boucle adversarial fin
boucle adversarial debut-- num batch  111
boucle adversarial fin
boucle adversarial debut-- num batch  112
boucle adversarial fin
boucle adversarial debut-- num batch  113
boucle adversarial fin
boucle adversarial debut-- num batch  114
boucle adversarial fin
boucle adversarial debut-- num batch  115
boucle adversarial fin
boucle adversarial debut-- num batch  116
boucle adversarial fin
boucle adversarial debut-- num batch  117
boucle adversarial fin
boucle adversarial debut-- num batch  118
boucle adversarial fin
boucle adversarial debut-- num batch  119
boucle adversarial fin
boucle adversarial debut-- num batch  120
boucle adversarial fin
boucle adversarial debut-- num batch  121
boucle adversarial fin
boucle adversarial debut-- num batch  122
boucle adversarial fin
boucle adversarial debut-- num batch  123
boucle adversarial fin
boucle adversarial debut-- num batch  124
boucle adversarial fin
boucle adversarial debut-- num batch  125
boucle adversarial fin
boucle adversarial debut-- num batch  126
boucle adversarial fin
boucle adversarial debut-- num batch  127
boucle adversarial fin
boucle adversarial debut-- num batch  128
boucle adversarial fin
boucle adversarial debut-- num batch  129
boucle adversarial fin
boucle adversarial debut-- num batch  130
boucle adversarial fin
boucle adversarial debut-- num batch  131
boucle adversarial fin
boucle adversarial debut-- num batch  132
boucle adversarial fin
boucle adversarial debut-- num batch  133
boucle adversarial fin
boucle adversarial debut-- num batch  134
boucle adversarial fin
boucle adversarial debut-- num batch  135
boucle adversarial fin
boucle adversarial debut-- num batch  136
boucle adversarial fin
boucle adversarial debut-- num batch  137
boucle adversarial fin
boucle adversarial debut-- num batch  138
boucle adversarial fin
boucle adversarial debut-- num batch  139
boucle adversarial fin
boucle adversarial debut-- num batch  140
boucle adversarial fin
boucle adversarial debut-- num batch  141
boucle adversarial fin
boucle adversarial debut-- num batch  142
boucle adversarial fin
boucle adversarial debut-- num batch  143
boucle adversarial fin
boucle adversarial debut-- num batch  144
boucle adversarial fin
boucle adversarial debut-- num batch  145
boucle adversarial fin
boucle adversarial debut-- num batch  146
boucle adversarial fin
boucle adversarial debut-- num batch  147
boucle adversarial fin
boucle adversarial debut-- num batch  148
boucle adversarial fin
boucle adversarial debut-- num batch  149
boucle adversarial fin
boucle adversarial debut-- num batch  150
boucle adversarial fin
boucle adversarial debut-- num batch  151
boucle adversarial fin
boucle adversarial debut-- num batch  152
boucle adversarial fin
boucle adversarial debut-- num batch  153
boucle adversarial fin
boucle adversarial debut-- num batch  154
boucle adversarial fin
boucle adversarial debut-- num batch  155
boucle adversarial fin
boucle adversarial debut-- num batch  156
boucle adversarial fin
boucle adversarial debut-- num batch  157
boucle adversarial fin
boucle adversarial debut-- num batch  158
boucle adversarial fin
boucle adversarial debut-- num batch  159
boucle adversarial fin
boucle adversarial debut-- num batch  160
boucle adversarial fin
boucle adversarial debut-- num batch  161
boucle adversarial fin
boucle adversarial debut-- num batch  162
boucle adversarial fin
boucle adversarial debut-- num batch  163
boucle adversarial fin
boucle adversarial debut-- num batch  164
boucle adversarial fin
boucle adversarial debut-- num batch  165
boucle adversarial fin
boucle adversarial debut-- num batch  166
boucle adversarial fin
boucle adversarial debut-- num batch  167
boucle adversarial fin
boucle adversarial debut-- num batch  168
boucle adversarial fin
boucle adversarial debut-- num batch  169
boucle adversarial fin
boucle adversarial debut-- num batch  170
boucle adversarial fin
boucle adversarial debut-- num batch  171
boucle adversarial fin
boucle adversarial debut-- num batch  172
boucle adversarial fin
boucle adversarial debut-- num batch  173
boucle adversarial fin
boucle adversarial debut-- num batch  174
boucle adversarial fin
boucle adversarial debut-- num batch  175
boucle adversarial fin
boucle adversarial debut-- num batch  176
boucle adversarial fin
boucle adversarial debut-- num batch  177
boucle adversarial fin
boucle adversarial debut-- num batch  178
boucle adversarial fin
boucle adversarial debut-- num batch  179
boucle adversarial fin
boucle adversarial debut-- num batch  180
boucle adversarial fin
boucle adversarial debut-- num batch  181
boucle adversarial fin
boucle adversarial debut-- num batch  182
boucle adversarial fin
boucle adversarial debut-- num batch  183
boucle adversarial fin
boucle adversarial debut-- num batch  184
boucle adversarial fin
boucle adversarial debut-- num batch  185
boucle adversarial fin
boucle adversarial debut-- num batch  186
boucle adversarial fin
boucle adversarial debut-- num batch  187
boucle adversarial fin
boucle adversarial debut-- num batch  188
boucle adversarial fin
boucle adversarial debut-- num batch  189
boucle adversarial fin
boucle adversarial debut-- num batch  190
boucle adversarial fin
boucle adversarial debut-- num batch  191
boucle adversarial fin
boucle adversarial debut-- num batch  192
boucle adversarial fin
boucle adversarial debut-- num batch  193
boucle adversarial fin
boucle adversarial debut-- num batch  194
boucle adversarial fin
boucle adversarial debut-- num batch  195
boucle adversarial fin
boucle adversarial debut-- num batch  196
boucle adversarial fin
boucle adversarial debut-- num batch  197
boucle adversarial fin
Training // Epoch 9 //  Total r_cost = 93635.51114  Total s_cost = 103.45977  Total s_mean = -0.00167  Total s_std = 197.89806  Total a_cost = 25.62515 Training time : 423988 ms negative Sampling time : 27398 ms negative samples : 201770
precision_1	[0.0407004],	||	 precision_5	[0.0312352],	||	 precision_10	[0.0268970],	||	 precision_15	[0.0241363]
recall_1   	[0.0203095],	||	 recall_5   	[0.0780925],	||	 recall_10   	[0.1378527],	||	 recall_15   	[0.1895564]
f_measure_1	[0.0270974],	||	 f_measure_5	[0.0446225],	||	 f_measure_10	[0.0450116],	||	 f_measure_15	[0.0428203]
ndcg_1     	[0.0407004],	||	 ndcg_5     	[0.0627166],	||	 ndcg_10     	[0.0799233],	||	 ndcg_15     	[0.0931604]
Metrics for user type	 Small
precision_1	[0.0470308],	||	 precision_5	[0.0365843],	||	 precision_10	[0.0315345],	||	 precision_15	[0.0282185]
recall_1	[0.0203236],	||	 recall_5	[0.0798092],	||	 recall_10	[0.1421760],	||	 recall_15	[0.1957083]
ndcg_1	[0.0470308],	||	 ndcg_5	[0.0679264],	||	 ndcg_10	[0.0853005],	||	 ndcg_15	[0.0987941]
AUC per user type	[0.8389204]
Metrics for user type	 Large
precision_1	[0.0237681],	||	 precision_5	[0.0169275],	||	 precision_10	[0.0144928],	||	 precision_15	[0.0132174]
recall_1	[0.0202719],	||	 recall_5	[0.0735010],	||	 recall_10	[0.1262888],	||	 recall_15	[0.1731013]
ndcg_1	[0.0237681],	||	 ndcg_5	[0.0487816],	||	 ndcg_10	[0.0655404],	||	 ndcg_15	[0.0780913]
AUC per user type	[0.8406788]

In [ ]:
with open('Rec_' + dataname + '_fairAdvBPR.npy', "wb") as f:
    np.save(f, Rec)

In [ ]:
with open('Rec_' + dataname + '_fairAdvBPR.npy', "rb") as f:
    Recom = np.load(f)
Recom.shape

In [ ]:
[precision, recall, f_score, NDCG] = utility.test_model_all(Recom, test_df, train_df)

utility.test_model_per_user_type(Recom, test_df, train_df, user_type_list, key_type)
auc = utility.auc_per_user(Recom, test_df, train_df)
print("AUC global is: ", auc)

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from colour import Color

def savepdf_barplot_color_gradient(ymin = 0.5, ymax = 0.7, whis = 5, start_color='pink',end_color='blue',num_color=5, title='',axis_x = None, xlabel = '', axis_y1 = None, ylabel ='', plot_file = ''):
    
    fig = plt.figure()
    gs = fig.add_gridspec(1, 2, hspace=0, wspace=0)
    (ax1, ax2) = gs.subplots(sharex='col', sharey='row')
    
    red = Color(start_color)
    colors = list(red.range_to(Color(end_color), num_color))
    colors = [color.rgb for color in colors]
    
    X_axis = np.arange(len(axis_x))
    ax1.bar(X_axis, axis_y1, color=colors)
    ax1.hlines(y=axis_y1[0], xmin = 0, xmax = len(axis_x)-1, colors='black', linestyles='--', lw=1)
    
    plt.sca(ax1)
    plt.xticks(X_axis, axis_x, rotation =50)
    #plt.xlabel(xlabel)
    #fig.suptitle(title)
    plt.ylabel(ylabel, fontsize=18)
    plt.rcParams.update({'font.size': 13}) 
    plt.grid()
    
    plt.sca(ax2)
    ax2.boxplot(axis_y1, whis = whis)
    ax1.set_ylim(ymin, ymax)
    
    plt.tight_layout()
    plt.savefig(plot_file)

def savepdf_barplot_color_gradient2(start_color='pink',end_color='blue',num_color=20, title='',axis_x = None, xlabel = '', axis_y1 = None, ylabel ='', plot_file = ''):
    
    red = Color(start_color)
    colors = list(red.range_to(Color(end_color), num_color))
    colors = [color.rgb for color in colors]
    
    X_axis = np.arange(len(axis_x))
    plt.bar(X_axis, axis_y1, color=colors)
    
    
    plt.xticks(X_axis, axis_x, rotation =70)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid()
    
   # plt.tight_layout()
    plt.savefig(plot_file)