In [151]:
import tensorflow as tf
import time
import numpy as np
import os
import copy
import pickle
import argparse
import utilityarm as utility
import pandas as pd
from sklearn.metrics import *
import tensorflow.keras.backend as K

In [152]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior() 


class FairAdvBPR:

    def __init__(self, sess, dict_args, train_df, test_df, user_type, type_error_weight, key_type, user_type_list, item_type_count):
       
        self.dataname = dict_args['dataname']

        self.key_type = key_type
        self.user_type_list = user_type_list
        self.item_type_count = item_type_count
        self.layers = dict_args['layers']
        self.sess = sess
        
        self.num_cols = len(train_df['item_id'].unique())
        self.num_rows = len(train_df['user_id'].unique())

        self.hidden_neuron = dict_args['hidden_neuron']
        self.neg = dict_args['neg']
        self.batch_size = dict_args['batch_size']

        self.train_df = train_df
        self.vali_df = test_df
        self.num_train = len(self.train_df)
        self.num_vali = len(self.vali_df)

        self.train_epoch = dict_args['train_epoch']
        self.train_epoch_a = dict_args['train_epoch_a']
       # self.train_epoch_a_post = dict_args['train_epoch_a_post']
        self.train_epoch_all = dict_args['train_epoch_all']

        self.lr_r = dict_args['lr_r'] # learning rate
        self.lr_a = dict_args['lr_a'] # learning rate
        self.alpha = dict_args['alpha'] # learning rate
        self.optimizer_method = dict_args['optimizer_method']
        self.display_step = dict_args['display_step']
        
        self.type_error_weight = type_error_weight
        self.num_type = dict_args['num_type']
        
        self.user_type = user_type
        self.type_count_list = []
        for k in range(self.num_type):
            self.type_count_list.append(np.sum(user_type[:,k]))

        
        self.reg = dict_args['reg'] # regularization term trade-off
        self.reg_s = dict_args['reg_s']

        print('**********fairAdvBPR**********')
        #print(self.args)
        self._prepare_model()

    def loadmodel(self, saver, checkpoint_dir):
        ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
            ckpt_name = os.path.basename(ckpt.model_checkpoint_path)
            saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
            return True
        else:
            return False
        
    def run(self):
        init = tf.global_variables_initializer()
        self.sess.run(init)

        saver = tf.train.Saver([self.P, self.Q])
        self.loadmodel(saver, "./"+self.dataname+"/BPR_check_points")

        for epoch_itr in range(1, self.train_epoch + 1 + self.train_epoch_a+ self.train_epoch_all):
            self.train_model(epoch_itr)
            if epoch_itr % self.display_step == 0:
                self.test_model(epoch_itr)
        return self.make_records()

    def _prepare_model(self):
        with tf.name_scope("input_data"):
            self.user_input = tf.placeholder(tf.int32, shape=[None, 1], name="user_input")
            self.item_input_pos = tf.placeholder(tf.int32, shape=[None, 1], name="item_input_pos")
            self.item_input_neg = tf.placeholder(tf.int32, shape=[None, 1], name="item_input_neg")

            self.input_user_type = tf.placeholder(dtype=tf.float32, shape=[None, self.num_type]
                                                   , name="input_user_type")
            self.input_user_error_weight = tf.placeholder(dtype=tf.float32, shape=[None, 1]
                                                          , name="input_user_error_weight")

        with tf.variable_scope("BPR", reuse=tf.AUTO_REUSE):
            self.P = tf.get_variable(name="P",
                                     initializer=tf.truncated_normal(shape=[self.num_rows, self.hidden_neuron], mean=0,
                                                                     stddev=0.03), dtype=tf.float32)
            self.Q = tf.get_variable(name="Q",
                                     initializer=tf.truncated_normal(shape=[self.num_cols+1, self.hidden_neuron], mean=0,
                                                                     stddev=0.03), dtype=tf.float32)
        para_r = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="BPR")

        with tf.variable_scope("Adversarial", reuse=tf.AUTO_REUSE):
            num_layer = len(self.layers)
            adv_W = []
            adv_b = []
            for l in range(num_layer):
                if l == 0:
                    in_shape = 21
                else:
                    in_shape = self.layers[l - 1]
                adv_W.append(tf.get_variable(name="adv_W" + str(l),
                                             initializer=tf.truncated_normal(shape=[in_shape, self.layers[l]],
                                                                             mean=0, stddev=0.03), dtype=tf.float32))
                adv_b.append(tf.get_variable(name="adv_b" + str(l),
                                             initializer=tf.truncated_normal(shape=[1, self.layers[l]],
                                                                             mean=0, stddev=0.03), dtype=tf.float32))
            adv_W_out = tf.get_variable(name="adv_W_out",
                                        initializer=tf.truncated_normal(shape=[self.layers[-1], self.num_type],
                                                                        mean=0, stddev=0.03), dtype=tf.float32)

            adv_b_out = tf.get_variable(name="adv_b_out",
                                        initializer=tf.truncated_normal(shape=[1, self.num_type],
                                                                        mean=0, stddev=0.03), dtype=tf.float32)
        para_a = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="Adversarial")

        p = tf.reduce_sum(tf.nn.embedding_lookup(self.P, self.user_input), 1)
        q_neg = tf.reduce_sum(tf.nn.embedding_lookup(self.Q, self.item_input_neg), 1)
        q_pos = tf.reduce_sum(tf.nn.embedding_lookup(self.Q, self.item_input_pos), 1)

        predict_pos = tf.reduce_sum(p * q_pos, 1)
        predict_neg = tf.reduce_sum(p * q_neg, 1)

        r_cost1 = tf.reduce_sum(tf.nn.softplus(-(predict_pos - predict_neg)))
        r_cost2 = self.reg * 0.5 * (self.l2_norm(self.P) + self.l2_norm(self.Q))  # regularization term
#         pred = tf.matmul(self.P, tf.transpose(self.Q))
#         self.s_mean = tf.reduce_mean(pred, axis=1)
#         self.s_std = tf.keras.backend.std(pred, axis=1)
#         self.s_cost = tf.reduce_sum(tf.square(self.s_mean) + tf.square(self.s_std) - 2 * tf.log(self.s_std) - 1)#additional regularization
        self.s_mean = 0
        self.s_std = 0
        self.s_cost = 0
        
#        print('input_user_type ',self.input_user_type[:,1].shape)
#         usertype = self.input_user_type[]
#         print('shape',usertype.shape)
#         const_user_type1 = tf.reduce_sum(tf.nn.softplus(-(predict_pos - predict_neg) * self.input_user_type[:,0]))
#         const_user_type2 = tf.reduce_sum(tf.nn.softplus(-(predict_pos - predict_neg) * self.input_user_type[:,1]))
        
#        const = K.sqrt(K.square(const_user_type1 - const_user_type2))
        
#        self.r_cost = r_cost1 + r_cost2 + 1 * const + self.reg_s * 0.5 * self.s_cost
        self.r_cost = r_cost1 + r_cost2 
        
        print('shape q pos',q_pos.shape)
        print('shape p',p.shape)
        print('shape predict pos ', predict_pos.shape)
        
        adv_last = tf.reshape(predict_pos, [tf.shape(self.input_user_type)[0], 1])
        print('shape adv_last ', adv_last.shape)
        adv_last = tf.concat([adv_last, q_pos], 1)
        
        for l in range(num_layer):
            adv = tf.nn.relu(tf.matmul(adv_last, adv_W[l]) + adv_b[l])
            adv_last = adv
        self.adv_output = tf.nn.sigmoid(tf.matmul(adv_last, adv_W_out) + adv_b_out)
 #       self.a_cost = tf.reduce_sum(tf.square(self.adv_output - self.input_user_type) * self.input_user_error_weight)
        self.a_cost = tf.reduce_sum(- self.input_user_type * tf.math.log(self.adv_output))

    
                  

 #       self.all_cost = self.r_cost - self.alpha * self.a_cost  # the loss function
        self.all_cost = self.r_cost - 1000 * self.a_cost  # the loss function

        with tf.variable_scope("Optimizer", reuse=tf.AUTO_REUSE):
            self.r_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_r).minimize(self.r_cost, var_list=para_r)
            self.a_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_a).minimize(self.a_cost, var_list=para_a)
            self.all_optimizer = tf.train.AdamOptimizer(learning_rate=self.lr_r).minimize(self.all_cost, var_list=para_r)


    def train_model(self, itr):
        NS_start_time = time.time() * 1000.0
        epoch_r_cost = 0.0
        epoch_s_cost = 0.0
        epoch_s_mean = 0.0
        epoch_s_std = 0.0
        epoch_a_cost = 0.0
        accuracy_adv_pre_temp = 0.0
        accuracy_adv_post_temp = 0.0
        accuracy_adv_pre =[]
        accuracy_adv_post =[]
        self.accuracy_adv_pre = [0]
        epoch_adv_acc_pre = 0.0
        epoch_adv_acc_post = 0.0
        num_sample, user_list, item_pos_list, item_neg_list = utility.negative_sample(self.train_df, self.num_rows,
                                                                                      self.num_cols, self.neg)
        NS_end_time = time.time() * 1000.0

        start_time = time.time() * 1000.0
        num_batch = int(num_sample / float(self.batch_size)) + 1
        random_idx = np.random.permutation(num_sample)
        for i in range(num_batch):
            # get the indices of the current batch
            if i == num_batch - 1:
                batch_idx = random_idx[i * self.batch_size:]
            elif i < num_batch - 1:
                batch_idx = random_idx[(i * self.batch_size):((i + 1) * self.batch_size)]
            
            accuracy_adv_pre_temp = 0.0
            accuracy_adv_post_temp = 0.0
            # training of adversary
            if itr > self.train_epoch and itr < (self.train_epoch + self.train_epoch_a + 1):
                #random_idx_a = np.random.permutation(num_sample)
                #print("boucle adversarial debut-- num batch ",i)
                #for j in range(num_batch):
#                 if j == num_batch - 1:
#                 batch_idx_a = random_idx_a[j * self.batch_size:]
#                 elif j < num_batch - 1:
#                 batch_idx_a = random_idx_a[(j * self.batch_size):((j + 1) * self.batch_size)]
                user_idx_list = ((user_list[batch_idx, :]).reshape((len(batch_idx)))).tolist()
                _, tmp_a_cost, adv_output = self.sess.run(  # do the optimization by the minibatch
                        [self.a_optimizer, self.a_cost, self.adv_output],
                feed_dict={self.user_input: user_list[batch_idx, :],
                                   self.item_input_pos: item_pos_list[batch_idx, :],
                                   self.item_input_neg: item_neg_list[batch_idx, :],
                                   self.input_user_type: self.user_type[user_idx_list,:],
                                   self.input_user_error_weight: self.type_error_weight[user_idx_list,:]})
                epoch_a_cost += tmp_a_cost
                    
                g = tf.Graph()
                with g.as_default():
                    logits = adv_output
                      
                    labels = self.user_type[user_idx_list,:]
                      
                    acc, acc_op = tf.compat.v1.metrics.accuracy(labels, logits)
                    global_init = tf.compat.v1.global_variables_initializer()
                    local_init = tf.compat.v1.local_variables_initializer()
                sess = tf.compat.v1.Session(graph=g)
                sess.run([global_init, local_init])
                acc, acc_op = sess.run([acc, acc_op])
                    #print('post adversarial -- adversaire ready ',acc_op)
                accuracy_adv_pre_temp += acc_op
                sess.close()
                accuracy_adv_pre.append(accuracy_adv_pre_temp)
                print('post adversarial -- adversaire ready after one adv epoch training ',accuracy_adv_pre_temp)
                
                if itr == self.train_epoch + self.train_epoch_a:
                    self.accuracy_adv_pre.append(accuracy_adv_pre_temp)
                
            if itr > (self.train_epoch + self.train_epoch_a ):  
                
                user_idx_list = ((user_list[batch_idx, :]).reshape((len(batch_idx)))).tolist()
                _, tmp_r_cost = self.sess.run(  # do the optimization by the minibatch
                    [self.all_optimizer, self.all_cost],
                    feed_dict={self.user_input: user_list[batch_idx, :],
                               self.item_input_pos: item_pos_list[batch_idx, :],
                               self.item_input_neg: item_neg_list[batch_idx, :],
                               self.input_user_type: self.user_type[user_idx_list, :],
                               self.input_user_error_weight: self.type_error_weight[user_idx_list, :]})
                epoch_r_cost += tmp_r_cost
                #mesure perf adv post training of main model
#                 for j in range(num_batch):
#                     if j == num_batch - 1:
#                         batch_idx_a = random_idx_a[j * self.batch_size:]
#                     elif j < num_batch - 1:
#                         batch_idx_a = random_idx_a[(j * self.batch_size):((j + 1) * self.batch_size)]
            
             
                user_idx_list = ((user_list[batch_idx, :]).reshape((len(batch_idx)))).tolist()
#                 _,tmp_a_cost, adv_output_post = self.sess.run(  # do the optimization by the minibatch
#                          [self.a_optimizer, self.a_cost, self.adv_output], feed_dict={self.user_input: user_list[batch_idx, :],
#                                     self.item_input_pos: item_pos_list[batch_idx, :],
#                                     self.item_input_neg: item_neg_list[batch_idx, :],
#                                     self.input_user_type: self.user_type[user_idx_list,:],
#                                     self.input_user_error_weight: self.type_error_weight[user_idx_list,:]})
#                 epoch_a_cost += tmp_a_cost
                
                adv_output_post = self.sess.run(  # do the optimization by the minibatch
                        [ self.adv_output],
                feed_dict={self.user_input: user_list[batch_idx, :],
                                   self.item_input_pos: item_pos_list[batch_idx, :],
                                   self.item_input_neg: item_neg_list[batch_idx, :],
                                   self.input_user_type: self.user_type[user_idx_list,:],
                                   self.input_user_error_weight: self.type_error_weight[user_idx_list,:]})
                    
                g = tf.Graph()
                with g.as_default():
                    labels2 = self.user_type[user_idx_list,:] 
                    logits2 = adv_output_post                    
                    acc, acc_op = tf.compat.v1.metrics.accuracy(labels2, logits2[0])
                    global_init = tf.compat.v1.global_variables_initializer()
                    local_init = tf.compat.v1.local_variables_initializer()
                sess = tf.compat.v1.Session(graph=g)
                sess.run([global_init, local_init])
                acc, acc_op = sess.run([acc, acc_op])
                    #print('post main model training -- adversaire dejoue', acc_op)
                accuracy_adv_post_temp += acc_op
                sess.close()
                accuracy_adv_post.append(accuracy_adv_post_temp)
                print('post adversarial -- adversaire dejoue after one re-training of main model ',accuracy_adv_post_temp)
                
                
                print("boucle adversarial fin")
            else:
                user_idx_list = ((user_list[batch_idx, :]).reshape((len(batch_idx)))).tolist()
                _, tmp_r_cost = self.sess.run(  # do the optimization by the minibatch
                    [self.r_optimizer, self.r_cost],
                    feed_dict={self.user_input: user_list[batch_idx, :],
                               self.item_input_pos: item_pos_list[batch_idx, :],
                               self.item_input_neg: item_neg_list[batch_idx, :],
                               self.input_user_type: self.user_type[user_idx_list, :],
                               self.input_user_error_weight: self.type_error_weight[user_idx_list, :]})
                epoch_r_cost += tmp_r_cost
    
        epoch_a_cost /= num_batch
        epoch_adv_acc_pre = sum(accuracy_adv_pre)/num_batch
        epoch_adv_acc_post = sum(accuracy_adv_post)/num_batch
        epoch_adv_acc_pre_lastAdvIter = sum(self.accuracy_adv_pre)/num_batch
        
        
        filename = './const_IembfairAdvBPR_new_results/epoch'+ str(itr) +'_pre_' + self.dataname + '_accAdvpre.npy'
        os.makedirs(os.path.dirname(filename), exist_ok=True)           
        with open(filename, "wb") as f:
                np.save(f, epoch_adv_acc_pre) 
        filename1 = './const_IembfairAdvBPR_new_results/epoch'+ str(itr) +'_post_' + self.dataname + '_accAdvpost.npy'
        os.makedirs(os.path.dirname(filename1), exist_ok=True)           
        with open(filename1, "wb") as f:
                np.save(f, epoch_adv_acc_post) 
                
        if itr % self.display_step == 0:
            print ("Training //", "Epoch %d //" % itr, " Total r_cost = %.5f" % epoch_r_cost,
                   " Total a_cost = %.5f" % epoch_a_cost,
                   "total pre adversarial accuracy = %.5f" % epoch_adv_acc_pre,
                   "total pre adversarial accuracy = %.5f" % epoch_adv_acc_pre_lastAdvIter,
                   "total post adversarial accuracy = %.5f" % epoch_adv_acc_post,
                   "Training time : %d ms" % (time.time() * 1000.0 - start_time),
                   "negative Sampling time : %d ms" % (NS_end_time - NS_start_time),
                   "negative samples : %d" % (num_sample))
       
    def test_model(self, itr):  # calculate the cost and rmse of testing set in each epoch
        if itr % self.display_step == 0:
            start_time = time.time() * 1000.0
            P, Q = self.sess.run([self.P, self.Q])
            Rec = np.matmul(P, Q.T)

            [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
#             utility.ranking_analysis(Rec, self.vali_df, self.train_df, self.key_genre, self.item_genre_list,
#                                      self.user_genre_count)
            utility.test_model_per_user_type(Rec, self.vali_df, self.train_df, self.user_type_list, self.key_type)
            auc = utility.auc_per_user(Rec, self.vali_df, self.train_df)
            print("AUC global is: ", auc)
            
            filename = './const_IembfairAdvBPR_new_results/epoch'+ str(itr) +'_Rec_' + self.dataname + '_constfairAdvBPR.npy'
            os.makedirs(os.path.dirname(filename), exist_ok=True)           
            with open(filename, "wb") as f:
                np.save(f, Rec)
                

            

    def make_records(self):  # record all the results' details into files
        P, Q = self.sess.run([self.P, self.Q])
        Rec = np.matmul(P, Q.T)

        [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
        return precision, recall, f_score, NDCG, Rec

#     def test_model(self, itr):  # calculate the cost and rmse of testing set in each epoch
#         if itr % self.display_step == 0:
#             start_time = time.time() * 1000.0
#             P, Q = self.sess.run([self.P, self.Q])
#             Rec = np.matmul(P, Q.T)

#             [precision, recall, f_score, NDCG] = utility.test_model_all(Rec, self.vali_df, self.train_df)
# #             utility.ranking_analysis(Rec, self.vali_df, self.train_df, self.key_type, self.user_type_list,
# #                                      self.item_type_count)
#             utility.test_model_per_user_type(Rec, self.vali_df, self.train_df, self.user_type_list, self.key_type)
#             auc = utility.auc_per_user(Rec, self.vali_df, self.train_df)
#             print("AUC global is: ", auc)
#             print (
#                 "Testing //", "Epoch %d //" % itr,
#                 "Testing time : %d ms" % (time.time() * 1000.0 - start_time))
#             print("=" * 200)


    @staticmethod
    def l2_norm(tensor):
        return tf.reduce_sum(tf.square(tensor))

In [153]:

#optimizer_method = ['Adam', 'Adadelta', 'Adagrad', 'RMSProp', 'GradientDescent','Momentum'], default='Adam')


train_epoch = 5
train_epoch_a = 10 #default 20
train_epoch_all = 10
#train_epoch_a_post = 5
display_step = 1
lr_r = 0.01
lr_a = 0.005
reg = 0.1
reg_s = 30
alpha = 1000
optimizer_method = 'Adam'
hidden_neuron = 20
n = 1
neg = 5
batch_size = 1024
#layers = [50, 50, 50, 50]
layers = [64]
dataname = 'ml1m-6'

In [154]:
dict_args =  {"train_epoch": train_epoch,
              "train_epoch_a": train_epoch_a,
              "train_epoch_all": train_epoch_all,
             # "train_epoch_a_post": train_epoch_a_post,
            "display_step":display_step,
            "lr_r":lr_r,
            "lr_a":lr_a,
            "reg":reg,
            "reg_s":reg_s,
            "alpha":alpha,
            "optimizer_method":optimizer_method,
            "hidden_neuron":hidden_neuron,
            "n":n,
            "neg":neg,
            "batch_size":batch_size,
            "layers":layers,
            "dataname":dataname}
dict_args

{'train_epoch': 5,
 'train_epoch_a': 10,
 'train_epoch_all': 10,
 'display_step': 1,
 'lr_r': 0.01,
 'lr_a': 0.005,
 'reg': 0.1,
 'reg_s': 30,
 'alpha': 1000,
 'optimizer_method': 'Adam',
 'hidden_neuron': 20,
 'n': 1,
 'neg': 5,
 'batch_size': 1024,
 'layers': [64],
 'dataname': 'ml1m-6'}

In [155]:
with open('./training_df.pkl', 'rb') as f:
    train_df = pickle.load(f,encoding='latin1')

# with open('./' + dataname + '/valiing_df.pkl', 'rb') as f:
#     vali_df = pickle.load(f,encoding='latin1')  # for validation
    
with open('./testing_df.pkl', 'rb') as f:
    test_df = pickle.load(f,encoding='latin1')  # for validation
# vali_df = pickle.load(open('./' + dataname + '/testing_df.pkl'))  # for testing

with open('./key_type.pkl', 'rb') as f:
    key_type = pickle.load(f,encoding='latin1')
    
with open('./user_idd_type_list.pkl', 'rb') as f:
    user_idd_type_list = pickle.load(f,encoding='latin1')
    
with open('./type_user_vector.pkl', 'rb') as f:
    type_user_vector = pickle.load(f,encoding='latin1')

with open('./type_count.pkl', 'rb') as f:
    type_count = pickle.load(f,encoding='latin1')
    
with open('./item_type_count.pkl', 'rb') as f:
    item_type_count = pickle.load(f,encoding='latin1')

In [156]:
train_df.head(20)

    user_id  item_id  rating
0         1        1       3
1         2        2       1
2         3        3       2
3         4        4       1
4         6        6       2
5         7        7       5
6         8        8       3
7         9        9       3
8        10       10       2
9        11       11       5
10       14       14       3
11       15       15       3
12       16       16       5
13       18       18       4
14       19       19       2
15       21       21       4
16       22       22       4
17       18       23       2
18       23       24       4
19       25       26       5

In [157]:
train_df.shape

(80146, 3)

In [158]:
test_df.head(20)

    user_id  item_id  rating
0         0        0       3
1         5        5       4
2        12       12       5
3        13       13       3
4        17       17       2
5        20       20       4
6        24       25       2
7        30       31       4
8        35       35       1
9        40       40       4
10       41       41       2
11       42       43       5
12       43       44       5
13       44       45       5
14       45       46       5
15       46       47       5
16       47       48       3
17       54       55       4
18        6       59       3
19       41       61       4

In [159]:
test_df.shape

(19577, 3)

In [160]:
print(len(user_idd_type_list))

943

In [161]:
user_idd_type_list

[['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['M'],
 ['F'],
 ['F'],
 ['M'],
 ['M'],
 ['M'],
 ['F'],
 ['M'],
 ['F'],
 ['F'],
 ['M']]

In [162]:
print(type_user_vector['F'].shape)

(1, 943)

In [163]:
type_user_vector

{'M': array([[1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.,
         0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
         1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
         1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
         1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
         0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
         0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1.,
         1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
         0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1.,
         0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
         1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
         1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
         1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
         1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
         1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
         0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0.,
         0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
         0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
         1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0.,
         1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0.,
         1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
         1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
         1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
         1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
         1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
         1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
         1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
         0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
         0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
         1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0.,
         0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1.,
         0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
         1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
         0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
         1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
         0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
         1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
         0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
         1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
         1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0.,
         1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
         1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
         1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
         1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
         1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
         0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
         1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
         1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
         1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
         1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
         1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
         1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
         1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1.]]),
 'F': array([[0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
         1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
         1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
         1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
         1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
         0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1.,
         0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
         1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
         1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
         1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
         0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
         0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1.,
         0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
         0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
         0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
         1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
         1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
         1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
         1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
         0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
         1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
         0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1.,
         0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
         0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
         0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
         0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
         0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
         0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
         0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
         0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0.]])}

In [164]:
len(item_type_count)

1473

In [165]:
item_type_count

[{'M': 605, 'F': 247},
 {'M': 500, 'F': 206},
 {'M': 666, 'F': 270},
 {'M': 630, 'F': 249},
 {'M': 592, 'F': 257},
 {'M': 531, 'F': 251},
 {'M': 523, 'F': 240},
 {'M': 623, 'F': 251},
 {'M': 572, 'F': 231},
 {'M': 585, 'F': 232},
 {'M': 492, 'F': 212},
 {'M': 618, 'F': 248},
 {'M': 429, 'F': 217},
 {'M': 640, 'F': 261},
 {'M': 604, 'F': 256},
 {'M': 655, 'F': 254},
 {'M': 643, 'F': 247},
 {'M': 567, 'F': 220},
 {'M': 656, 'F': 267},
 {'M': 663, 'F': 271},
 {'M': 635, 'F': 254},
 {'M': 638, 'F': 252},
 {'M': 509, 'F': 236},
 {'M': 493, 'F': 204},
 {'M': 404, 'F': 177},
 {'M': 520, 'F': 231},
 {'M': 537, 'F': 226},
 {'M': 636, 'F': 260},
 {'M': 630, 'F': 250},
 {'M': 494, 'F': 221},
 {'M': 595, 'F': 249},
 {'M': 442, 'F': 201},
 {'M': 570, 'F': 244},
 {'M': 554, 'F': 212},
 {'M': 524, 'F': 227},
 {'M': 665, 'F': 272},
 {'M': 551, 'F': 232},
 {'M': 648, 'F': 262},
 {'M': 617, 'F': 260},
 {'M': 645, 'F': 266},
 {'M': 590, 'F': 231},
 {'M': 647, 'F': 270},
 {'M': 653, 'F': 270},
 {'M': 567, 'F': 239},
 {'M': 607, 'F': 266},
 {'M': 653, 'F': 271},
 {'M': 588, 'F': 246},
 {'M': 542, 'F': 234},
 {'M': 598, 'F': 229},
 {'M': 357, 'F': 172},
 {'M': 574, 'F': 237},
 {'M': 544, 'F': 224},
 {'M': 365, 'F': 177},
 {'M': 527, 'F': 216},
 {'M': 596, 'F': 260},
 {'M': 630, 'F': 260},
 {'M': 550, 'F': 209},
 {'M': 498, 'F': 199},
 {'M': 531, 'F': 245},
 {'M': 631, 'F': 255},
 {'M': 404, 'F': 157},
 {'M': 594, 'F': 255},
 {'M': 594, 'F': 248},
 {'M': 608, 'F': 261},
 {'M': 629, 'F': 256},
 {'M': 606, 'F': 264},
 {'M': 550, 'F': 217},
 {'M': 634, 'F': 259},
 {'M': 499, 'F': 201},
 {'M': 657, 'F': 268},
 {'M': 640, 'F': 250},
 {'M': 633, 'F': 259},
 {'M': 588, 'F': 228},
 {'M': 579, 'F': 236},
 {'M': 662, 'F': 265},
 {'M': 616, 'F': 258},
 {'M': 557, 'F': 253},
 {'M': 454, 'F': 180},
 {'M': 557, 'F': 244},
 {'M': 604, 'F': 253},
 {'M': 643, 'F': 263},
 {'M': 608, 'F': 256},
 {'M': 543, 'F': 239},
 {'M': 536, 'F': 195},
 {'M': 619, 'F': 257},
 {'M': 611, 'F': 259},
 {'M': 513, 'F': 203},
 {'M': 580, 'F': 250},
 {'M': 561, 'F': 243},
 {'M': 525, 'F': 194},
 {'M': 660, 'F': 270},
 {'M': 575, 'F': 241},
 {'M': 617, 'F': 239},
 {'M': 551, 'F': 242},
 {'M': 547, 'F': 248},
 {'M': 387, 'F': 158},
 {'M': 548, 'F': 237},
 {'M': 564, 'F': 250},
 {'M': 499, 'F': 201},
 {'M': 533, 'F': 220},
 {'M': 537, 'F': 217},
 {'M': 415, 'F': 199},
 {'M': 475, 'F': 227},
 {'M': 481, 'F': 200},
 {'M': 561, 'F': 225},
 {'M': 630, 'F': 260},
 {'M': 619, 'F': 259},
 {'M': 661, 'F': 266},
 {'M': 564, 'F': 237},
 {'M': 644, 'F': 269},
 {'M': 611, 'F': 241},
 {'M': 606, 'F': 258},
 {'M': 468, 'F': 228},
 {'M': 546, 'F': 231},
 {'M': 538, 'F': 238},
 {'M': 601, 'F': 246},
 {'M': 604, 'F': 263},
 {'M': 529, 'F': 212},
 {'M': 509, 'F': 225},
 {'M': 662, 'F': 264},
 {'M': 539, 'F': 230},
 {'M': 622, 'F': 261},
 {'M': 647, 'F': 253},
 {'M': 644, 'F': 267},
 {'M': 615, 'F': 235},
 {'M': 560, 'F': 240},
 {'M': 651, 'F': 267},
 {'M': 664, 'F': 270},
 {'M': 644, 'F': 269},
 {'M': 650, 'F': 270},
 {'M': 558, 'F': 226},
 {'M': 601, 'F': 233},
 {'M': 663, 'F': 268},
 {'M': 563, 'F': 227},
 {'M': 649, 'F': 260},
 {'M': 571, 'F': 228},
 {'M': 463, 'F': 208},
 {'M': 601, 'F': 247},
 {'M': 637, 'F': 263},
 {'M': 517, 'F': 223},
 {'M': 446, 'F': 205},
 {'M': 522, 'F': 243},
 {'M': 592, 'F': 242},
 {'M': 647, 'F': 256},
 {'M': 530, 'F': 209},
 {'M': 569, 'F': 260},
 {'M': 585, 'F': 256},
 {'M': 589, 'F': 256},
 {'M': 570, 'F': 241},
 {'M': 664, 'F': 270},
 {'M': 568, 'F': 254},
 {'M': 588, 'F': 242},
 {'M': 653, 'F': 270},
 {'M': 562, 'F': 231},
 {'M': 568, 'F': 236},
 {'M': 636, 'F': 255},
 {'M': 457, 'F': 215},
 {'M': 372, 'F': 165},
 {'M': 572, 'F': 253},
 {'M': 614, 'F': 250},
 {'M': 619, 'F': 253},
 {'M': 446, 'F': 202},
 {'M': 644, 'F': 267},
 {'M': 653, 'F': 269},
 {'M': 645, 'F': 267},
 {'M': 617, 'F': 261},
 {'M': 503, 'F': 203},
 {'M': 645, 'F': 265},
 {'M': 626, 'F': 257},
 {'M': 626, 'F': 267},
 {'M': 595, 'F': 258},
 {'M': 661, 'F': 272},
 {'M': 573, 'F': 245},
 {'M': 591, 'F': 228},
 {'M': 520, 'F': 229},
 {'M': 486, 'F': 206},
 {'M': 650, 'F': 240},
 {'M': 577, 'F': 223},
 {'M': 637, 'F': 241},
 {'M': 490, 'F': 215},
 {'M': 593, 'F': 256},
 {'M': 525, 'F': 237},
 {'M': 507, 'F': 237},
 {'M': 646, 'F': 266},
 {'M': 587, 'F': 246},
 {'M': 596, 'F': 253},
 {'M': 612, 'F': 250},
 {'M': 640, 'F': 266},
 {'M': 617, 'F': 253},
 {'M': 414, 'F': 181},
 {'M': 634, 'F': 256},
 {'M': 478, 'F': 205},
 {'M': 642, 'F': 265},
 {'M': 623, 'F': 262},
 {'M': 646, 'F': 260},
 {'M': 599, 'F': 255},
 {'M': 585, 'F': 240},
 {'M': 603, 'F': 260},
 {'M': 587, 'F': 259},
 {'M': 629, 'F': 262},
 {'M': 496, 'F': 209},
 {'M': 532, 'F': 228},
 {'M': 657, 'F': 267},
 {'M': 608, 'F': 246},
 {'M': 568, 'F': 233},
 {'M': 627, 'F': 254},
 {'M': 643, 'F': 262},
 {'M': 597, 'F': 252},
 {'M': 575, 'F': 254},
 {'M': 431, 'F': 205},
 {'M': 649, 'F': 271},
 {'M': 558, 'F': 239},
 {'M': 653, 'F': 261},
 {'M': 629, 'F': 262},
 {'M': 637, 'F': 267},
 {'M': 628, 'F': 262},
 {'M': 413, 'F': 209},
 {'M': 479, 'F': 235},
 {'M': 630, 'F': 262},
 {'M': 611, 'F': 261},
 {'M': 578, 'F': 231},
 {'M': 524, 'F': 218},
 {'M': 637, 'F': 264},
 {'M': 651, 'F': 257},
 {'M': 666, 'F': 271},
 {'M': 611, 'F': 252},
 {'M': 576, 'F': 231},
 {'M': 635, 'F': 258},
 {'M': 636, 'F': 257},
 {'M': 513, 'F': 230},
 {'M': 586, 'F': 253},
 {'M': 512, 'F': 224},
 {'M': 598, 'F': 243},
 {'M': 608, 'F': 260},
 {'M': 664, 'F': 270},
 {'M': 589, 'F': 254},
 {'M': 629, 'F': 262},
 {'M': 662, 'F': 271},
 {'M': 587, 'F': 249},
 {'M': 490, 'F': 224},
 {'M': 520, 'F': 222},
 {'M': 587, 'F': 246},
 {'M': 549, 'F': 231},
 {'M': 582, 'F': 246},
 {'M': 542, 'F': 229},
 {'M': 640, 'F': 258},
 {'M': 647, 'F': 266},
 {'M': 447, 'F': 203},
 {'M': 665, 'F': 271},
 {'M': 607, 'F': 262},
 {'M': 627, 'F': 263},
 {'M': 581, 'F': 230},
 {'M': 586, 'F': 255},
 {'M': 561, 'F': 255},
 {'M': 505, 'F': 209},
 {'M': 658, 'F': 268},
 {'M': 484, 'F': 231},
 {'M': 641, 'F': 243},
 {'M': 609, 'F': 262},
 {'M': 647, 'F': 260},
 {'M': 539, 'F': 245},
 {'M': 551, 'F': 243},
 {'M': 613, 'F': 259},
 {'M': 661, 'F': 268},
 {'M': 628, 'F': 246},
 {'M': 645, 'F': 266},
 {'M': 638, 'F': 268},
 {'M': 562, 'F': 249},
 {'M': 583, 'F': 248},
 {'M': 527, 'F': 245},
 {'M': 659, 'F': 268},
 {'M': 637, 'F': 263},
 {'M': 650, 'F': 268},
 {'M': 524, 'F': 218},
 {'M': 542, 'F': 232},
 {'M': 572, 'F': 242},
 {'M': 619, 'F': 243},
 {'M': 602, 'F': 250},
 {'M': 532, 'F': 238},
 {'M': 664, 'F': 273},
 {'M': 514, 'F': 219},
 {'M': 652, 'F': 267},
 {'M': 650, 'F': 268},
 {'M': 615, 'F': 240},
 {'M': 621, 'F': 256},
 {'M': 629, 'F': 263},
 {'M': 662, 'F': 270},
 {'M': 642, 'F': 261},
 {'M': 530, 'F': 243},
 {'M': 408, 'F': 149},
 {'M': 630, 'F': 260},
 {'M': 586, 'F': 228},
 {'M': 637, 'F': 266},
 {'M': 588, 'F': 226},
 {'M': 616, 'F': 261},
 {'M': 648, 'F': 268},
 {'M': 581, 'F': 257},
 {'M': 496, 'F': 228},
 {'M': 593, 'F': 244},
 {'M': 579, 'F': 237},
 {'M': 646, 'F': 268},
 {'M': 659, 'F': 270},
 {'M': 585, 'F': 227},
 {'M': 610, 'F': 262},
 {'M': 659, 'F': 272},
 {'M': 533, 'F': 241},
 {'M': 617, 'F': 262},
 {'M': 509, 'F': 235},
 {'M': 655, 'F': 260},
 {'M': 546, 'F': 220},
 {'M': 631, 'F': 246},
 {'M': 481, 'F': 230},
 {'M': 663, 'F': 272},
 {'M': 648, 'F': 264},
 {'M': 595, 'F': 259},
 {'M': 614, 'F': 245},
 {'M': 649, 'F': 250},
 {'M': 556, 'F': 258},
 {'M': 635, 'F': 229},
 {'M': 622, 'F': 253},
 {'M': 527, 'F': 223},
 {'M': 489, 'F': 196},
 {'M': 648, 'F': 272},
 {'M': 627, 'F': 254},
 {'M': 612, 'F': 263},
 {'M': 575, 'F': 235},
 {'M': 624, 'F': 260},
 {'M': 654, 'F': 265},
 {'M': 625, 'F': 260},
 {'M': 512, 'F': 218},
 {'M': 625, 'F': 265},
 {'M': 594, 'F': 248},
 {'M': 642, 'F': 270},
 {'M': 593, 'F': 247},
 {'M': 658, 'F': 273},
 {'M': 639, 'F': 258},
 {'M': 591, 'F': 246},
 {'M': 597, 'F': 242},
 {'M': 592, 'F': 252},
 {'M': 587, 'F': 236},
 {'M': 599, 'F': 248},
 {'M': 655, 'F': 271},
 {'M': 545, 'F': 237},
 {'M': 664, 'F': 261},
 {'M': 646, 'F': 263},
 {'M': 608, 'F': 248},
 {'M': 618, 'F': 256},
 {'M': 464, 'F': 212},
 {'M': 647, 'F': 244},
 {'M': 630, 'F': 262},
 {'M': 574, 'F': 243},
 {'M': 577, 'F': 250},
 {'M': 645, 'F': 268},
 {'M': 645, 'F': 265},
 {'M': 570, 'F': 252},
 {'M': 517, 'F': 233},
 {'M': 520, 'F': 242},
 {'M': 316, 'F': 150},
 {'M': 648, 'F': 256},
 {'M': 533, 'F': 240},
 {'M': 531, 'F': 209},
 {'M': 531, 'F': 224},
 {'M': 635, 'F': 265},
 {'M': 587, 'F': 244},
 {'M': 512, 'F': 218},
 {'M': 604, 'F': 241},
 {'M': 573, 'F': 236},
 {'M': 477, 'F': 219},
 {'M': 572, 'F': 257},
 {'M': 634, 'F': 264},
 {'M': 640, 'F': 261},
 {'M': 565, 'F': 255},
 {'M': 660, 'F': 264},
 {'M': 583, 'F': 266},
 {'M': 637, 'F': 254},
 {'M': 617, 'F': 254},
 {'M': 636, 'F': 245},
 {'M': 619, 'F': 236},
 {'M': 649, 'F': 267},
 {'M': 652, 'F': 262},
 {'M': 617, 'F': 244},
 {'M': 647, 'F': 263},
 {'M': 586, 'F': 250},
 {'M': 642, 'F': 259},
 {'M': 645, 'F': 266},
 {'M': 643, 'F': 252},
 {'M': 644, 'F': 270},
 {'M': 617, 'F': 247},
 {'M': 633, 'F': 270},
 {'M': 538, 'F': 224},
 {'M': 572, 'F': 238},
 {'M': 649, 'F': 268},
 {'M': 635, 'F': 261},
 {'M': 661, 'F': 263},
 {'M': 619, 'F': 259},
 {'M': 642, 'F': 266},
 {'M': 642, 'F': 264},
 {'M': 656, 'F': 267},
 {'M': 564, 'F': 253},
 {'M': 619, 'F': 250},
 {'M': 614, 'F': 257},
 {'M': 661, 'F': 272},
 {'M': 411, 'F': 185},
 {'M': 547, 'F': 211},
 {'M': 601, 'F': 252},
 {'M': 565, 'F': 232},
 {'M': 639, 'F': 254},
 {'M': 486, 'F': 223},
 {'M': 617, 'F': 253},
 {'M': 662, 'F': 271},
 {'M': 653, 'F': 265},
 {'M': 663, 'F': 264},
 {'M': 574, 'F': 250},
 {'M': 658, 'F': 266},
 {'M': 633, 'F': 262},
 {'M': 620, 'F': 253},
 {'M': 612, 'F': 256},
 {'M': 620, 'F': 248},
 {'M': 666, 'F': 269},
 {'M': 617, 'F': 236},
 {'M': 635, 'F': 262},
 {'M': 664, 'F': 271},
 {'M': 513, 'F': 230},
 {'M': 634, 'F': 250},
 {'M': 643, 'F': 270},
 {'M': 643, 'F': 270},
 {'M': 575, 'F': 244},
 {'M': 633, 'F': 257},
 {'M': 665, 'F': 273},
 {'M': 664, 'F': 272},
 {'M': 541, 'F': 220},
 {'M': 562, 'F': 230},
 {'M': 559, 'F': 225},
 {'M': 639, 'F': 253},
 {'M': 573, 'F': 234},
 {'M': 616, 'F': 258},
 {'M': 596, 'F': 264},
 {'M': 576, 'F': 235},
 {'M': 668, 'F': 271},
 {'M': 644, 'F': 251},
 {'M': 667, 'F': 272},
 {'M': 633, 'F': 261},
 {'M': 618, 'F': 242},
 {'M': 623, 'F': 267},
 {'M': 610, 'F': 243},
 {'M': 627, 'F': 262},
 {'M': 628, 'F': 254},
 {'M': 667, 'F': 272},
 {'M': 642, 'F': 245},
 {'M': 643, 'F': 269},
 {'M': 660, 'F': 271},
 {'M': 552, 'F': 235},
 {'M': 652, 'F': 268},
 {'M': 639, 'F': 262},
 {'M': 643, 'F': 261},
 {'M': 536, 'F': 228},
 {'M': 655, 'F': 266},
 {'M': 589, 'F': 260},
 {'M': 636, 'F': 263},
 {'M': 602, 'F': 245},
 {'M': 663, 'F': 271},
 {'M': 612, 'F': 261},
 {'M': 666, 'F': 270},
 {'M': 614, 'F': 259},
 {'M': 601, 'F': 229},
 {'M': 650, 'F': 266},
 {'M': 632, 'F': 257},
 {'M': 625, 'F': 263},
 {'M': 626, 'F': 255},
 {'M': 637, 'F': 264},
 {'M': 501, 'F': 218},
 {'M': 630, 'F': 248},
 {'M': 619, 'F': 254},
 {'M': 532, 'F': 244},
 {'M': 617, 'F': 256},
 {'M': 546, 'F': 244},
 {'M': 650, 'F': 267},
 {'M': 665, 'F': 271},
 {'M': 567, 'F': 241},
 {'M': 578, 'F': 235},
 {'M': 668, 'F': 271},
 {'M': 595, 'F': 245},
 {'M': 635, 'F': 270},
 {'M': 645, 'F': 254},
 {'M': 635, 'F': 250},
 {'M': 648, 'F': 272},
 {'M': 633, 'F': 249},
 {'M': 601, 'F': 244},
 {'M': 666, 'F': 271},
 {'M': 625, 'F': 253},
 {'M': 496, 'F': 187},
 {'M': 534, 'F': 240},
 {'M': 663, 'F': 269},
 {'M': 638, 'F': 266},
 {'M': 646, 'F': 271},
 {'M': 571, 'F': 250},
 {'M': 585, 'F': 253},
 {'M': 631, 'F': 247},
 {'M': 600, 'F': 263},
 {'M': 621, 'F': 260},
 {'M': 578, 'F': 255},
 {'M': 495, 'F': 207},
 {'M': 619, 'F': 262},
 {'M': 597, 'F': 257},
 {'M': 637, 'F': 272},
 {'M': 545, 'F': 247},
 {'M': 652, 'F': 269},
 {'M': 641, 'F': 258},
 {'M': 627, 'F': 252},
 {'M': 607, 'F': 253},
 {'M': 590, 'F': 233},
 {'M': 595, 'F': 232},
 {'M': 597, 'F': 245},
 {'M': 613, 'F': 257},
 {'M': 665, 'F': 272},
 {'M': 637, 'F': 265},
 {'M': 634, 'F': 264},
 {'M': 611, 'F': 245},
 {'M': 654, 'F': 258},
 {'M': 646, 'F': 266},
 {'M': 654, 'F': 262},
 {'M': 647, 'F': 258},
 {'M': 604, 'F': 265},
 {'M': 656, 'F': 268},
 {'M': 605, 'F': 251},
 {'M': 619, 'F': 246},
 {'M': 581, 'F': 256},
 {'M': 556, 'F': 228},
 {'M': 576, 'F': 252},
 {'M': 617, 'F': 253},
 {'M': 578, 'F': 244},
 {'M': 641, 'F': 264},
 {'M': 661, 'F': 269},
 {'M': 596, 'F': 250},
 {'M': 645, 'F': 270},
 {'M': 654, 'F': 272},
 {'M': 628, 'F': 262},
 {'M': 550, 'F': 249},
 {'M': 661, 'F': 271},
 {'M': 614, 'F': 246},
 {'M': 620, 'F': 262},
 {'M': 658, 'F': 266},
 {'M': 602, 'F': 251},
 {'M': 604, 'F': 241},
 {'M': 668, 'F': 272},
 {'M': 621, 'F': 248},
 {'M': 589, 'F': 240},
 {'M': 664, 'F': 266},
 {'M': 593, 'F': 250},
 {'M': 595, 'F': 255},
 {'M': 652, 'F': 265},
 {'M': 527, 'F': 221},
 {'M': 658, 'F': 269},
 {'M': 624, 'F': 260},
 {'M': 622, 'F': 262},
 {'M': 587, 'F': 247},
 {'M': 576, 'F': 247},
 {'M': 663, 'F': 268},
 {'M': 642, 'F': 263},
 {'M': 659, 'F': 268},
 {'M': 561, 'F': 251},
 {'M': 655, 'F': 272},
 {'M': 658, 'F': 271},
 {'M': 656, 'F': 261},
 {'M': 633, 'F': 260},
 {'M': 649, 'F': 264},
 {'M': 595, 'F': 235},
 {'M': 579, 'F': 232},
 {'M': 649, 'F': 261},
 {'M': 638, 'F': 261},
 {'M': 526, 'F': 239},
 {'M': 658, 'F': 263},
 {'M': 602, 'F': 255},
 {'M': 614, 'F': 260},
 {'M': 660, 'F': 266},
 {'M': 647, 'F': 264},
 {'M': 598, 'F': 241},
 {'M': 637, 'F': 266},
 {'M': 660, 'F': 267},
 {'M': 630, 'F': 261},
 {'M': 638, 'F': 268},
 {'M': 649, 'F': 267},
 {'M': 624, 'F': 267},
 {'M': 647, 'F': 263},
 {'M': 623, 'F': 255},
 {'M': 614, 'F': 253},
 {'M': 609, 'F': 249},
 {'M': 658, 'F': 261},
 {'M': 632, 'F': 266},
 {'M': 620, 'F': 247},
 {'M': 633, 'F': 266},
 {'M': 635, 'F': 256},
 {'M': 651, 'F': 255},
 {'M': 614, 'F': 249},
 {'M': 625, 'F': 254},
 {'M': 665, 'F': 270},
 {'M': 636, 'F': 260},
 {'M': 663, 'F': 268},
 {'M': 621, 'F': 254},
 {'M': 576, 'F': 215},
 {'M': 643, 'F': 261},
 {'M': 647, 'F': 268},
 {'M': 655, 'F': 272},
 {'M': 627, 'F': 265},
 {'M': 659, 'F': 266},
 {'M': 613, 'F': 259},
 {'M': 606, 'F': 250},
 {'M': 641, 'F': 271},
 {'M': 630, 'F': 248},
 {'M': 637, 'F': 254},
 {'M': 626, 'F': 261},
 {'M': 548, 'F': 250},
 {'M': 591, 'F': 242},
 {'M': 644, 'F': 266},
 {'M': 659, 'F': 263},
 {'M': 643, 'F': 271},
 {'M': 592, 'F': 259},
 {'M': 653, 'F': 262},
 {'M': 661, 'F': 267},
 {'M': 652, 'F': 269},
 {'M': 529, 'F': 240},
 {'M': 592, 'F': 243},
 {'M': 659, 'F': 270},
 {'M': 667, 'F': 273},
 {'M': 657, 'F': 271},
 {'M': 624, 'F': 269},
 {'M': 560, 'F': 246},
 {'M': 598, 'F': 253},
 {'M': 649, 'F': 265},
 {'M': 651, 'F': 267},
 {'M': 643, 'F': 254},
 {'M': 659, 'F': 269},
 {'M': 608, 'F': 256},
 {'M': 668, 'F': 272},
 {'M': 664, 'F': 270},
 {'M': 634, 'F': 259},
 {'M': 665, 'F': 273},
 {'M': 649, 'F': 272},
 {'M': 657, 'F': 269},
 {'M': 656, 'F': 266},
 {'M': 631, 'F': 250},
 {'M': 604, 'F': 258},
 {'M': 660, 'F': 270},
 {'M': 613, 'F': 262},
 {'M': 530, 'F': 219},
 {'M': 658, 'F': 264},
 {'M': 594, 'F': 254},
 {'M': 636, 'F': 268},
 {'M': 422, 'F': 167},
 {'M': 668, 'F': 271},
 {'M': 641, 'F': 251},
 {'M': 637, 'F': 264},
 {'M': 572, 'F': 241},
 {'M': 556, 'F': 237},
 {'M': 667, 'F': 271},
 {'M': 668, 'F': 269},
 {'M': 579, 'F': 253},
 {'M': 644, 'F': 262},
 {'M': 666, 'F': 271},
 {'M': 646, 'F': 271},
 {'M': 651, 'F': 265},
 {'M': 598, 'F': 247},
 {'M': 636, 'F': 257},
 {'M': 660, 'F': 259},
 {'M': 605, 'F': 233},
 {'M': 568, 'F': 234},
 {'M': 636, 'F': 250},
 {'M': 655, 'F': 265},
 {'M': 648, 'F': 260},
 {'M': 646, 'F': 271},
 {'M': 664, 'F': 269},
 {'M': 657, 'F': 264},
 {'M': 605, 'F': 262},
 {'M': 619, 'F': 263},
 {'M': 638, 'F': 265},
 {'M': 668, 'F': 273},
 {'M': 660, 'F': 265},
 {'M': 621, 'F': 252},
 {'M': 631, 'F': 258},
 {'M': 632, 'F': 259},
 {'M': 653, 'F': 269},
 {'M': 637, 'F': 268},
 {'M': 665, 'F': 265},
 {'M': 640, 'F': 256},
 {'M': 668, 'F': 273},
 {'M': 658, 'F': 267},
 {'M': 626, 'F': 263},
 {'M': 654, 'F': 264},
 {'M': 638, 'F': 264},
 {'M': 567, 'F': 229},
 {'M': 592, 'F': 244},
 {'M': 485, 'F': 210},
 {'M': 664, 'F': 269},
 {'M': 623, 'F': 261},
 {'M': 611, 'F': 264},
 {'M': 642, 'F': 270},
 {'M': 632, 'F': 262},
 {'M': 665, 'F': 273},
 {'M': 630, 'F': 259},
 {'M': 646, 'F': 261},
 {'M': 625, 'F': 264},
 {'M': 645, 'F': 262},
 {'M': 636, 'F': 255},
 {'M': 610, 'F': 254},
 {'M': 662, 'F': 272},
 {'M': 639, 'F': 261},
 {'M': 639, 'F': 259},
 {'M': 662, 'F': 269},
 {'M': 660, 'F': 271},
 {'M': 661, 'F': 269},
 {'M': 657, 'F': 269},
 {'M': 641, 'F': 266},
 {'M': 663, 'F': 263},
 {'M': 646, 'F': 263},
 {'M': 641, 'F': 253},
 {'M': 465, 'F': 192},
 {'M': 651, 'F': 271},
 {'M': 661, 'F': 270},
 {'M': 652, 'F': 267},
 {'M': 634, 'F': 261},
 {'M': 665, 'F': 269},
 {'M': 579, 'F': 253},
 {'M': 645, 'F': 252},
 {'M': 663, 'F': 270},
 {'M': 660, 'F': 268},
 {'M': 638, 'F': 260},
 {'M': 589, 'F': 259},
 {'M': 622, 'F': 263},
 {'M': 632, 'F': 268},
 {'M': 645, 'F': 262},
 {'M': 578, 'F': 244},
 {'M': 633, 'F': 261},
 {'M': 650, 'F': 264},
 {'M': 666, 'F': 271},
 {'M': 650, 'F': 267},
 {'M': 642, 'F': 267},
 {'M': 587, 'F': 255},
 {'M': 656, 'F': 268},
 {'M': 653, 'F': 267},
 {'M': 647, 'F': 269},
 {'M': 660, 'F': 266},
 {'M': 645, 'F': 253},
 {'M': 608, 'F': 256},
 {'M': 667, 'F': 265},
 {'M': 632, 'F': 258},
 {'M': 654, 'F': 267},
 {'M': 632, 'F': 253},
 {'M': 552, 'F': 237},
 {'M': 659, 'F': 263},
 {'M': 617, 'F': 264},
 {'M': 603, 'F': 249},
 {'M': 630, 'F': 263},
 {'M': 640, 'F': 266},
 {'M': 550, 'F': 254},
 {'M': 669, 'F': 270},
 {'M': 660, 'F': 270},
 {'M': 668, 'F': 270},
 {'M': 655, 'F': 254},
 {'M': 655, 'F': 265},
 {'M': 643, 'F': 266},
 {'M': 658, 'F': 267},
 {'M': 665, 'F': 272},
 {'M': 611, 'F': 256},
 {'M': 644, 'F': 267},
 {'M': 636, 'F': 270},
 {'M': 646, 'F': 261},
 {'M': 638, 'F': 270},
 {'M': 661, 'F': 267},
 {'M': 634, 'F': 268},
 {'M': 652, 'F': 266},
 {'M': 665, 'F': 272},
 {'M': 660, 'F': 270},
 {'M': 635, 'F': 264},
 {'M': 617, 'F': 254},
 {'M': 655, 'F': 270},
 {'M': 659, 'F': 266},
 {'M': 595, 'F': 243},
 {'M': 665, 'F': 266},
 {'M': 615, 'F': 249},
 {'M': 650, 'F': 267},
 {'M': 666, 'F': 271},
 {'M': 666, 'F': 270},
 {'M': 658, 'F': 270},
 {'M': 655, 'F': 272},
 {'M': 663, 'F': 269},
 {'M': 665, 'F': 272},
 {'M': 662, 'F': 270},
 {'M': 654, 'F': 268},
 {'M': 623, 'F': 257},
 {'M': 632, 'F': 267},
 {'M': 621, 'F': 262},
 {'M': 648, 'F': 265},
 {'M': 654, 'F': 272},
 {'M': 641, 'F': 256},
 {'M': 659, 'F': 271},
 {'M': 564, 'F': 248},
 {'M': 647, 'F': 269},
 {'M': 663, 'F': 271},
 {'M': 664, 'F': 271},
 {'M': 665, 'F': 271},
 {'M': 660, 'F': 272},
 {'M': 641, 'F': 247},
 {'M': 624, 'F': 264},
 {'M': 644, 'F': 261},
 {'M': 664, 'F': 269},
 {'M': 669, 'F': 271},
 {'M': 659, 'F': 262},
 {'M': 661, 'F': 269},
 {'M': 594, 'F': 253},
 {'M': 657, 'F': 261},
 {'M': 629, 'F': 256},
 {'M': 625, 'F': 259},
 {'M': 624, 'F': 262},
 {'M': 660, 'F': 270},
 {'M': 625, 'F': 254},
 {'M': 660, 'F': 268},
 {'M': 613, 'F': 257},
 {'M': 642, 'F': 271},
 {'M': 655, 'F': 261},
 {'M': 668, 'F': 271},
 {'M': 658, 'F': 270},
 {'M': 663, 'F': 269},
 {'M': 644, 'F': 262},
 {'M': 638, 'F': 267},
 {'M': 652, 'F': 271},
 {'M': 641, 'F': 263},
 {'M': 648, 'F': 266},
 {'M': 651, 'F': 265},
 {'M': 600, 'F': 260},
 {'M': 654, 'F': 270},
 {'M': 657, 'F': 271},
 {'M': 649, 'F': 269},
 {'M': 661, 'F': 272},
 {'M': 643, 'F': 265},
 {'M': 658, 'F': 264},
 {'M': 658, 'F': 266},
 {'M': 626, 'F': 260},
 {'M': 651, 'F': 268},
 {'M': 655, 'F': 267},
 {'M': 647, 'F': 261},
 {'M': 664, 'F': 271},
 {'M': 666, 'F': 269},
 {'M': 637, 'F': 260},
 {'M': 666, 'F': 273},
 {'M': 641, 'F': 255},
 {'M': 630, 'F': 255},
 {'M': 660, 'F': 260},
 {'M': 668, 'F': 269},
 {'M': 622, 'F': 262},
 {'M': 599, 'F': 247},
 {'M': 665, 'F': 270},
 {'M': 635, 'F': 268},
 {'M': 659, 'F': 271},
 {'M': 567, 'F': 234},
 {'M': 607, 'F': 249},
 {'M': 571, 'F': 234},
 {'M': 630, 'F': 258},
 {'M': 565, 'F': 256},
 {'M': 663, 'F': 271},
 {'M': 631, 'F': 261},
 {'M': 640, 'F': 264},
 {'M': 668, 'F': 272},
 {'M': 659, 'F': 269},
 {'M': 660, 'F': 267},
 {'M': 639, 'F': 260},
 {'M': 557, 'F': 241},
 {'M': 644, 'F': 263},
 {'M': 657, 'F': 264},
 {'M': 643, 'F': 266},

In [166]:
print(type_count)

{'M': 670, 'F': 273}

In [167]:
num_item = len(train_df['item_id'].unique())
num_user = len(train_df['user_id'].unique())
num_type = len(key_type)
print('items number : ',num_item)
print('users number : ',num_user)
print('user types : ',key_type)

items number :  1472
users number :  943
user types :  ['M', 'F']

In [168]:
dict_args["num_type"] = len(key_type)

In [169]:
user_type_list = [] #preprocessing to be sure that user types are really the right ones armielle 
for u in range(num_user):
    gl = user_idd_type_list[u]
    tmp = []
    for g in gl:
        if g in key_type:
            tmp.append(g)
    user_type_list.append(tmp)

print(len(user_type_list))

943

In [170]:
# genreate user_type matrix
user_type = np.zeros((num_user, num_type))
for u in range(num_user):
    gl = user_type_list[u]
    for k in range(num_type):
        if key_type[k] in gl:
            user_type[u, k] = 1.0

In [171]:
len(user_type_list)

943

In [172]:
print('*' * 50)
print('number of positive feedback: ' + str(len(train_df)))
print('estimated number of training samples: ' + str(neg * len(train_df)))
print('*' * 50)

**************************************************
number of positive feedback: 80146
estimated number of training samples: 400730
**************************************************

In [173]:
type_count_mean_reciprocal = []
for k in key_type:
    type_count_mean_reciprocal.append(1.0 / type_count[k])
type_count_mean_reciprocal = (np.array(type_count_mean_reciprocal)).reshape((num_type, 1))
type_error_weight = np.dot(user_type, type_count_mean_reciprocal)

In [174]:
# generate user_type matrix
type_user_indicator = np.zeros((num_type, num_user))

for k in range(num_type):
    type_user_indicator[k,:] = type_user_vector[key_type[k]]

In [175]:
precision = np.zeros(4)
recall = np.zeros(4)
f1 = np.zeros(4)
ndcg = np.zeros(4)
RSP = np.zeros(4)
REO = np.zeros(4)

precision

array([0., 0., 0., 0.])

In [176]:
len(user_type)

943

In [177]:
user_type.shape

(943, 2)

In [178]:
#tf.compat.v1.disable_eager_execution()
#tf.enable_eager_execution()
for i in range(n):
    with tf.compat.v1.Session() as sess:
        fairadvbpr = FairAdvBPR(sess, dict_args, train_df, test_df, user_type, type_error_weight, key_type, user_type_list, item_type_count)
        [prec_one, rec_one, f_one, ndcg_one, Rec] = fairadvbpr.run()
        #[RSP_one, REO_one] = utility.ranking_analysis(Rec, vali_df, train_df, key_genre, item_genre_list, user_genre_count)
#         precision += prec_one
#         recall += rec_one
#         f1 += f_one
#         ndcg += ndcg_one
#         RSP += RSP_one
#         REO += REO_one

**********fairAdvBPR**********
shape q pos (?, 20)
shape p (?, 20)
shape predict pos  (?,)
shape adv_last  (?, 1)
INFO:tensorflow:Restoring parameters from ./ml1m-6/BPR_check_points\check_point.ckpt-41
Training // Epoch 1 //  Total r_cost = 196695.43311  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 476 ms negative Sampling time : 12119 ms negative samples : 400730
precision_1	[0.4188759],	||	 precision_5	[0.3208908],	||	 precision_10	[0.2726405],	||	 precision_15	[0.2416402]
recall_1   	[0.0288540],	||	 recall_5   	[0.1050808],	||	 recall_10   	[0.1697450],	||	 recall_15   	[0.2208417]
f_measure_1	[0.0539890],	||	 f_measure_5	[0.1583179],	||	 f_measure_10	[0.2092264],	||	 f_measure_15	[0.2307732]
ndcg_1     	[0.4188759],	||	 ndcg_5     	[0.3434508],	||	 ndcg_10     	[0.3249946],	||	 ndcg_15     	[0.3207431]
Metrics for user type	 M
precision_1	[0.4417910],	||	 precision_5	[0.3426866],	||	 precision_10	[0.2910448],	||	 precision_15	[0.2585075]
recall_1	[0.0293887],	||	 recall_5	[0.1063862],	||	 recall_10	[0.1719386],	||	 recall_15	[0.2242606]
ndcg_1	[0.4417910],	||	 ndcg_5	[0.3653464],	||	 ndcg_10	[0.3433487],	||	 ndcg_15	[0.3373324]
AUC per user type	[0.9016406]
Metrics for user type	 F
precision_1	[0.3626374],	||	 precision_5	[0.2673993],	||	 precision_10	[0.2274725],	||	 precision_15	[0.2002442]
recall_1	[0.0275417],	||	 recall_5	[0.1018771],	||	 recall_10	[0.1643614],	||	 recall_15	[0.2124510]
ndcg_1	[0.3626374],	||	 ndcg_5	[0.2897143],	||	 ndcg_10	[0.2799496],	||	 ndcg_15	[0.2800294]
AUC per user type	[0.8984989]
AUC global is:  0.9007310625406424
Training // Epoch 2 //  Total r_cost = 190048.57175  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 362 ms negative Sampling time : 7984 ms negative samples : 400730
precision_1	[0.4358431],	||	 precision_5	[0.3314952],	||	 precision_10	[0.2870626],	||	 precision_15	[0.2572641]
recall_1   	[0.0307040],	||	 recall_5   	[0.1121911],	||	 recall_10   	[0.1844368],	||	 recall_15   	[0.2398970]
f_measure_1	[0.0573667],	||	 f_measure_5	[0.1676446],	||	 f_measure_10	[0.2245810],	||	 f_measure_15	[0.2482772]
ndcg_1     	[0.4358431],	||	 ndcg_5     	[0.3560784],	||	 ndcg_10     	[0.3426032],	||	 ndcg_15     	[0.3409990]
Metrics for user type	 M
precision_1	[0.4507463],	||	 precision_5	[0.3525373],	||	 precision_10	[0.3052239],	||	 precision_15	[0.2754229]
recall_1	[0.0301482],	||	 recall_5	[0.1123431],	||	 recall_10	[0.1855289],	||	 recall_15	[0.2435024]
ndcg_1	[0.4507463],	||	 ndcg_5	[0.3760708],	||	 ndcg_10	[0.3592967],	||	 ndcg_15	[0.3571229]
AUC per user type	[0.9074559]
Metrics for user type	 F
precision_1	[0.3992674],	||	 precision_5	[0.2798535],	||	 precision_10	[0.2424908],	||	 precision_15	[0.2126984]
recall_1	[0.0320680],	||	 recall_5	[0.1118180],	||	 recall_10	[0.1817565],	||	 recall_15	[0.2310486]
ndcg_1	[0.3992674],	||	 ndcg_5	[0.3070128],	||	 ndcg_10	[0.3016337],	||	 ndcg_15	[0.3014274]
AUC per user type	[0.9050566]
AUC global is:  0.9067612923415835
Training // Epoch 3 //  Total r_cost = 189249.05478  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 347 ms negative Sampling time : 8419 ms negative samples : 400730
precision_1	[0.4422057],	||	 precision_5	[0.3395546],	||	 precision_10	[0.2925769],	||	 precision_15	[0.2624249]
recall_1   	[0.0317523],	||	 recall_5   	[0.1142559],	||	 recall_10   	[0.1856994],	||	 recall_15   	[0.2437100]
f_measure_1	[0.0592502],	||	 f_measure_5	[0.1709793],	||	 f_measure_10	[0.2271965],	||	 f_measure_15	[0.2527214]
ndcg_1     	[0.4422057],	||	 ndcg_5     	[0.3645870],	||	 ndcg_10     	[0.3492635],	||	 ndcg_15     	[0.3481187]
Metrics for user type	 M
precision_1	[0.4522388],	||	 precision_5	[0.3594030],	||	 precision_10	[0.3119403],	||	 precision_15	[0.2782090]
recall_1	[0.0309417],	||	 recall_5	[0.1136324],	||	 recall_10	[0.1893957],	||	 recall_15	[0.2466483]
ndcg_1	[0.4522388],	||	 ndcg_5	[0.3830094],	||	 ndcg_10	[0.3667736],	||	 ndcg_15	[0.3625368]
AUC per user type	[0.9087201]
Metrics for user type	 F
precision_1	[0.4175824],	||	 precision_5	[0.2908425],	||	 precision_10	[0.2450549],	||	 precision_15	[0.2236874]
recall_1	[0.0337417],	||	 recall_5	[0.1157859],	||	 recall_10	[0.1766279],	||	 recall_15	[0.2364988]
ndcg_1	[0.4175824],	||	 ndcg_5	[0.3193745],	||	 ndcg_10	[0.3062902],	||	 ndcg_15	[0.3127336]
AUC per user type	[0.9076166]
AUC global is:  0.9084006631095336
Training // Epoch 4 //  Total r_cost = 189418.45938  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 350 ms negative Sampling time : 7941 ms negative samples : 400730
precision_1	[0.4390244],	||	 precision_5	[0.3469777],	||	 precision_10	[0.2989396],	||	 precision_15	[0.2669495]
recall_1   	[0.0310668],	||	 recall_5   	[0.1154877],	||	 recall_10   	[0.1916872],	||	 recall_15   	[0.2479236]
f_measure_1	[0.0580274],	||	 f_measure_5	[0.1732958],	||	 f_measure_10	[0.2335905],	||	 f_measure_15	[0.2570850]
ndcg_1     	[0.4390244],	||	 ndcg_5     	[0.3676702],	||	 ndcg_10     	[0.3526694],	||	 ndcg_15     	[0.3510214]
Metrics for user type	 M
precision_1	[0.4537313],	||	 precision_5	[0.3680597],	||	 precision_10	[0.3191045],	||	 precision_15	[0.2841791]
recall_1	[0.0305782],	||	 recall_5	[0.1168540],	||	 recall_10	[0.1965790],	||	 recall_15	[0.2515431]
ndcg_1	[0.4537313],	||	 ndcg_5	[0.3876523],	||	 ndcg_10	[0.3715382],	||	 ndcg_15	[0.3672248]
AUC per user type	[0.9098723]
Metrics for user type	 F
precision_1	[0.4029304],	||	 precision_5	[0.2952381],	||	 precision_10	[0.2494505],	||	 precision_15	[0.2246642]
recall_1	[0.0322659],	||	 recall_5	[0.1121344],	||	 recall_10	[0.1796817],	||	 recall_15	[0.2390405]
ndcg_1	[0.4029304],	||	 ndcg_5	[0.3186300],	||	 ndcg_10	[0.3063616],	||	 ndcg_15	[0.3112549]
AUC per user type	[0.9095674]
AUC global is:  0.9097840267160752
Training // Epoch 5 //  Total r_cost = 188948.02780  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 414 ms negative Sampling time : 8999 ms negative samples : 400730
precision_1	[0.4379639],	||	 precision_5	[0.3410392],	||	 precision_10	[0.2944857],	||	 precision_15	[0.2616472]
recall_1   	[0.0324380],	||	 recall_5   	[0.1133083],	||	 recall_10   	[0.1881864],	||	 recall_15   	[0.2425214]
f_measure_1	[0.0604023],	||	 f_measure_5	[0.1701014],	||	 f_measure_10	[0.2296309],	||	 f_measure_15	[0.2517215]
ndcg_1     	[0.4379639],	||	 ndcg_5     	[0.3640872],	||	 ndcg_10     	[0.3496915],	||	 ndcg_15     	[0.3466735]
Metrics for user type	 M
precision_1	[0.4358209],	||	 precision_5	[0.3629851],	||	 precision_10	[0.3153731],	||	 precision_15	[0.2785075]
recall_1	[0.0306052],	||	 recall_5	[0.1153943],	||	 recall_10	[0.1917983],	||	 recall_15	[0.2464013]
ndcg_1	[0.4358209],	||	 ndcg_5	[0.3818331],	||	 ndcg_10	[0.3668983],	||	 ndcg_15	[0.3611704]
AUC per user type	[0.9095426]
Metrics for user type	 F
precision_1	[0.4432234],	||	 precision_5	[0.2871795],	||	 precision_10	[0.2432234],	||	 precision_15	[0.2202686]
recall_1	[0.0369360],	||	 recall_5	[0.1081889],	||	 recall_10	[0.1793221],	||	 recall_15	[0.2329993]
ndcg_1	[0.4432234],	||	 ndcg_5	[0.3205349],	||	 ndcg_10	[0.3074625],	||	 ndcg_15	[0.3110950]
AUC per user type	[0.9074050]
AUC global is:  0.9089237609517702
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0

post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00341796875

post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00439453125
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00048828125
post adversarial -- adversaire ready after one adv epoch training  0.0
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00390625
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.0048828125
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.0068359375
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.00439453125
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.00537109375
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.00390625
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00439453125
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.001953125
post adversarial -- adversaire ready after one adv epoch training  0.00537109375
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.0009765625
post adversarial -- adversaire ready after one adv epoch training  0.00390625
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00146484375
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.0029296875
post adversarial -- adversaire ready after one adv epoch training  0.00537109375

post adversarial -- adversaire ready after one adv epoch training  0.00390625
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00244140625
post adversarial -- adversaire ready after one adv epoch training  0.0068359375
post adversarial -- adversaire ready after one adv epoch training  0.00439453125
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00390625
post adversarial -- adversaire ready after one adv epoch training  0.00634765625
post adversarial -- adversaire ready after one adv epoch training  0.00537109375
post adversarial -- adversaire ready after one adv epoch training  0.0048828125
post adversarial -- adversaire ready after one adv epoch training  0.00439453125
post adversarial -- adversaire ready after one adv epoch training  0.0068359375
post adversarial -- adversaire ready after one adv epoch training  0.00390625
post adversarial -- adversaire ready after one adv epoch training  0.00341796875
post adversarial -- adversaire ready after one adv epoch training  0.00390625
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.00830078125
post adversarial -- adversaire ready after one adv epoch training  0.00390625
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.00927734375
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.00537109375
post adversarial -- adversaire ready after one adv epoch training  0.00537109375
post adversarial -- adversaire ready after one adv epoch training  0.00732421875
post adversarial -- adversaire ready after one adv epoch training  0.00537109375
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.009765625
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.0048828125
post adversarial -- adversaire ready after one adv epoch training  0.0087890625
post adversarial -- adversaire ready after one adv epoch training  0.00439453125
post adversarial -- adversaire ready after one adv epoch training  0.00732421875
post adversarial -- adversaire ready after one adv epoch training  0.00732421875
post adversarial -- adversaire ready after one adv epoch training  0.00830078125
post adversarial -- adversaire ready after one adv epoch training  0.00830078125
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.0068359375
post adversarial -- adversaire ready after one adv epoch training  0.005859375
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.00927734375
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.0068359375
post adversarial -- adversaire ready after one adv epoch training  0.0087890625
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.0068359375
post adversarial -- adversaire ready after one adv epoch training  0.01171875
post adversarial -- adversaire ready after one adv epoch training  0.009765625
post adversarial -- adversaire ready after one adv epoch training  0.00732421875
post adversarial -- adversaire ready after one adv epoch training  0.00830078125
post adversarial -- adversaire ready after one adv epoch training  0.0107421875
post adversarial -- adversaire ready after one adv epoch training  0.01171875
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.0087890625
post adversarial -- adversaire ready after one adv epoch training  0.01220703125
post adversarial -- adversaire ready after one adv epoch training  0.01220703125
post adversarial -- adversaire ready after one adv epoch training  0.0087890625
post adversarial -- adversaire ready after one adv epoch training  0.00830078125
post adversarial -- adversaire ready after one adv epoch training  0.00732421875
post adversarial -- adversaire ready after one adv epoch training  0.00927734375
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.0087890625
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.009765625
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.0068359375
post adversarial -- adversaire ready after one adv epoch training  0.0107421875
post adversarial -- adversaire ready after one adv epoch training  0.01220703125
post adversarial -- adversaire ready after one adv epoch training  0.00830078125
post adversarial -- adversaire ready after one adv epoch training  0.01171875
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.0087890625
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.00927734375
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.00927734375
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.01171875
post adversarial -- adversaire ready after one adv epoch training  0.00927734375
post adversarial -- adversaire ready after one adv epoch training  0.01220703125
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.01171875
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.01220703125
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.009765625
post adversarial -- adversaire ready after one adv epoch training  0.0107421875
post adversarial -- adversaire ready after one adv epoch training  0.0126953125
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.01220703125
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.009765625

post adversarial -- adversaire ready after one adv epoch training  0.01171875
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.0146484375
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.0166015625
post adversarial -- adversaire ready after one adv epoch training  0.01171875
post adversarial -- adversaire ready after one adv epoch training  0.009765625
post adversarial -- adversaire ready after one adv epoch training  0.021484375
post adversarial -- adversaire ready after one adv epoch training  0.0126953125
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.0107421875
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.01953125
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.0166015625
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.0166015625
post adversarial -- adversaire ready after one adv epoch training  0.01220703125
post adversarial -- adversaire ready after one adv epoch training  0.01806640625
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.0185546875
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.01025390625
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.0126953125
post adversarial -- adversaire ready after one adv epoch training  0.024566473439335823
Training // Epoch 6 //  Total r_cost = 189014.05463  Total a_cost = 32.05287 total pre adversarial accuracy = 0.00507 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 9749 ms negative Sampling time : 7925 ms negative samples : 400730
precision_1	[0.4591729],	||	 precision_5	[0.3512195],	||	 precision_10	[0.2987275],	||	 precision_15	[0.2637681]
recall_1   	[0.0332412],	||	 recall_5   	[0.1172824],	||	 recall_10   	[0.1909299],	||	 recall_15   	[0.2456179]
f_measure_1	[0.0619944],	||	 f_measure_5	[0.1758450],	||	 f_measure_10	[0.2329629],	||	 f_measure_15	[0.2543696]
ndcg_1     	[0.4591729],	||	 ndcg_5     	[0.3776582],	||	 ndcg_10     	[0.3584097],	||	 ndcg_15     	[0.3537526]
Metrics for user type	 M
precision_1	[0.4761194],	||	 precision_5	[0.3740299],	||	 precision_10	[0.3191045],	||	 precision_15	[0.2815920]
recall_1	[0.0333076],	||	 recall_5	[0.1206232],	||	 recall_10	[0.1946694],	||	 recall_15	[0.2493255]
ndcg_1	[0.4761194],	||	 ndcg_5	[0.3994350],	||	 ndcg_10	[0.3780219],	||	 ndcg_15	[0.3711203]
AUC per user type	[0.9109553]
Metrics for user type	 F
precision_1	[0.4175824],	||	 precision_5	[0.2952381],	||	 precision_10	[0.2487179],	||	 precision_15	[0.2200244]
recall_1	[0.0330783],	||	 recall_5	[0.1090834],	||	 recall_10	[0.1817521],	||	 recall_15	[0.2365186]
ndcg_1	[0.4175824],	||	 ndcg_5	[0.3242134],	||	 ndcg_10	[0.3102771],	||	 ndcg_15	[0.3111287]
AUC per user type	[0.9087482]
AUC global is:  0.9103163608385374
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.0068359375
post adversarial -- adversaire ready after one adv epoch training  0.0107421875
post adversarial -- adversaire ready after one adv epoch training  0.0078125
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.0107421875
post adversarial -- adversaire ready after one adv epoch training  0.01904296875
post adversarial -- adversaire ready after one adv epoch training  0.0126953125
post adversarial -- adversaire ready after one adv epoch training  0.01953125
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.0126953125
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.01904296875
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.0166015625
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.01220703125
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.01806640625
post adversarial -- adversaire ready after one adv epoch training  0.0126953125
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.0126953125
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.0146484375
post adversarial -- adversaire ready after one adv epoch training  0.0185546875
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.01123046875
post adversarial -- adversaire ready after one adv epoch training  0.0146484375
post adversarial -- adversaire ready after one adv epoch training  0.013671875
post adversarial -- adversaire ready after one adv epoch training  0.02001953125
post adversarial -- adversaire ready after one adv epoch training  0.015625

post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.0146484375
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.01806640625
post adversarial -- adversaire ready after one adv epoch training  0.0146484375
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.0146484375
post adversarial -- adversaire ready after one adv epoch training  0.0146484375
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.01806640625
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01806640625
post adversarial -- adversaire ready after one adv epoch training  0.02099609375
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.0234375
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.0185546875
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.01513671875
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.01904296875
post adversarial -- adversaire ready after one adv epoch training  0.01611328125
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.01318359375
post adversarial -- adversaire ready after one adv epoch training  0.01416015625
post adversarial -- adversaire ready after one adv epoch training  0.0224609375
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.02294921875
post adversarial -- adversaire ready after one adv epoch training  0.021484375
post adversarial -- adversaire ready after one adv epoch training  0.0185546875
post adversarial -- adversaire ready after one adv epoch training  0.021484375
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.017578125
post adversarial -- adversaire ready after one adv epoch training  0.01806640625
post adversarial -- adversaire ready after one adv epoch training  0.0185546875
post adversarial -- adversaire ready after one adv epoch training  0.0146484375
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.02099609375
post adversarial -- adversaire ready after one adv epoch training  0.0185546875
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.02099609375
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.02001953125
post adversarial -- adversaire ready after one adv epoch training  0.0224609375
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.015625
post adversarial -- adversaire ready after one adv epoch training  0.02197265625
post adversarial -- adversaire ready after one adv epoch training  0.021484375
post adversarial -- adversaire ready after one adv epoch training  0.02490234375
post adversarial -- adversaire ready after one adv epoch training  0.01806640625
post adversarial -- adversaire ready after one adv epoch training  0.02587890625
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.01953125
post adversarial -- adversaire ready after one adv epoch training  0.0283203125
post adversarial -- adversaire ready after one adv epoch training  0.01806640625
post adversarial -- adversaire ready after one adv epoch training  0.02587890625
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.0234375
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.0263671875
post adversarial -- adversaire ready after one adv epoch training  0.025390625
post adversarial -- adversaire ready after one adv epoch training  0.01953125
post adversarial -- adversaire ready after one adv epoch training  0.02294921875
post adversarial -- adversaire ready after one adv epoch training  0.01708984375
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.0283203125
post adversarial -- adversaire ready after one adv epoch training  0.02001953125
post adversarial -- adversaire ready after one adv epoch training  0.02294921875
post adversarial -- adversaire ready after one adv epoch training  0.02783203125
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.02685546875
post adversarial -- adversaire ready after one adv epoch training  0.02685546875
post adversarial -- adversaire ready after one adv epoch training  0.02294921875
post adversarial -- adversaire ready after one adv epoch training  0.02099609375
post adversarial -- adversaire ready after one adv epoch training  0.01953125
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.02197265625
post adversarial -- adversaire ready after one adv epoch training  0.03076171875
post adversarial -- adversaire ready after one adv epoch training  0.02294921875
post adversarial -- adversaire ready after one adv epoch training  0.0283203125
post adversarial -- adversaire ready after one adv epoch training  0.029296875
post adversarial -- adversaire ready after one adv epoch training  0.0224609375
post adversarial -- adversaire ready after one adv epoch training  0.02001953125
post adversarial -- adversaire ready after one adv epoch training  0.029296875
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.02783203125
post adversarial -- adversaire ready after one adv epoch training  0.025390625
post adversarial -- adversaire ready after one adv epoch training  0.02294921875
post adversarial -- adversaire ready after one adv epoch training  0.017578125

post adversarial -- adversaire ready after one adv epoch training  0.0234375
post adversarial -- adversaire ready after one adv epoch training  0.0234375
post adversarial -- adversaire ready after one adv epoch training  0.0234375
post adversarial -- adversaire ready after one adv epoch training  0.029296875
post adversarial -- adversaire ready after one adv epoch training  0.0224609375
post adversarial -- adversaire ready after one adv epoch training  0.02783203125
post adversarial -- adversaire ready after one adv epoch training  0.02734375
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.02197265625
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.0263671875
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.02197265625
post adversarial -- adversaire ready after one adv epoch training  0.02294921875
post adversarial -- adversaire ready after one adv epoch training  0.02587890625
post adversarial -- adversaire ready after one adv epoch training  0.0234375
post adversarial -- adversaire ready after one adv epoch training  0.01904296875
post adversarial -- adversaire ready after one adv epoch training  0.025390625
post adversarial -- adversaire ready after one adv epoch training  0.025390625
post adversarial -- adversaire ready after one adv epoch training  0.01904296875
post adversarial -- adversaire ready after one adv epoch training  0.021484375
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.0224609375
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.021484375
post adversarial -- adversaire ready after one adv epoch training  0.0263671875
post adversarial -- adversaire ready after one adv epoch training  0.02294921875
post adversarial -- adversaire ready after one adv epoch training  0.03076171875
post adversarial -- adversaire ready after one adv epoch training  0.0234375
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.02685546875
post adversarial -- adversaire ready after one adv epoch training  0.02490234375
post adversarial -- adversaire ready after one adv epoch training  0.025390625
post adversarial -- adversaire ready after one adv epoch training  0.0234375
post adversarial -- adversaire ready after one adv epoch training  0.0205078125
post adversarial -- adversaire ready after one adv epoch training  0.02490234375
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.025390625
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.0263671875
post adversarial -- adversaire ready after one adv epoch training  0.02734375
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.01904296875
post adversarial -- adversaire ready after one adv epoch training  0.02099609375
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.0283203125
post adversarial -- adversaire ready after one adv epoch training  0.0224609375
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.02099609375
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.03466796875
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.02587890625
post adversarial -- adversaire ready after one adv epoch training  0.02880859375
post adversarial -- adversaire ready after one adv epoch training  0.02734375
post adversarial -- adversaire ready after one adv epoch training  0.02880859375
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.02587890625
post adversarial -- adversaire ready after one adv epoch training  0.02880859375
post adversarial -- adversaire ready after one adv epoch training  0.02783203125
post adversarial -- adversaire ready after one adv epoch training  0.02685546875
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.02783203125
post adversarial -- adversaire ready after one adv epoch training  0.0283203125
post adversarial -- adversaire ready after one adv epoch training  0.02880859375
post adversarial -- adversaire ready after one adv epoch training  0.03515625
post adversarial -- adversaire ready after one adv epoch training  0.02587890625
post adversarial -- adversaire ready after one adv epoch training  0.0244140625
post adversarial -- adversaire ready after one adv epoch training  0.03076171875
post adversarial -- adversaire ready after one adv epoch training  0.02978515625
post adversarial -- adversaire ready after one adv epoch training  0.02490234375
post adversarial -- adversaire ready after one adv epoch training  0.02685546875
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.01904296875
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.02685546875
post adversarial -- adversaire ready after one adv epoch training  0.02880859375
post adversarial -- adversaire ready after one adv epoch training  0.0400390625
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.03076171875
post adversarial -- adversaire ready after one adv epoch training  0.02880859375
post adversarial -- adversaire ready after one adv epoch training  0.0283203125
post adversarial -- adversaire ready after one adv epoch training  0.02734375
post adversarial -- adversaire ready after one adv epoch training  0.03466796875
post adversarial -- adversaire ready after one adv epoch training  0.02685546875
post adversarial -- adversaire ready after one adv epoch training  0.02978515625
post adversarial -- adversaire ready after one adv epoch training  0.02734375
post adversarial -- adversaire ready after one adv epoch training  0.03076171875
post adversarial -- adversaire ready after one adv epoch training  0.02880859375
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.02685546875
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.029296875
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.0322265625

post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.0361328125
post adversarial -- adversaire ready after one adv epoch training  0.03662109375
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.0263671875
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.03466796875
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.029296875
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.0283203125
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.02978515625
post adversarial -- adversaire ready after one adv epoch training  0.02978515625
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.0341796875
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.0400390625
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.0361328125
post adversarial -- adversaire ready after one adv epoch training  0.03515625
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.03466796875
post adversarial -- adversaire ready after one adv epoch training  0.0341796875
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.0283203125
post adversarial -- adversaire ready after one adv epoch training  0.03662109375
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.0341796875
post adversarial -- adversaire ready after one adv epoch training  0.0341796875
post adversarial -- adversaire ready after one adv epoch training  0.02978515625
post adversarial -- adversaire ready after one adv epoch training  0.03662109375
post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.0263671875
post adversarial -- adversaire ready after one adv epoch training  0.029296875
post adversarial -- adversaire ready after one adv epoch training  0.02783203125
post adversarial -- adversaire ready after one adv epoch training  0.03515625
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.04248046875
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.02734375
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.03076171875
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.0439453125
post adversarial -- adversaire ready after one adv epoch training  0.03662109375
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.03515625
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.0263671875
post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.02392578125
post adversarial -- adversaire ready after one adv epoch training  0.04248046875
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.03466796875
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.0361328125
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.03515625
post adversarial -- adversaire ready after one adv epoch training  0.0341796875

post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.04296875
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.0400390625
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.0341796875
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.04052734375
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.03466796875
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.0361328125
post adversarial -- adversaire ready after one adv epoch training  0.039017342031002045
Training // Epoch 7 //  Total r_cost = 188838.56787  Total a_cost = 0.04935 total pre adversarial accuracy = 0.02651 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 9201 ms negative Sampling time : 8169 ms negative samples : 400730
precision_1	[0.4538706],	||	 precision_5	[0.3471898],	||	 precision_10	[0.2985154],	||	 precision_15	[0.2629905]
recall_1   	[0.0316480],	||	 recall_5   	[0.1171587],	||	 recall_10   	[0.1907594],	||	 recall_15   	[0.2455168]
f_measure_1	[0.0591701],	||	 f_measure_5	[0.1751973],	||	 f_measure_10	[0.2327715],	||	 f_measure_15	[0.2539534]
ndcg_1     	[0.4538706],	||	 ndcg_5     	[0.3721390],	||	 ndcg_10     	[0.3556687],	||	 ndcg_15     	[0.3509517]
Metrics for user type	 M
precision_1	[0.4686567],	||	 precision_5	[0.3680597],	||	 precision_10	[0.3168657],	||	 precision_15	[0.2800995]
recall_1	[0.0316163],	||	 recall_5	[0.1182353],	||	 recall_10	[0.1942361],	||	 recall_15	[0.2495867]
ndcg_1	[0.4686567],	||	 ndcg_5	[0.3919020],	||	 ndcg_10	[0.3731241],	||	 ndcg_15	[0.3671256]
AUC per user type	[0.9108494]
Metrics for user type	 F
precision_1	[0.4175824],	||	 precision_5	[0.2959707],	||	 precision_10	[0.2534799],	||	 precision_15	[0.2210012]
recall_1	[0.0317256],	||	 recall_5	[0.1145162],	||	 recall_10	[0.1822269],	||	 recall_15	[0.2355284]
ndcg_1	[0.4175824],	||	 ndcg_5	[0.3236364],	||	 ndcg_10	[0.3128295],	||	 ndcg_15	[0.3112576]
AUC per user type	[0.9089296]
AUC global is:  0.9102936234053881
post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.04052734375
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.04931640625
post adversarial -- adversaire ready after one adv epoch training  0.0400390625
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.0439453125
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.03515625
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.0361328125
post adversarial -- adversaire ready after one adv epoch training  0.04248046875
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.03271484375
post adversarial -- adversaire ready after one adv epoch training  0.0322265625
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.0361328125
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.0361328125
post adversarial -- adversaire ready after one adv epoch training  0.03125
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.0400390625
post adversarial -- adversaire ready after one adv epoch training  0.04541015625
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.0400390625
post adversarial -- adversaire ready after one adv epoch training  0.029296875
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.0302734375
post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.03369140625
post adversarial -- adversaire ready after one adv epoch training  0.03662109375
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.02734375
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.03515625
post adversarial -- adversaire ready after one adv epoch training  0.037109375
post adversarial -- adversaire ready after one adv epoch training  0.03173828125
post adversarial -- adversaire ready after one adv epoch training  0.0400390625
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.0439453125
post adversarial -- adversaire ready after one adv epoch training  0.033203125
post adversarial -- adversaire ready after one adv epoch training  0.04296875
post adversarial -- adversaire ready after one adv epoch training  0.03466796875
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.03662109375
post adversarial -- adversaire ready after one adv epoch training  0.03759765625

post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.04638671875
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.0341796875
post adversarial -- adversaire ready after one adv epoch training  0.03564453125
post adversarial -- adversaire ready after one adv epoch training  0.029296875
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.04931640625
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.04443359375
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.0361328125
post adversarial -- adversaire ready after one adv epoch training  0.03466796875
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.0439453125
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.04638671875
post adversarial -- adversaire ready after one adv epoch training  0.04736328125
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.046875
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.04638671875
post adversarial -- adversaire ready after one adv epoch training  0.0380859375
post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.04833984375
post adversarial -- adversaire ready after one adv epoch training  0.05126953125
post adversarial -- adversaire ready after one adv epoch training  0.04443359375
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.03759765625
post adversarial -- adversaire ready after one adv epoch training  0.04443359375
post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.05126953125
post adversarial -- adversaire ready after one adv epoch training  0.046875
post adversarial -- adversaire ready after one adv epoch training  0.04248046875
post adversarial -- adversaire ready after one adv epoch training  0.03955078125
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.0546875
post adversarial -- adversaire ready after one adv epoch training  0.04931640625
post adversarial -- adversaire ready after one adv epoch training  0.0556640625
post adversarial -- adversaire ready after one adv epoch training  0.0439453125
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.046875
post adversarial -- adversaire ready after one adv epoch training  0.046875
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.04736328125
post adversarial -- adversaire ready after one adv epoch training  0.04638671875
post adversarial -- adversaire ready after one adv epoch training  0.0400390625
post adversarial -- adversaire ready after one adv epoch training  0.04248046875
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.05224609375
post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.0556640625
post adversarial -- adversaire ready after one adv epoch training  0.041015625
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.04833984375
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.04833984375
post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.05419921875
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.05419921875
post adversarial -- adversaire ready after one adv epoch training  0.0439453125
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.04931640625
post adversarial -- adversaire ready after one adv epoch training  0.04541015625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.04638671875
post adversarial -- adversaire ready after one adv epoch training  0.0390625
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.05126953125

post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.04443359375
post adversarial -- adversaire ready after one adv epoch training  0.04443359375
post adversarial -- adversaire ready after one adv epoch training  0.05419921875
post adversarial -- adversaire ready after one adv epoch training  0.04931640625
post adversarial -- adversaire ready after one adv epoch training  0.04638671875
post adversarial -- adversaire ready after one adv epoch training  0.04638671875
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.046875
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.05224609375
post adversarial -- adversaire ready after one adv epoch training  0.04541015625
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.0419921875
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.04541015625
post adversarial -- adversaire ready after one adv epoch training  0.04248046875
post adversarial -- adversaire ready after one adv epoch training  0.05517578125
post adversarial -- adversaire ready after one adv epoch training  0.05322265625
post adversarial -- adversaire ready after one adv epoch training  0.05126953125
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.04296875
post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.04150390625
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.0537109375
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.05322265625
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.05908203125
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.05224609375
post adversarial -- adversaire ready after one adv epoch training  0.0546875
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.05322265625
post adversarial -- adversaire ready after one adv epoch training  0.05126953125
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.04541015625
post adversarial -- adversaire ready after one adv epoch training  0.04052734375
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.05126953125
post adversarial -- adversaire ready after one adv epoch training  0.04931640625
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.04638671875
post adversarial -- adversaire ready after one adv epoch training  0.05419921875
post adversarial -- adversaire ready after one adv epoch training  0.04833984375
post adversarial -- adversaire ready after one adv epoch training  0.04248046875
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.05224609375
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.05419921875
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.05224609375
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.0556640625
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.0458984375
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.04345703125
post adversarial -- adversaire ready after one adv epoch training  0.0478515625
post adversarial -- adversaire ready after one adv epoch training  0.03857421875
post adversarial -- adversaire ready after one adv epoch training  0.05908203125
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.04833984375
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.05224609375
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.04541015625
post adversarial -- adversaire ready after one adv epoch training  0.05126953125
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.0546875
post adversarial -- adversaire ready after one adv epoch training  0.05419921875
post adversarial -- adversaire ready after one adv epoch training  0.060546875
post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.04931640625
post adversarial -- adversaire ready after one adv epoch training  0.05029296875
post adversarial -- adversaire ready after one adv epoch training  0.044921875
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.05322265625
post adversarial -- adversaire ready after one adv epoch training  0.05322265625
post adversarial -- adversaire ready after one adv epoch training  0.06103515625

post adversarial -- adversaire ready after one adv epoch training  0.0546875
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.05419921875
post adversarial -- adversaire ready after one adv epoch training  0.05322265625
post adversarial -- adversaire ready after one adv epoch training  0.05322265625
post adversarial -- adversaire ready after one adv epoch training  0.0546875
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.05908203125
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.06298828125
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.05859375
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.060546875
post adversarial -- adversaire ready after one adv epoch training  0.0693359375
post adversarial -- adversaire ready after one adv epoch training  0.06005859375
post adversarial -- adversaire ready after one adv epoch training  0.0537109375
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.06298828125
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.05859375
post adversarial -- adversaire ready after one adv epoch training  0.0498046875
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.060546875
post adversarial -- adversaire ready after one adv epoch training  0.05419921875
post adversarial -- adversaire ready after one adv epoch training  0.0546875
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.060546875
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.04541015625
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.0556640625
post adversarial -- adversaire ready after one adv epoch training  0.0556640625
post adversarial -- adversaire ready after one adv epoch training  0.05126953125
post adversarial -- adversaire ready after one adv epoch training  0.0556640625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.0625
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.04541015625
post adversarial -- adversaire ready after one adv epoch training  0.06005859375
post adversarial -- adversaire ready after one adv epoch training  0.052734375
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.048828125
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.0556640625
post adversarial -- adversaire ready after one adv epoch training  0.0673828125
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.0693359375
post adversarial -- adversaire ready after one adv epoch training  0.05908203125
post adversarial -- adversaire ready after one adv epoch training  0.05078125
post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.0615234375
post adversarial -- adversaire ready after one adv epoch training  0.05859375
post adversarial -- adversaire ready after one adv epoch training  0.04931640625
post adversarial -- adversaire ready after one adv epoch training  0.0634765625
post adversarial -- adversaire ready after one adv epoch training  0.06640625
post adversarial -- adversaire ready after one adv epoch training  0.06005859375
post adversarial -- adversaire ready after one adv epoch training  0.068359375
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.04736328125
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.05517578125
post adversarial -- adversaire ready after one adv epoch training  0.068359375
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.05126953125
post adversarial -- adversaire ready after one adv epoch training  0.0625
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.05517578125
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.0634765625
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.05224609375
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.0625
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.06494140625
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.0615234375
post adversarial -- adversaire ready after one adv epoch training  0.06494140625
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.0625
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.05322265625
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.05635838210582733
Training // Epoch 8 //  Total r_cost = 188582.73605  Total a_cost = 0.01593 total pre adversarial accuracy = 0.04929 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 8960 ms negative Sampling time : 9363 ms negative samples : 400730

precision_1	[0.4591729],	||	 precision_5	[0.3512195],	||	 precision_10	[0.2974549],	||	 precision_15	[0.2668788]
recall_1   	[0.0329943],	||	 recall_5   	[0.1178434],	||	 recall_10   	[0.1887281],	||	 recall_15   	[0.2490697]
f_measure_1	[0.0615648],	||	 f_measure_5	[0.1764748],	||	 f_measure_10	[0.2309340],	||	 f_measure_15	[0.2576669]
ndcg_1     	[0.4591729],	||	 ndcg_5     	[0.3782105],	||	 ndcg_10     	[0.3577963],	||	 ndcg_15     	[0.3564719]
Metrics for user type	 M
precision_1	[0.4791045],	||	 precision_5	[0.3758209],	||	 precision_10	[0.3185075],	||	 precision_15	[0.2848756]
recall_1	[0.0336775],	||	 recall_5	[0.1215361],	||	 recall_10	[0.1940543],	||	 recall_15	[0.2531426]
ndcg_1	[0.4791045],	||	 ndcg_5	[0.4012242],	||	 ndcg_10	[0.3781078],	||	 ndcg_15	[0.3741168]
AUC per user type	[0.9101081]
Metrics for user type	 F
precision_1	[0.4102564],	||	 precision_5	[0.2908425],	||	 precision_10	[0.2457875],	||	 precision_15	[0.2227106]
recall_1	[0.0313175],	||	 recall_5	[0.1087805],	||	 recall_10	[0.1756564],	||	 recall_15	[0.2390740]
ndcg_1	[0.4102564],	||	 ndcg_5	[0.3217299],	||	 ndcg_10	[0.3079476],	||	 ndcg_15	[0.3131674]
AUC per user type	[0.9091351]
AUC global is:  0.909826405751992
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.07080078125
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.05859375
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.0673828125
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.0634765625
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.05908203125
post adversarial -- adversaire ready after one adv epoch training  0.05615234375
post adversarial -- adversaire ready after one adv epoch training  0.0517578125
post adversarial -- adversaire ready after one adv epoch training  0.06201171875
post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.06201171875
post adversarial -- adversaire ready after one adv epoch training  0.06494140625
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.060546875
post adversarial -- adversaire ready after one adv epoch training  0.06201171875
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.056640625
post adversarial -- adversaire ready after one adv epoch training  0.0546875
post adversarial -- adversaire ready after one adv epoch training  0.06640625
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.0693359375
post adversarial -- adversaire ready after one adv epoch training  0.0673828125
post adversarial -- adversaire ready after one adv epoch training  0.05908203125
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.06494140625
post adversarial -- adversaire ready after one adv epoch training  0.06201171875
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.06201171875
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.06640625
post adversarial -- adversaire ready after one adv epoch training  0.0625
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.05810546875
post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.068359375
post adversarial -- adversaire ready after one adv epoch training  0.0595703125
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.07080078125
post adversarial -- adversaire ready after one adv epoch training  0.06298828125
post adversarial -- adversaire ready after one adv epoch training  0.0693359375
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.06298828125
post adversarial -- adversaire ready after one adv epoch training  0.05224609375
post adversarial -- adversaire ready after one adv epoch training  0.05908203125
post adversarial -- adversaire ready after one adv epoch training  0.06982421875
post adversarial -- adversaire ready after one adv epoch training  0.0634765625
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.06982421875
post adversarial -- adversaire ready after one adv epoch training  0.07080078125
post adversarial -- adversaire ready after one adv epoch training  0.0615234375
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.064453125
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.06787109375
post adversarial -- adversaire ready after one adv epoch training  0.0615234375
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.06787109375
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.060546875
post adversarial -- adversaire ready after one adv epoch training  0.05908203125
post adversarial -- adversaire ready after one adv epoch training  0.07080078125
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.06494140625
post adversarial -- adversaire ready after one adv epoch training  0.0693359375

post adversarial -- adversaire ready after one adv epoch training  0.05712890625
post adversarial -- adversaire ready after one adv epoch training  0.06982421875
post adversarial -- adversaire ready after one adv epoch training  0.0615234375
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.0693359375
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.06005859375
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.0625
post adversarial -- adversaire ready after one adv epoch training  0.07080078125
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.07470703125
post adversarial -- adversaire ready after one adv epoch training  0.0634765625
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.072265625
post adversarial -- adversaire ready after one adv epoch training  0.07568359375
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.06640625
post adversarial -- adversaire ready after one adv epoch training  0.0693359375
post adversarial -- adversaire ready after one adv epoch training  0.06787109375
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.06787109375
post adversarial -- adversaire ready after one adv epoch training  0.0693359375
post adversarial -- adversaire ready after one adv epoch training  0.0673828125
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.0625
post adversarial -- adversaire ready after one adv epoch training  0.06396484375
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.068359375
post adversarial -- adversaire ready after one adv epoch training  0.06494140625
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.0712890625
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.06787109375
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.0712890625
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.07666015625
post adversarial -- adversaire ready after one adv epoch training  0.08056640625
post adversarial -- adversaire ready after one adv epoch training  0.0673828125
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.07373046875
post adversarial -- adversaire ready after one adv epoch training  0.06689453125
post adversarial -- adversaire ready after one adv epoch training  0.08349609375
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.07666015625
post adversarial -- adversaire ready after one adv epoch training  0.07958984375
post adversarial -- adversaire ready after one adv epoch training  0.0712890625
post adversarial -- adversaire ready after one adv epoch training  0.07373046875
post adversarial -- adversaire ready after one adv epoch training  0.0654296875
post adversarial -- adversaire ready after one adv epoch training  0.07666015625
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.068359375
post adversarial -- adversaire ready after one adv epoch training  0.07763671875
post adversarial -- adversaire ready after one adv epoch training  0.07470703125
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.07763671875
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.0712890625
post adversarial -- adversaire ready after one adv epoch training  0.068359375
post adversarial -- adversaire ready after one adv epoch training  0.068359375
post adversarial -- adversaire ready after one adv epoch training  0.0576171875
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.07470703125
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.06982421875
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.06103515625
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.0712890625
post adversarial -- adversaire ready after one adv epoch training  0.0693359375
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.072265625
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.07470703125
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.06787109375
post adversarial -- adversaire ready after one adv epoch training  0.08154296875
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.06689453125

post adversarial -- adversaire ready after one adv epoch training  0.07373046875
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.07373046875
post adversarial -- adversaire ready after one adv epoch training  0.07373046875
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.07568359375
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.07373046875
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.06787109375
post adversarial -- adversaire ready after one adv epoch training  0.060546875
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.07958984375
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.0673828125
post adversarial -- adversaire ready after one adv epoch training  0.0810546875
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.072265625
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.07080078125
post adversarial -- adversaire ready after one adv epoch training  0.06494140625
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.0712890625
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.07763671875
post adversarial -- adversaire ready after one adv epoch training  0.07080078125
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.0810546875
post adversarial -- adversaire ready after one adv epoch training  0.072265625
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.07568359375
post adversarial -- adversaire ready after one adv epoch training  0.07470703125
post adversarial -- adversaire ready after one adv epoch training  0.07568359375
post adversarial -- adversaire ready after one adv epoch training  0.06640625
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.07763671875
post adversarial -- adversaire ready after one adv epoch training  0.07373046875
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.06591796875
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.07666015625
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.0625
post adversarial -- adversaire ready after one adv epoch training  0.06298828125
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.07666015625
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.06884765625
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.08056640625
post adversarial -- adversaire ready after one adv epoch training  0.09521484375
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.07666015625
post adversarial -- adversaire ready after one adv epoch training  0.0703125
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.07958984375
post adversarial -- adversaire ready after one adv epoch training  0.08056640625
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.07568359375
post adversarial -- adversaire ready after one adv epoch training  0.0751953125

post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.07568359375
post adversarial -- adversaire ready after one adv epoch training  0.0712890625
post adversarial -- adversaire ready after one adv epoch training  0.07958984375
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.0849609375
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.0810546875
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.08154296875
post adversarial -- adversaire ready after one adv epoch training  0.08154296875
post adversarial -- adversaire ready after one adv epoch training  0.07568359375
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.07373046875
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.07177734375
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.08203125
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.0849609375
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.087890625
post adversarial -- adversaire ready after one adv epoch training  0.08935546875
post adversarial -- adversaire ready after one adv epoch training  0.08349609375
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.07958984375
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.08544921875
post adversarial -- adversaire ready after one adv epoch training  0.07421875
post adversarial -- adversaire ready after one adv epoch training  0.091796875
post adversarial -- adversaire ready after one adv epoch training  0.0849609375
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.08984375
post adversarial -- adversaire ready after one adv epoch training  0.08203125
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.08154296875
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.08544921875
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.08056640625
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.07666015625
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.0732421875
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.08349609375
post adversarial -- adversaire ready after one adv epoch training  0.07470703125
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.07958984375
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.0849609375
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.078125
post adversarial -- adversaire ready after one adv epoch training  0.08544921875
post adversarial -- adversaire ready after one adv epoch training  0.08544921875
post adversarial -- adversaire ready after one adv epoch training  0.0927734375
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.07947976887226105
Training // Epoch 9 //  Total r_cost = 188370.71588  Total a_cost = 0.00766 total pre adversarial accuracy = 0.07332 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 13421 ms negative Sampling time : 16889 ms negative samples : 400730
precision_1	[0.4369035],	||	 precision_5	[0.3431601],	||	 precision_10	[0.2969247],	||	 precision_15	[0.2653234]
recall_1   	[0.0318679],	||	 recall_5   	[0.1163999],	||	 recall_10   	[0.1899970],	||	 recall_15   	[0.2485100]
f_measure_1	[0.0594029],	||	 f_measure_5	[0.1738350],	||	 f_measure_10	[0.2317202],	||	 f_measure_15	[0.2566416]
ndcg_1     	[0.4369035],	||	 ndcg_5     	[0.3658881],	||	 ndcg_10     	[0.3521149],	||	 ndcg_15     	[0.3509433]
Metrics for user type	 M
precision_1	[0.4626866],	||	 precision_5	[0.3665672],	||	 precision_10	[0.3155224],	||	 precision_15	[0.2800995]
recall_1	[0.0330774],	||	 recall_5	[0.1183687],	||	 recall_10	[0.1926986],	||	 recall_15	[0.2485600]
ndcg_1	[0.4626866],	||	 ndcg_5	[0.3896879],	||	 ndcg_10	[0.3715187],	||	 ndcg_15	[0.3664966]
AUC per user type	[0.9107733]
Metrics for user type	 F
precision_1	[0.3736264],	||	 precision_5	[0.2857143],	||	 precision_10	[0.2512821],	||	 precision_15	[0.2290598]
recall_1	[0.0288994],	||	 recall_5	[0.1115683],	||	 recall_10	[0.1833667],	||	 recall_15	[0.2483873]
ndcg_1	[0.3736264],	||	 ndcg_5	[0.3074782],	||	 ndcg_10	[0.3044936],	||	 ndcg_15	[0.3127722]
AUC per user type	[0.9105309]

AUC global is:  0.9107031359170589
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.0849609375
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.08154296875
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.08203125
post adversarial -- adversaire ready after one adv epoch training  0.0751953125
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.07470703125
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.07275390625
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.08056640625
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.07763671875
post adversarial -- adversaire ready after one adv epoch training  0.0712890625
post adversarial -- adversaire ready after one adv epoch training  0.076171875
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.08544921875
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.0849609375
post adversarial -- adversaire ready after one adv epoch training  0.0927734375
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.0966796875
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.091796875
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.07861328125
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.09423828125
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.087890625
post adversarial -- adversaire ready after one adv epoch training  0.091796875
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.08203125
post adversarial -- adversaire ready after one adv epoch training  0.08203125
post adversarial -- adversaire ready after one adv epoch training  0.0947265625
post adversarial -- adversaire ready after one adv epoch training  0.107421875
post adversarial -- adversaire ready after one adv epoch training  0.08154296875
post adversarial -- adversaire ready after one adv epoch training  0.0849609375
post adversarial -- adversaire ready after one adv epoch training  0.08056640625
post adversarial -- adversaire ready after one adv epoch training  0.08349609375
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.091796875
post adversarial -- adversaire ready after one adv epoch training  0.0771484375
post adversarial -- adversaire ready after one adv epoch training  0.08984375
post adversarial -- adversaire ready after one adv epoch training  0.09423828125
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.08935546875
post adversarial -- adversaire ready after one adv epoch training  0.0947265625
post adversarial -- adversaire ready after one adv epoch training  0.0791015625
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.08544921875
post adversarial -- adversaire ready after one adv epoch training  0.10888671875
post adversarial -- adversaire ready after one adv epoch training  0.091796875
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.08544921875
post adversarial -- adversaire ready after one adv epoch training  0.07763671875
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.09521484375
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.0859375
post adversarial -- adversaire ready after one adv epoch training  0.0869140625

post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.080078125
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.0810546875
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.091796875
post adversarial -- adversaire ready after one adv epoch training  0.07470703125
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.091796875
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.08349609375
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.08447265625
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.0927734375
post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.07666015625
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.09521484375
post adversarial -- adversaire ready after one adv epoch training  0.09423828125
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.083984375
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.0927734375
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.08935546875
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.1025390625
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.091796875
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.0810546875
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.09423828125
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.09521484375
post adversarial -- adversaire ready after one adv epoch training  0.08056640625
post adversarial -- adversaire ready after one adv epoch training  0.08984375
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.087890625
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.10546875
post adversarial -- adversaire ready after one adv epoch training  0.08984375
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.0966796875
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.09423828125
post adversarial -- adversaire ready after one adv epoch training  0.08740234375
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.10009765625
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.08935546875
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.111328125
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.09521484375
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.09716796875
post adversarial -- adversaire ready after one adv epoch training  0.0869140625
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.08642578125

post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.09716796875
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.0947265625
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.10009765625
post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.11474609375
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.09912109375
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.11181640625
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.09912109375
post adversarial -- adversaire ready after one adv epoch training  0.08984375
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.09423828125
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.08984375
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.0966796875
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.09716796875
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.08251953125
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.10400390625
post adversarial -- adversaire ready after one adv epoch training  0.09228515625
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.0830078125
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.0947265625
post adversarial -- adversaire ready after one adv epoch training  0.09716796875
post adversarial -- adversaire ready after one adv epoch training  0.10400390625
post adversarial -- adversaire ready after one adv epoch training  0.09033203125
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.08984375
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.11474609375
post adversarial -- adversaire ready after one adv epoch training  0.107421875
post adversarial -- adversaire ready after one adv epoch training  0.09912109375
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.10009765625
post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.111328125
post adversarial -- adversaire ready after one adv epoch training  0.0966796875
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.109375
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.10546875
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.0966796875
post adversarial -- adversaire ready after one adv epoch training  0.10546875
post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.0966796875
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.10546875
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.11181640625
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.10546875
post adversarial -- adversaire ready after one adv epoch training  0.09912109375
post adversarial -- adversaire ready after one adv epoch training  0.09716796875
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.09912109375
post adversarial -- adversaire ready after one adv epoch training  0.09130859375
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.10888671875
post adversarial -- adversaire ready after one adv epoch training  0.0947265625
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.1025390625
post adversarial -- adversaire ready after one adv epoch training  0.11328125
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.1025390625
post adversarial -- adversaire ready after one adv epoch training  0.1044921875

post adversarial -- adversaire ready after one adv epoch training  0.10400390625
post adversarial -- adversaire ready after one adv epoch training  0.09423828125
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.09521484375
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.0947265625
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.08642578125
post adversarial -- adversaire ready after one adv epoch training  0.09912109375
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.09375
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.1103515625
post adversarial -- adversaire ready after one adv epoch training  0.10546875
post adversarial -- adversaire ready after one adv epoch training  0.0927734375
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.08837890625
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.1064453125
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.09912109375
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.09716796875
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.09912109375
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.08935546875
post adversarial -- adversaire ready after one adv epoch training  0.09326171875
post adversarial -- adversaire ready after one adv epoch training  0.09521484375
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.10400390625
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.10009765625
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.111328125
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.0888671875
post adversarial -- adversaire ready after one adv epoch training  0.09716796875
post adversarial -- adversaire ready after one adv epoch training  0.0966796875
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.10009765625
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.0947265625
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.08815029263496399
Training // Epoch 10 //  Total r_cost = 188903.91003  Total a_cost = 0.00439 total pre adversarial accuracy = 0.09461 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 10470 ms negative Sampling time : 11038 ms negative samples : 400730
precision_1	[0.4644751],	||	 precision_5	[0.3537646],	||	 precision_10	[0.2973489],	||	 precision_15	[0.2665253]
recall_1   	[0.0333770],	||	 recall_5   	[0.1167404],	||	 recall_10   	[0.1895790],	||	 recall_15   	[0.2462604]
f_measure_1	[0.0622786],	||	 f_measure_5	[0.1755502],	||	 f_measure_10	[0.2315378],	||	 f_measure_15	[0.2559924]
ndcg_1     	[0.4644751],	||	 ndcg_5     	[0.3813010],	||	 ndcg_10     	[0.3585165],	||	 ndcg_15     	[0.3559930]
Metrics for user type	 M
precision_1	[0.4776119],	||	 precision_5	[0.3704478],	||	 precision_10	[0.3170149],	||	 precision_15	[0.2824876]
recall_1	[0.0325616],	||	 recall_5	[0.1157710],	||	 recall_10	[0.1926100],	||	 recall_15	[0.2486594]
ndcg_1	[0.4776119],	||	 ndcg_5	[0.3980672],	||	 ndcg_10	[0.3762007],	||	 ndcg_15	[0.3703893]
AUC per user type	[0.9111173]
Metrics for user type	 F
precision_1	[0.4322344],	||	 precision_5	[0.3128205],	||	 precision_10	[0.2490842],	||	 precision_15	[0.2273504]
recall_1	[0.0353781],	||	 recall_5	[0.1191197],	||	 recall_10	[0.1821400],	||	 recall_15	[0.2403728]
ndcg_1	[0.4322344],	||	 ndcg_5	[0.3401532],	||	 ndcg_10	[0.3151157],	||	 ndcg_15	[0.3206613]
AUC per user type	[0.9080513]
AUC global is:  0.910229715068861
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.1064453125
post adversarial -- adversaire ready after one adv epoch training  0.107421875
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.1025390625
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.10888671875
post adversarial -- adversaire ready after one adv epoch training  0.1064453125
post adversarial -- adversaire ready after one adv epoch training  0.09765625
post adversarial -- adversaire ready after one adv epoch training  0.109375
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.11181640625
post adversarial -- adversaire ready after one adv epoch training  0.11181640625

post adversarial -- adversaire ready after one adv epoch training  0.11669921875
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.1064453125
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.10009765625
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.10888671875
post adversarial -- adversaire ready after one adv epoch training  0.0947265625
post adversarial -- adversaire ready after one adv epoch training  0.11474609375
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.10888671875
post adversarial -- adversaire ready after one adv epoch training  0.11572265625
post adversarial -- adversaire ready after one adv epoch training  0.1103515625
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.111328125
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.11572265625
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.107421875
post adversarial -- adversaire ready after one adv epoch training  0.10546875
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.11767578125
post adversarial -- adversaire ready after one adv epoch training  0.0908203125
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.1064453125
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.1103515625
post adversarial -- adversaire ready after one adv epoch training  0.10205078125
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.10400390625
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.103515625
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.1162109375
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.10546875
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.0986328125
post adversarial -- adversaire ready after one adv epoch training  0.10009765625
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.109375
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.1103515625
post adversarial -- adversaire ready after one adv epoch training  0.111328125
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.099609375
post adversarial -- adversaire ready after one adv epoch training  0.1025390625
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.1103515625
post adversarial -- adversaire ready after one adv epoch training  0.10888671875
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.11328125
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.11376953125
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.11474609375
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.125
post adversarial -- adversaire ready after one adv epoch training  0.109375
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.10107421875
post adversarial -- adversaire ready after one adv epoch training  0.11474609375

post adversarial -- adversaire ready after one adv epoch training  0.11572265625
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.11669921875
post adversarial -- adversaire ready after one adv epoch training  0.11669921875
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.1162109375
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.11328125
post adversarial -- adversaire ready after one adv epoch training  0.107421875
post adversarial -- adversaire ready after one adv epoch training  0.12109375
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.1181640625
post adversarial -- adversaire ready after one adv epoch training  0.11572265625
post adversarial -- adversaire ready after one adv epoch training  0.1015625
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.1162109375
post adversarial -- adversaire ready after one adv epoch training  0.11181640625
post adversarial -- adversaire ready after one adv epoch training  0.11767578125
post adversarial -- adversaire ready after one adv epoch training  0.095703125
post adversarial -- adversaire ready after one adv epoch training  0.11474609375
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.11376953125
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.11376953125
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.11376953125
post adversarial -- adversaire ready after one adv epoch training  0.1162109375
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.13037109375
post adversarial -- adversaire ready after one adv epoch training  0.11328125
post adversarial -- adversaire ready after one adv epoch training  0.1064453125
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.11669921875
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.09619140625
post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.09814453125
post adversarial -- adversaire ready after one adv epoch training  0.1201171875
post adversarial -- adversaire ready after one adv epoch training  0.109375
post adversarial -- adversaire ready after one adv epoch training  0.1005859375
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.1181640625
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.1103515625
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.10400390625
post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.10400390625
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.10498046875
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.1044921875
post adversarial -- adversaire ready after one adv epoch training  0.12060546875
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.12939453125
post adversarial -- adversaire ready after one adv epoch training  0.10302734375
post adversarial -- adversaire ready after one adv epoch training  0.1181640625
post adversarial -- adversaire ready after one adv epoch training  0.12109375
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.10791015625
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.10595703125
post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.12548828125
post adversarial -- adversaire ready after one adv epoch training  0.10693359375
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.12060546875
post adversarial -- adversaire ready after one adv epoch training  0.1162109375
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.12548828125
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.11669921875
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.111328125

post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.11669921875
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.11474609375
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.11572265625
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.1162109375
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.1083984375
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.11328125
post adversarial -- adversaire ready after one adv epoch training  0.11181640625
post adversarial -- adversaire ready after one adv epoch training  0.1201171875
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.11767578125
post adversarial -- adversaire ready after one adv epoch training  0.11474609375
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.11083984375
post adversarial -- adversaire ready after one adv epoch training  0.10888671875
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.11767578125
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.11767578125
post adversarial -- adversaire ready after one adv epoch training  0.12890625
post adversarial -- adversaire ready after one adv epoch training  0.11376953125
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.11279296875
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.1201171875
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.11474609375
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.126953125
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.1201171875
post adversarial -- adversaire ready after one adv epoch training  0.11376953125
post adversarial -- adversaire ready after one adv epoch training  0.12109375
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.12109375
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.11669921875
post adversarial -- adversaire ready after one adv epoch training  0.10986328125
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.12890625
post adversarial -- adversaire ready after one adv epoch training  0.1162109375
post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.12890625
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.126953125
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.12939453125
post adversarial -- adversaire ready after one adv epoch training  0.1201171875
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.125
post adversarial -- adversaire ready after one adv epoch training  0.1181640625
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.1181640625
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.1181640625
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.13134765625
post adversarial -- adversaire ready after one adv epoch training  0.1181640625
post adversarial -- adversaire ready after one adv epoch training  0.1171875

post adversarial -- adversaire ready after one adv epoch training  0.11376953125
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.11376953125
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.109375
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.1142578125
post adversarial -- adversaire ready after one adv epoch training  0.12939453125
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.11328125
post adversarial -- adversaire ready after one adv epoch training  0.12109375
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.1171875
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.1298828125
post adversarial -- adversaire ready after one adv epoch training  0.13525390625
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.12890625
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.1298828125
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1298828125
post adversarial -- adversaire ready after one adv epoch training  0.1123046875
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.13525390625
post adversarial -- adversaire ready after one adv epoch training  0.1318359375
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.130859375
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.1286127120256424
Training // Epoch 11 //  Total r_cost = 188782.53235  Total a_cost = 0.00278 total pre adversarial accuracy = 0.11570 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 10540 ms negative Sampling time : 12136 ms negative samples : 400730
precision_1	[0.4750795],	||	 precision_5	[0.3571580],	||	 precision_10	[0.2985154],	||	 precision_15	[0.2689290]
recall_1   	[0.0353226],	||	 recall_5   	[0.1207096],	||	 recall_10   	[0.1918943],	||	 recall_15   	[0.2496770]
f_measure_1	[0.0657562],	||	 f_measure_5	[0.1804366],	||	 f_measure_10	[0.2336145],	||	 f_measure_15	[0.2589457]
ndcg_1     	[0.4750795],	||	 ndcg_5     	[0.3839092],	||	 ndcg_10     	[0.3614074],	||	 ndcg_15     	[0.3601911]
Metrics for user type	 M
precision_1	[0.4880597],	||	 precision_5	[0.3797015],	||	 precision_10	[0.3185075],	||	 precision_15	[0.2866667]
recall_1	[0.0344001],	||	 recall_5	[0.1228001],	||	 recall_10	[0.1962057],	||	 recall_15	[0.2534176]
ndcg_1	[0.4880597],	||	 ndcg_5	[0.4046314],	||	 ndcg_10	[0.3798295],	||	 ndcg_15	[0.3763705]
AUC per user type	[0.9104968]
Metrics for user type	 F
precision_1	[0.4432234],	||	 precision_5	[0.3018315],	||	 precision_10	[0.2494505],	||	 precision_15	[0.2253968]
recall_1	[0.0375867],	||	 recall_5	[0.1155789],	||	 recall_10	[0.1813133],	||	 recall_15	[0.2404968]
ndcg_1	[0.4432234],	||	 ndcg_5	[0.3330527],	||	 ndcg_10	[0.3161958],	||	 ndcg_15	[0.3204833]
AUC per user type	[0.9098479]
AUC global is:  0.9103089346697153
post adversarial -- adversaire ready after one adv epoch training  0.13330078125
post adversarial -- adversaire ready after one adv epoch training  0.11669921875
post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.1298828125
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.12939453125
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.13330078125
post adversarial -- adversaire ready after one adv epoch training  0.12109375
post adversarial -- adversaire ready after one adv epoch training  0.1298828125
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.13037109375
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.126953125
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.12060546875
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.1337890625

post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.13134765625
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.13037109375
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.12060546875
post adversarial -- adversaire ready after one adv epoch training  0.1201171875
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.13134765625
post adversarial -- adversaire ready after one adv epoch training  0.111328125
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.11962890625
post adversarial -- adversaire ready after one adv epoch training  0.125
post adversarial -- adversaire ready after one adv epoch training  0.125
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.1162109375
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.126953125
post adversarial -- adversaire ready after one adv epoch training  0.109375
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.13037109375
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.13330078125
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.12060546875
post adversarial -- adversaire ready after one adv epoch training  0.12890625
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.115234375
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.12548828125
post adversarial -- adversaire ready after one adv epoch training  0.1298828125
post adversarial -- adversaire ready after one adv epoch training  0.12939453125
post adversarial -- adversaire ready after one adv epoch training  0.125
post adversarial -- adversaire ready after one adv epoch training  0.12548828125
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.125
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.12939453125
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.1201171875
post adversarial -- adversaire ready after one adv epoch training  0.11865234375
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.12939453125
post adversarial -- adversaire ready after one adv epoch training  0.130859375
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.126953125
post adversarial -- adversaire ready after one adv epoch training  0.12158203125
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.12451171875
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.13134765625
post adversarial -- adversaire ready after one adv epoch training  0.125
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.130859375
post adversarial -- adversaire ready after one adv epoch training  0.1318359375
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.13134765625
post adversarial -- adversaire ready after one adv epoch training  0.12890625
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.13330078125
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.130859375
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.13330078125
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1318359375
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.1240234375
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.13134765625
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.12890625

post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.12255859375
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.1318359375
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.119140625
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.12841796875
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.13525390625
post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.13037109375
post adversarial -- adversaire ready after one adv epoch training  0.13134765625
post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.123046875
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.1298828125
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.1220703125
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.12353515625
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.13525390625
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.13037109375
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.14892578125
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.12939453125
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.15283203125
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.13330078125
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.13916015625

post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.1328125
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.1484375
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.12890625
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.13232421875
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.12646484375
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.12744140625
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.126953125
post adversarial -- adversaire ready after one adv epoch training  0.14892578125
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.1533203125
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.140625

post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.126953125
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.1484375
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.1533203125
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.1279296875
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.1552734375
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.1484375
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.15317918360233307
Training // Epoch 12 //  Total r_cost = 188611.76941  Total a_cost = 0.00184 total pre adversarial accuracy = 0.13610 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 10808 ms negative Sampling time : 11058 ms negative samples : 400730
precision_1	[0.4517497],	||	 precision_5	[0.3518558],	||	 precision_10	[0.3026511],	||	 precision_15	[0.2676564]
recall_1   	[0.0328322],	||	 recall_5   	[0.1184863],	||	 recall_10   	[0.1960071],	||	 recall_15   	[0.2493637]
f_measure_1	[0.0612153],	||	 f_measure_5	[0.1772756],	||	 f_measure_10	[0.2379256],	||	 f_measure_15	[0.2581864]
ndcg_1     	[0.4517497],	||	 ndcg_5     	[0.3748702],	||	 ndcg_10     	[0.3597837],	||	 ndcg_15     	[0.3554740]
Metrics for user type	 M
precision_1	[0.4567164],	||	 precision_5	[0.3776119],	||	 precision_10	[0.3234328],	||	 precision_15	[0.2855721]
recall_1	[0.0314127],	||	 recall_5	[0.1223877],	||	 recall_10	[0.1996800],	||	 recall_15	[0.2531868]
ndcg_1	[0.4567164],	||	 ndcg_5	[0.3968396],	||	 ndcg_10	[0.3781206],	||	 ndcg_15	[0.3714148]
AUC per user type	[0.9121970]
Metrics for user type	 F
precision_1	[0.4395604],	||	 precision_5	[0.2886447],	||	 precision_10	[0.2516484],	||	 precision_15	[0.2236874]
recall_1	[0.0363158],	||	 recall_5	[0.1089114],	||	 recall_10	[0.1869930],	||	 recall_15	[0.2399808]
ndcg_1	[0.4395604],	||	 ndcg_5	[0.3209525],	||	 ndcg_10	[0.3147811],	||	 ndcg_15	[0.3163518]
AUC per user type	[0.9097294]
AUC global is:  0.9114826362875184
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.1484375
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.13623046875
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.1484375
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.140625

post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.13427734375
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.15234375
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.13330078125
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.15234375
post adversarial -- adversaire ready after one adv epoch training  0.1376953125
post adversarial -- adversaire ready after one adv epoch training  0.14111328125
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.1259765625
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.15234375
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.1552734375
post adversarial -- adversaire ready after one adv epoch training  0.13671875
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.15234375
post adversarial -- adversaire ready after one adv epoch training  0.14892578125
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.13916015625
post adversarial -- adversaire ready after one adv epoch training  0.13525390625
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.13818359375
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.1337890625
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.14892578125
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.15234375
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.13330078125
post adversarial -- adversaire ready after one adv epoch training  0.15234375
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.1435546875
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.1357421875
post adversarial -- adversaire ready after one adv epoch training  0.14453125

post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.14013671875
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.1416015625
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.1455078125
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.16064453125
post adversarial -- adversaire ready after one adv epoch training  0.14208984375
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.1484375
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.1533203125
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.134765625
post adversarial -- adversaire ready after one adv epoch training  0.14892578125
post adversarial -- adversaire ready after one adv epoch training  0.15673828125
post adversarial -- adversaire ready after one adv epoch training  0.138671875
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.1533203125
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.1533203125
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.140625
post adversarial -- adversaire ready after one adv epoch training  0.166015625
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.1533203125
post adversarial -- adversaire ready after one adv epoch training  0.14501953125
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.15283203125
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.14892578125
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.15234375
post adversarial -- adversaire ready after one adv epoch training  0.14306640625
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.14892578125
post adversarial -- adversaire ready after one adv epoch training  0.15673828125
post adversarial -- adversaire ready after one adv epoch training  0.15283203125
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.15625
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.1484375
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.1396484375
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.16357421875
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.15625
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.15234375
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.16064453125
post adversarial -- adversaire ready after one adv epoch training  0.15283203125
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.14404296875
post adversarial -- adversaire ready after one adv epoch training  0.14697265625
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.162109375

post adversarial -- adversaire ready after one adv epoch training  0.1533203125
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.1494140625
post adversarial -- adversaire ready after one adv epoch training  0.15625
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.1552734375
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.1630859375
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.1533203125
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.1650390625
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.166015625
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.1474609375
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.16796875
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.1552734375
post adversarial -- adversaire ready after one adv epoch training  0.15283203125
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.14794921875
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.14599609375
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.16552734375
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.16064453125
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.15625
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.13720703125
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.1630859375
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.16357421875
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.1513671875
post adversarial -- adversaire ready after one adv epoch training  0.142578125
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.1552734375
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.1728515625
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.16796875
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125

post adversarial -- adversaire ready after one adv epoch training  0.15625
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.1650390625
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.16552734375
post adversarial -- adversaire ready after one adv epoch training  0.14453125
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.1552734375
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.15185546875
post adversarial -- adversaire ready after one adv epoch training  0.154296875
post adversarial -- adversaire ready after one adv epoch training  0.18641617894172668
Training // Epoch 13 //  Total r_cost = 188851.03049  Total a_cost = 0.00130 total pre adversarial accuracy = 0.15208 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 8170 ms negative Sampling time : 12651 ms negative samples : 400730
precision_1	[0.4475080],	||	 precision_5	[0.3529162],	||	 precision_10	[0.3025451],	||	 precision_15	[0.2675857]
recall_1   	[0.0310145],	||	 recall_5   	[0.1183770],	||	 recall_10   	[0.1942903],	||	 recall_15   	[0.2513509]
f_measure_1	[0.0580087],	||	 f_measure_5	[0.1772874],	||	 f_measure_10	[0.2366240],	||	 f_measure_15	[0.2592144]
ndcg_1     	[0.4475080],	||	 ndcg_5     	[0.3784386],	||	 ndcg_10     	[0.3610959],	||	 ndcg_15     	[0.3571679]
Metrics for user type	 M
precision_1	[0.4477612],	||	 precision_5	[0.3758209],	||	 precision_10	[0.3205970],	||	 precision_15	[0.2831841]
recall_1	[0.0299902],	||	 recall_5	[0.1187051],	||	 recall_10	[0.1971325],	||	 recall_15	[0.2528361]
ndcg_1	[0.4477612],	||	 ndcg_5	[0.3961641],	||	 ndcg_10	[0.3763446],	||	 ndcg_15	[0.3700095]
AUC per user type	[0.9106509]
Metrics for user type	 F
precision_1	[0.4468864],	||	 precision_5	[0.2967033],	||	 precision_10	[0.2582418],	||	 precision_15	[0.2293040]
recall_1	[0.0335283],	||	 recall_5	[0.1175718],	||	 recall_10	[0.1873151],	||	 recall_15	[0.2477061]
ndcg_1	[0.4468864],	||	 ndcg_5	[0.3349363],	||	 ndcg_10	[0.3236722],	||	 ndcg_15	[0.3256521]
AUC per user type	[0.9095888]
AUC global is:  0.9103434046559253
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.166015625
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.1728515625
post adversarial -- adversaire ready after one adv epoch training  0.1484375
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.14990234375
post adversarial -- adversaire ready after one adv epoch training  0.15673828125
post adversarial -- adversaire ready after one adv epoch training  0.16796875
post adversarial -- adversaire ready after one adv epoch training  0.14892578125
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.146484375
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.16357421875
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.166015625
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.1630859375
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.15625
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.15673828125
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.16064453125
post adversarial -- adversaire ready after one adv epoch training  0.1650390625
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.1669921875
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.16796875
post adversarial -- adversaire ready after one adv epoch training  0.1650390625
post adversarial -- adversaire ready after one adv epoch training  0.17626953125
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.1630859375
post adversarial -- adversaire ready after one adv epoch training  0.16796875
post adversarial -- adversaire ready after one adv epoch training  0.166015625
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.16357421875
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.166015625
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.15380859375
post adversarial -- adversaire ready after one adv epoch training  0.16552734375
post adversarial -- adversaire ready after one adv epoch training  0.1650390625
post adversarial -- adversaire ready after one adv epoch training  0.1630859375
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.16650390625

post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.16943359375
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.15673828125
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.15966796875
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.166015625
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.173828125
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.173828125
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.16552734375
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.16552734375
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.15283203125
post adversarial -- adversaire ready after one adv epoch training  0.16064453125
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.1669921875
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.1728515625
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.177734375
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.177734375
post adversarial -- adversaire ready after one adv epoch training  0.173828125
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.1728515625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.18798828125
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.1748046875
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.16015625
post adversarial -- adversaire ready after one adv epoch training  0.150390625
post adversarial -- adversaire ready after one adv epoch training  0.15576171875
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.1669921875
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.173828125
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.15087890625
post adversarial -- adversaire ready after one adv epoch training  0.185546875
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.16357421875
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.15869140625
post adversarial -- adversaire ready after one adv epoch training  0.15771484375
post adversarial -- adversaire ready after one adv epoch training  0.16064453125
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.1630859375
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.1669921875
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.1669921875
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.19287109375
post adversarial -- adversaire ready after one adv epoch training  0.16796875
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.1689453125

post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.16552734375
post adversarial -- adversaire ready after one adv epoch training  0.17626953125
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.1748046875
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.1611328125
post adversarial -- adversaire ready after one adv epoch training  0.17626953125
post adversarial -- adversaire ready after one adv epoch training  0.177734375
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.1650390625
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.16552734375
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.1728515625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.16455078125
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.1630859375
post adversarial -- adversaire ready after one adv epoch training  0.18310546875
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.1572265625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.16552734375
post adversarial -- adversaire ready after one adv epoch training  0.16064453125
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.16357421875
post adversarial -- adversaire ready after one adv epoch training  0.16943359375
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.15478515625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.16796875
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.16357421875
post adversarial -- adversaire ready after one adv epoch training  0.1591796875
post adversarial -- adversaire ready after one adv epoch training  0.162109375
post adversarial -- adversaire ready after one adv epoch training  0.19140625
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.158203125
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.1669921875
post adversarial -- adversaire ready after one adv epoch training  0.166015625
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.173828125
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.1669921875
post adversarial -- adversaire ready after one adv epoch training  0.1669921875
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.16943359375
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.16943359375
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.1689453125

post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.1650390625
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.1884765625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.1728515625
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.17626953125
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.19091796875
post adversarial -- adversaire ready after one adv epoch training  0.19091796875
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.17236328125
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.185546875
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.17626953125
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.16650390625
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.177734375
post adversarial -- adversaire ready after one adv epoch training  0.1640625
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.16943359375
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.15673828125
post adversarial -- adversaire ready after one adv epoch training  0.19775390625
post adversarial -- adversaire ready after one adv epoch training  0.1748046875
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.17626953125
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.1884765625
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.16796875
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.169921875
post adversarial -- adversaire ready after one adv epoch training  0.16943359375
post adversarial -- adversaire ready after one adv epoch training  0.1630859375
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.16748046875
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.18497109413146973
Training // Epoch 14 //  Total r_cost = 188670.06796  Total a_cost = 0.00093 total pre adversarial accuracy = 0.17078 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00000 Training time : 8374 ms negative Sampling time : 8315 ms negative samples : 400730
precision_1	[0.4697773],	||	 precision_5	[0.3573701],	||	 precision_10	[0.2987275],	||	 precision_15	[0.2664546]
recall_1   	[0.0327686],	||	 recall_5   	[0.1190795],	||	 recall_10   	[0.1894540],	||	 recall_15   	[0.2488721]
f_measure_1	[0.0612638],	||	 f_measure_5	[0.1786357],	||	 f_measure_10	[0.2318610],	||	 f_measure_15	[0.2573634]
ndcg_1     	[0.4697773],	||	 ndcg_5     	[0.3836168],	||	 ndcg_10     	[0.3594999],	||	 ndcg_15     	[0.3566510]

Metrics for user type	 M
precision_1	[0.4850746],	||	 precision_5	[0.3802985],	||	 precision_10	[0.3194030],	||	 precision_15	[0.2837811]
recall_1	[0.0311172],	||	 recall_5	[0.1205928],	||	 recall_10	[0.1946440],	||	 recall_15	[0.2524134]
ndcg_1	[0.4850746],	||	 ndcg_5	[0.4056471],	||	 ndcg_10	[0.3788452],	||	 ndcg_15	[0.3728310]
AUC per user type	[0.9117801]
Metrics for user type	 F
precision_1	[0.4322344],	||	 precision_5	[0.3010989],	||	 precision_10	[0.2479853],	||	 precision_15	[0.2239316]
recall_1	[0.0368215],	||	 recall_5	[0.1153656],	||	 recall_10	[0.1767168],	||	 recall_15	[0.2401812]
ndcg_1	[0.4322344],	||	 ndcg_5	[0.3295497],	||	 ndcg_10	[0.3120226],	||	 ndcg_15	[0.3169420]
AUC per user type	[0.9088374]
AUC global is:  0.9109281831200529
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.18310546875
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.18798828125
post adversarial -- adversaire ready after one adv epoch training  0.1689453125
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.1708984375
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.16162109375
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.185546875
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.1650390625
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.173828125
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.1748046875
post adversarial -- adversaire ready after one adv epoch training  0.1748046875
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.189453125
post adversarial -- adversaire ready after one adv epoch training  0.16259765625
post adversarial -- adversaire ready after one adv epoch training  0.193359375
post adversarial -- adversaire ready after one adv epoch training  0.18310546875
post adversarial -- adversaire ready after one adv epoch training  0.1923828125
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.19873046875
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.189453125
post adversarial -- adversaire ready after one adv epoch training  0.18603515625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.1953125
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.18603515625
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.19921875
post adversarial -- adversaire ready after one adv epoch training  0.16845703125
post adversarial -- adversaire ready after one adv epoch training  0.1943359375
post adversarial -- adversaire ready after one adv epoch training  0.17578125
post adversarial -- adversaire ready after one adv epoch training  0.19091796875
post adversarial -- adversaire ready after one adv epoch training  0.19482421875
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.19482421875
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.19287109375
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.19384765625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.19140625
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.185546875
post adversarial -- adversaire ready after one adv epoch training  0.1923828125
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.16357421875
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.18798828125
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.19384765625

post adversarial -- adversaire ready after one adv epoch training  0.1748046875
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.19189453125
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.1728515625
post adversarial -- adversaire ready after one adv epoch training  0.18310546875
post adversarial -- adversaire ready after one adv epoch training  0.17431640625
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.18798828125
post adversarial -- adversaire ready after one adv epoch training  0.19384765625
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.1884765625
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.19091796875
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.19921875
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.185546875
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.18798828125
post adversarial -- adversaire ready after one adv epoch training  0.18115234375
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.171875
post adversarial -- adversaire ready after one adv epoch training  0.2021484375
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.1767578125
post adversarial -- adversaire ready after one adv epoch training  0.19775390625
post adversarial -- adversaire ready after one adv epoch training  0.185546875
post adversarial -- adversaire ready after one adv epoch training  0.177734375
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.20068359375
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.185546875
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.1923828125
post adversarial -- adversaire ready after one adv epoch training  0.1923828125
post adversarial -- adversaire ready after one adv epoch training  0.19287109375
post adversarial -- adversaire ready after one adv epoch training  0.1923828125
post adversarial -- adversaire ready after one adv epoch training  0.17041015625
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.19140625
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.1923828125
post adversarial -- adversaire ready after one adv epoch training  0.201171875
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.19384765625
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.19189453125
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.19189453125
post adversarial -- adversaire ready after one adv epoch training  0.197265625
post adversarial -- adversaire ready after one adv epoch training  0.185546875
post adversarial -- adversaire ready after one adv epoch training  0.18603515625
post adversarial -- adversaire ready after one adv epoch training  0.1884765625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.189453125
post adversarial -- adversaire ready after one adv epoch training  0.19287109375
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.189453125
post adversarial -- adversaire ready after one adv epoch training  0.20068359375
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.19140625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.19091796875
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.19775390625
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.20751953125
post adversarial -- adversaire ready after one adv epoch training  0.18017578125
post adversarial -- adversaire ready after one adv epoch training  0.1796875
post adversarial -- adversaire ready after one adv epoch training  0.1943359375
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.19580078125

post adversarial -- adversaire ready after one adv epoch training  0.17529296875
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.193359375
post adversarial -- adversaire ready after one adv epoch training  0.1923828125
post adversarial -- adversaire ready after one adv epoch training  0.1806640625
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.2001953125
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.19970703125
post adversarial -- adversaire ready after one adv epoch training  0.19921875
post adversarial -- adversaire ready after one adv epoch training  0.1884765625
post adversarial -- adversaire ready after one adv epoch training  0.1865234375
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.18310546875
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.18212890625
post adversarial -- adversaire ready after one adv epoch training  0.19140625
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.189453125
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.177734375
post adversarial -- adversaire ready after one adv epoch training  0.20263671875
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.193359375
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.193359375
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.17138671875
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.189453125
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.1884765625
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.19384765625
post adversarial -- adversaire ready after one adv epoch training  0.17822265625
post adversarial -- adversaire ready after one adv epoch training  0.19140625
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.201171875
post adversarial -- adversaire ready after one adv epoch training  0.177734375
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.20166015625
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.18408203125
post adversarial -- adversaire ready after one adv epoch training  0.203125
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.18310546875
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.2021484375
post adversarial -- adversaire ready after one adv epoch training  0.17333984375
post adversarial -- adversaire ready after one adv epoch training  0.19482421875
post adversarial -- adversaire ready after one adv epoch training  0.197265625
post adversarial -- adversaire ready after one adv epoch training  0.19970703125
post adversarial -- adversaire ready after one adv epoch training  0.20361328125
post adversarial -- adversaire ready after one adv epoch training  0.19580078125
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.19677734375
post adversarial -- adversaire ready after one adv epoch training  0.19775390625
post adversarial -- adversaire ready after one adv epoch training  0.203125
post adversarial -- adversaire ready after one adv epoch training  0.1923828125
post adversarial -- adversaire ready after one adv epoch training  0.2001953125
post adversarial -- adversaire ready after one adv epoch training  0.20458984375
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.19189453125
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.19580078125
post adversarial -- adversaire ready after one adv epoch training  0.19384765625
post adversarial -- adversaire ready after one adv epoch training  0.19482421875
post adversarial -- adversaire ready after one adv epoch training  0.19970703125
post adversarial -- adversaire ready after one adv epoch training  0.19580078125
post adversarial -- adversaire ready after one adv epoch training  0.208984375
post adversarial -- adversaire ready after one adv epoch training  0.19140625
post adversarial -- adversaire ready after one adv epoch training  0.1748046875
post adversarial -- adversaire ready after one adv epoch training  0.2001953125
post adversarial -- adversaire ready after one adv epoch training  0.19384765625
post adversarial -- adversaire ready after one adv epoch training  0.20458984375
post adversarial -- adversaire ready after one adv epoch training  0.19580078125
post adversarial -- adversaire ready after one adv epoch training  0.1904296875
post adversarial -- adversaire ready after one adv epoch training  0.20361328125
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.18798828125
post adversarial -- adversaire ready after one adv epoch training  0.19775390625
post adversarial -- adversaire ready after one adv epoch training  0.208984375
post adversarial -- adversaire ready after one adv epoch training  0.20263671875
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.19775390625
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.2021484375
post adversarial -- adversaire ready after one adv epoch training  0.19580078125
post adversarial -- adversaire ready after one adv epoch training  0.2001953125
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.19970703125
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.2001953125
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.20263671875
post adversarial -- adversaire ready after one adv epoch training  0.2080078125
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.1943359375
post adversarial -- adversaire ready after one adv epoch training  0.189453125
post adversarial -- adversaire ready after one adv epoch training  0.19091796875
post adversarial -- adversaire ready after one adv epoch training  0.18359375
post adversarial -- adversaire ready after one adv epoch training  0.19287109375
post adversarial -- adversaire ready after one adv epoch training  0.20556640625
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.20751953125
post adversarial -- adversaire ready after one adv epoch training  0.19677734375
post adversarial -- adversaire ready after one adv epoch training  0.185546875

post adversarial -- adversaire ready after one adv epoch training  0.1884765625
post adversarial -- adversaire ready after one adv epoch training  0.22265625
post adversarial -- adversaire ready after one adv epoch training  0.18603515625
post adversarial -- adversaire ready after one adv epoch training  0.21337890625
post adversarial -- adversaire ready after one adv epoch training  0.19775390625
post adversarial -- adversaire ready after one adv epoch training  0.20166015625
post adversarial -- adversaire ready after one adv epoch training  0.19970703125
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.20166015625
post adversarial -- adversaire ready after one adv epoch training  0.20361328125
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.1787109375
post adversarial -- adversaire ready after one adv epoch training  0.19189453125
post adversarial -- adversaire ready after one adv epoch training  0.18505859375
post adversarial -- adversaire ready after one adv epoch training  0.18798828125
post adversarial -- adversaire ready after one adv epoch training  0.17919921875
post adversarial -- adversaire ready after one adv epoch training  0.18896484375
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.20458984375
post adversarial -- adversaire ready after one adv epoch training  0.20166015625
post adversarial -- adversaire ready after one adv epoch training  0.19140625
post adversarial -- adversaire ready after one adv epoch training  0.1826171875
post adversarial -- adversaire ready after one adv epoch training  0.181640625
post adversarial -- adversaire ready after one adv epoch training  0.20654296875
post adversarial -- adversaire ready after one adv epoch training  0.19970703125
post adversarial -- adversaire ready after one adv epoch training  0.17724609375
post adversarial -- adversaire ready after one adv epoch training  0.2138671875
post adversarial -- adversaire ready after one adv epoch training  0.20166015625
post adversarial -- adversaire ready after one adv epoch training  0.20458984375
post adversarial -- adversaire ready after one adv epoch training  0.19677734375
post adversarial -- adversaire ready after one adv epoch training  0.19970703125
post adversarial -- adversaire ready after one adv epoch training  0.20556640625
post adversarial -- adversaire ready after one adv epoch training  0.19091796875
post adversarial -- adversaire ready after one adv epoch training  0.19091796875
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.2001953125
post adversarial -- adversaire ready after one adv epoch training  0.19677734375
post adversarial -- adversaire ready after one adv epoch training  0.20068359375
post adversarial -- adversaire ready after one adv epoch training  0.18994140625
post adversarial -- adversaire ready after one adv epoch training  0.21435546875
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.2041015625
post adversarial -- adversaire ready after one adv epoch training  0.1943359375
post adversarial -- adversaire ready after one adv epoch training  0.193359375
post adversarial -- adversaire ready after one adv epoch training  0.201171875
post adversarial -- adversaire ready after one adv epoch training  0.2021484375
post adversarial -- adversaire ready after one adv epoch training  0.189453125
post adversarial -- adversaire ready after one adv epoch training  0.2060546875
post adversarial -- adversaire ready after one adv epoch training  0.2021484375
post adversarial -- adversaire ready after one adv epoch training  0.2099609375
post adversarial -- adversaire ready after one adv epoch training  0.19970703125
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.20556640625
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.20361328125
post adversarial -- adversaire ready after one adv epoch training  0.20654296875
post adversarial -- adversaire ready after one adv epoch training  0.1875
post adversarial -- adversaire ready after one adv epoch training  0.2080078125
post adversarial -- adversaire ready after one adv epoch training  0.2041015625
post adversarial -- adversaire ready after one adv epoch training  0.197265625
post adversarial -- adversaire ready after one adv epoch training  0.1953125
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.18701171875
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.197265625
post adversarial -- adversaire ready after one adv epoch training  0.19677734375
post adversarial -- adversaire ready after one adv epoch training  0.201171875
post adversarial -- adversaire ready after one adv epoch training  0.19775390625
post adversarial -- adversaire ready after one adv epoch training  0.1962890625
post adversarial -- adversaire ready after one adv epoch training  0.1845703125
post adversarial -- adversaire ready after one adv epoch training  0.19189453125
post adversarial -- adversaire ready after one adv epoch training  0.1982421875
post adversarial -- adversaire ready after one adv epoch training  0.2109375
post adversarial -- adversaire ready after one adv epoch training  0.1820809245109558
Training // Epoch 15 //  Total r_cost = 188568.37079  Total a_cost = 0.00068 total pre adversarial accuracy = 0.18939 total pre adversarial accuracy = 0.18939 total post adversarial accuracy = 0.00000 Training time : 8602 ms negative Sampling time : 8216 ms negative samples : 400730
precision_1	[0.4379639],	||	 precision_5	[0.3454931],	||	 precision_10	[0.2958643],	||	 precision_15	[0.2662425]
recall_1   	[0.0311300],	||	 recall_5   	[0.1156020],	||	 recall_10   	[0.1891647],	||	 recall_15   	[0.2498206]
f_measure_1	[0.0581282],	||	 f_measure_5	[0.1732384],	||	 f_measure_10	[0.2307783],	||	 f_measure_15	[0.2577703]
ndcg_1     	[0.4379639],	||	 ndcg_5     	[0.3701400],	||	 ndcg_10     	[0.3532383],	||	 ndcg_15     	[0.3530836]
Metrics for user type	 M
precision_1	[0.4522388],	||	 precision_5	[0.3638806],	||	 precision_10	[0.3164179],	||	 precision_15	[0.2833831]
recall_1	[0.0306642],	||	 recall_5	[0.1158664],	||	 recall_10	[0.1902531],	||	 recall_15	[0.2520105]
ndcg_1	[0.4522388],	||	 ndcg_5	[0.3874942],	||	 ndcg_10	[0.3704263],	||	 ndcg_15	[0.3678394]
AUC per user type	[0.9111550]
Metrics for user type	 F
precision_1	[0.4029304],	||	 precision_5	[0.3003663],	||	 precision_10	[0.2454212],	||	 precision_15	[0.2241758]
recall_1	[0.0322732],	||	 recall_5	[0.1149531],	||	 recall_10	[0.1864935],	||	 recall_15	[0.2444462]
ndcg_1	[0.4029304],	||	 ndcg_5	[0.3275492],	||	 ndcg_10	[0.3110552],	||	 ndcg_15	[0.3168700]
AUC per user type	[0.9106863]
AUC global is:  0.9110193116342523
post adversarial -- adversaire dejoue after one re-training of main model  0.21435546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2138671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21044921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20849609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.177734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20947265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18505859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1865234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18603515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2080078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1865234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.181640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20947265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18701171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1845703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18798828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18701171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1806640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18017578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1806640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1865234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18505859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17822265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1865234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18896484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18505859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.181640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18603515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17919921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.18408203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18505859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1845703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20751953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18505859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18603515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2119140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21728515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18017578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1845703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18115234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18017578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1982421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1982421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1865234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17822265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1767578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17724609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18896484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18017578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.181640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18896484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20751953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1845703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18505859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18701171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.177734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1611328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17822265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1767578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.181640625
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17822265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18701171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1845703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1865234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.181640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1845703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18896484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17919921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1767578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.181640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.177734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17724609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18505859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20166015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17919921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18798828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18798828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18017578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18798828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.15606936812400818
boucle adversarial fin
Training // Epoch 16 //  Total r_cost = 188479.31506  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.19362 Training time : 8647 ms negative Sampling time : 8075 ms negative samples : 400730
precision_1	[0.4517497],	||	 precision_5	[0.3490986],	||	 precision_10	[0.2986214],	||	 precision_15	[0.2661718]
recall_1   	[0.0314898],	||	 recall_5   	[0.1156636],	||	 recall_10   	[0.1894882],	||	 recall_15   	[0.2479759]
f_measure_1	[0.0588756],	||	 f_measure_5	[0.1737577],	||	 f_measure_10	[0.2318546],	||	 f_measure_15	[0.2567518]
ndcg_1     	[0.4517497],	||	 ndcg_5     	[0.3749003],	||	 ndcg_10     	[0.3567290],	||	 ndcg_15     	[0.3541290]
Metrics for user type	 M
precision_1	[0.4611940],	||	 precision_5	[0.3695522],	||	 precision_10	[0.3162687],	||	 precision_15	[0.2826866]
recall_1	[0.0302468],	||	 recall_5	[0.1166813],	||	 recall_10	[0.1909445],	||	 recall_15	[0.2496368]
ndcg_1	[0.4611940],	||	 ndcg_5	[0.3937882],	||	 ndcg_10	[0.3725372],	||	 ndcg_15	[0.3681940]
AUC per user type	[0.9103472]
Metrics for user type	 F
precision_1	[0.4285714],	||	 precision_5	[0.2989011],	||	 precision_10	[0.2553114],	||	 precision_15	[0.2256410]
recall_1	[0.0345402],	||	 recall_5	[0.1131658],	||	 recall_10	[0.1859142],	||	 recall_15	[0.2438996]
ndcg_1	[0.4285714],	||	 ndcg_5	[0.3285455],	||	 ndcg_10	[0.3179321],	||	 ndcg_15	[0.3196106]
AUC per user type	[0.9088903]

AUC global is:  0.9099254492703871
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17333984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1865234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1748046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18017578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18896484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.181640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18798828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1806640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1708984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1865234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17822265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2158203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18798828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18896484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20166015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18115234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18603515625
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.1875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18896484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1982421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17626953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17333984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17919921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18798828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20947265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17431640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1982421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17822265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18798828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1845703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18017578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20849609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18408203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20751953125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18603515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18603515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.185546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18408203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18603515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1982421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20849609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1982421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20166015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2158203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2158203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20166015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20166015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20166015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1982421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20947265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19091796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20361328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20751953125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.2197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2177734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18310546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20751953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20166015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21044921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.193359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2080078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21142578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18994140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22314453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.208984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2138671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21044921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21435546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21337890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2080078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21044921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20166015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2158203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21142578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20947265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2255859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20849609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.201171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2080078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21142578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21435546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2119140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.208984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20849609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21728515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21435546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.22119140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2080078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21728515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21240234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.208984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.220703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20947265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21337890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2177734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21533203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21435546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20849609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19580078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2158203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22900390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2138671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20458984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22314453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2080078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21240234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2177734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2119140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2275390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2177734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.220703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22412109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2119140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21142578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2236328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.224609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22802734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22314453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21533203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.23046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21337890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21533203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22119140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2158203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2041015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2255859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20556640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21240234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2099609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.224609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20751953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21533203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.212890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2255859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20947265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21826171875
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.21531791985034943
boucle adversarial fin
Training // Epoch 17 //  Total r_cost = 151824.85826  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.20052 Training time : 8205 ms negative Sampling time : 8490 ms negative samples : 400730
precision_1	[0.4326617],	||	 precision_5	[0.3378579],	||	 precision_10	[0.2918346],	||	 precision_15	[0.2600919]
recall_1   	[0.0304924],	||	 recall_5   	[0.1127359],	||	 recall_10   	[0.1878848],	||	 recall_15   	[0.2416903]
f_measure_1	[0.0569699],	||	 f_measure_5	[0.1690601],	||	 f_measure_10	[0.2285973],	||	 f_measure_15	[0.2505537]
ndcg_1     	[0.4326617],	||	 ndcg_5     	[0.3616061],	||	 ndcg_10     	[0.3468966],	||	 ndcg_15     	[0.3441768]
Metrics for user type	 M
precision_1	[0.4507463],	||	 precision_5	[0.3608955],	||	 precision_10	[0.3105970],	||	 precision_15	[0.2777114]
recall_1	[0.0305297],	||	 recall_5	[0.1151516],	||	 recall_10	[0.1891857],	||	 recall_15	[0.2438073]
ndcg_1	[0.4507463],	||	 ndcg_5	[0.3843443],	||	 ndcg_10	[0.3651941],	||	 ndcg_15	[0.3607241]
AUC per user type	[0.8949688]
Metrics for user type	 F
precision_1	[0.3882784],	||	 precision_5	[0.2813187],	||	 precision_10	[0.2457875],	||	 precision_15	[0.2168498]
recall_1	[0.0304010],	||	 recall_5	[0.1068075],	||	 recall_10	[0.1846921],	||	 recall_15	[0.2364948]
ndcg_1	[0.3882784],	||	 ndcg_5	[0.3058019],	||	 ndcg_10	[0.3019906],	||	 ndcg_15	[0.3035661]
AUC per user type	[0.8920502]
AUC global is:  0.8941238803904565
post adversarial -- adversaire dejoue after one re-training of main model  0.22802734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22119140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21923828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21533203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.21875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2177734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.22021484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2119140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20751953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.23095703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19873046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.2216796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20849609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19384765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20654296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1982421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.205078125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19970703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.20263671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19482421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19287109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18408203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19775390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.197265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.203125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19677734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17919921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19189453125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.19140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1962890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18505859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1748046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17529296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.181640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.169921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17236328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1826171875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.16943359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.17529296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.18017578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.16552734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.16796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.16259765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.14990234375
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.15673828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1650390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.14501953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.146484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.138671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.13720703125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.142578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.13525390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.12841796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1298828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.12353515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.13232421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.12060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.11328125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.13037109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1123046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.12060546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1103515625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1142578125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.1005859375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0947265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0927734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.08740234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0869140625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.08447265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.08154296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0810546875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.06787109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.06884765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.06640625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.06591796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0615234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.05712890625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0537109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.05615234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.05419921875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0400390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.03759765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0400390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.037109375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0322265625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.03125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.03271484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.02099609375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.03125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0234375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.01904296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.01708984375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.01123046875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.015625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.01513671875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.01318359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00732421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0068359375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00732421875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00927734375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00341796875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00390625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0029296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0029296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0029296875
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.001953125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
Training // Epoch 18 //  Total r_cost = -67983372.24872  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.04369 Training time : 8238 ms negative Sampling time : 8141 ms negative samples : 400730

precision_1	[0.0010604],	||	 precision_5	[0.0286320],	||	 precision_10	[0.0293743],	||	 precision_15	[0.0290562]
recall_1   	[0.0000081],	||	 recall_5   	[0.0041983],	||	 recall_10   	[0.0096726],	||	 recall_15   	[0.0138140]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0073229],	||	 f_measure_10	[0.0145531],	||	 f_measure_15	[0.0187255]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0242696],	||	 ndcg_10     	[0.0267148],	||	 ndcg_15     	[0.0277071]
Metrics for user type	 M
precision_1	[0.0000000],	||	 precision_5	[0.0313433],	||	 precision_10	[0.0313433],	||	 precision_15	[0.0309453]
recall_1	[0.0000000],	||	 recall_5	[0.0045669],	||	 recall_10	[0.0104451],	||	 recall_15	[0.0147178]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0266206],	||	 ndcg_10	[0.0287271],	||	 ndcg_15	[0.0297455]
AUC per user type	[0.6353475]
Metrics for user type	 F
precision_1	[0.0036630],	||	 precision_5	[0.0219780],	||	 precision_10	[0.0245421],	||	 precision_15	[0.0244200]
recall_1	[0.0000280],	||	 recall_5	[0.0032938],	||	 recall_10	[0.0077770],	||	 recall_15	[0.0115958]
ndcg_1	[0.0036630],	||	 ndcg_5	[0.0184996],	||	 ndcg_10	[0.0217764],	||	 ndcg_15	[0.0227046]
AUC per user type	[0.6362568]
AUC global is:  0.6356107537239155
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
Training // Epoch 19 //  Total r_cost = -144266999.88281  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00005 Training time : 8496 ms negative Sampling time : 8069 ms negative samples : 400730
precision_1	[0.0010604],	||	 precision_5	[0.0061506],	||	 precision_10	[0.0074231],	||	 precision_15	[0.0079180]
recall_1   	[0.0000081],	||	 recall_5   	[0.0013860],	||	 recall_10   	[0.0027632],	||	 recall_15   	[0.0043661]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0022622],	||	 f_measure_10	[0.0040273],	||	 f_measure_15	[0.0056285]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0054036],	||	 ndcg_10     	[0.0067027],	||	 ndcg_15     	[0.0075636]
Metrics for user type	 M
precision_1	[0.0000000],	||	 precision_5	[0.0050746],	||	 precision_10	[0.0070149],	||	 precision_15	[0.0078607]
recall_1	[0.0000000],	||	 recall_5	[0.0016304],	||	 recall_10	[0.0030383],	||	 recall_15	[0.0043395]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0044023],	||	 ndcg_10	[0.0062315],	||	 ndcg_15	[0.0073196]
AUC per user type	[0.3990599]
Metrics for user type	 F
precision_1	[0.0036630],	||	 precision_5	[0.0087912],	||	 precision_10	[0.0084249],	||	 precision_15	[0.0080586]
recall_1	[0.0000280],	||	 recall_5	[0.0007860],	||	 recall_10	[0.0020880],	||	 recall_15	[0.0044313]
ndcg_1	[0.0036630],	||	 ndcg_5	[0.0078611],	||	 ndcg_10	[0.0078591],	||	 ndcg_15	[0.0081625]
AUC per user type	[0.4221147]

AUC global is:  0.405734348648887
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
Training // Epoch 20 //  Total r_cost = -161222375.10938  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00008 Training time : 8462 ms negative Sampling time : 7926 ms negative samples : 400730
precision_1	[0.0010604],	||	 precision_5	[0.0042418],	||	 precision_10	[0.0043478],	||	 precision_15	[0.0049487]
recall_1   	[0.0000081],	||	 recall_5   	[0.0008270],	||	 recall_10   	[0.0016816],	||	 recall_15   	[0.0030579]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0013841],	||	 f_measure_10	[0.0024252],	||	 f_measure_15	[0.0037801]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0036771],	||	 ndcg_10     	[0.0041630],	||	 ndcg_15     	[0.0048163]
Metrics for user type	 M
precision_1	[0.0000000],	||	 precision_5	[0.0047761],	||	 precision_10	[0.0049254],	||	 precision_15	[0.0046766]
recall_1	[0.0000000],	||	 recall_5	[0.0010152],	||	 recall_10	[0.0017275],	||	 recall_15	[0.0026140]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0040595],	||	 ndcg_10	[0.0045916],	||	 ndcg_15	[0.0046776]
AUC per user type	[0.2864169]
Metrics for user type	 F
precision_1	[0.0036630],	||	 precision_5	[0.0029304],	||	 precision_10	[0.0029304],	||	 precision_15	[0.0056166]
recall_1	[0.0000280],	||	 recall_5	[0.0003652],	||	 recall_10	[0.0015688],	||	 recall_15	[0.0041473]
ndcg_1	[0.0036630],	||	 ndcg_5	[0.0027386],	||	 ndcg_10	[0.0031112],	||	 ndcg_15	[0.0051567]
AUC per user type	[0.3118003]
AUC global is:  0.29376544802111576
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
Training // Epoch 21 //  Total r_cost = -170417033.59375  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00009 Training time : 8584 ms negative Sampling time : 8978 ms negative samples : 400730
precision_1	[0.0010604],	||	 precision_5	[0.0027572],	||	 precision_10	[0.0034995],	||	 precision_15	[0.0036055]
recall_1   	[0.0000081],	||	 recall_5   	[0.0005539],	||	 recall_10   	[0.0019981],	||	 recall_15   	[0.0024796]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0009224],	||	 f_measure_10	[0.0025437],	||	 f_measure_15	[0.0029384]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0025917],	||	 ndcg_10     	[0.0034556],	||	 ndcg_15     	[0.0037652]
Metrics for user type	 M
precision_1	[0.0000000],	||	 precision_5	[0.0023881],	||	 precision_10	[0.0032836],	||	 precision_15	[0.0034826]
recall_1	[0.0000000],	||	 recall_5	[0.0005479],	||	 recall_10	[0.0018455],	||	 recall_15	[0.0023316]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0020629],	||	 ndcg_10	[0.0030494],	||	 ndcg_15	[0.0034227]
AUC per user type	[0.2361306]
Metrics for user type	 F
precision_1	[0.0036630],	||	 precision_5	[0.0036630],	||	 precision_10	[0.0040293],	||	 precision_15	[0.0039072]
recall_1	[0.0000280],	||	 recall_5	[0.0005685],	||	 recall_10	[0.0023725],	||	 recall_15	[0.0028429]
ndcg_1	[0.0036630],	||	 ndcg_5	[0.0038897],	||	 ndcg_10	[0.0044527],	||	 ndcg_15	[0.0046056]
AUC per user type	[0.2596458]
AUC global is:  0.24293831458583515
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
Training // Epoch 22 //  Total r_cost = -176534646.03125  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00009 Training time : 8822 ms negative Sampling time : 7945 ms negative samples : 400730
precision_1	[0.0010604],	||	 precision_5	[0.0033934],	||	 precision_10	[0.0026511],	||	 precision_15	[0.0025451]
recall_1   	[0.0000081],	||	 recall_5   	[0.0008252],	||	 recall_10   	[0.0012720],	||	 recall_15   	[0.0018091]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0013275],	||	 f_measure_10	[0.0017191],	||	 f_measure_15	[0.0021149]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0030536],	||	 ndcg_10     	[0.0027230],	||	 ndcg_15     	[0.0027746]
Metrics for user type	 M
precision_1	[0.0000000],	||	 precision_5	[0.0038806],	||	 precision_10	[0.0029851],	||	 precision_15	[0.0027861]
recall_1	[0.0000000],	||	 recall_5	[0.0010837],	||	 recall_10	[0.0015862],	||	 recall_15	[0.0019257]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0032764],	||	 ndcg_10	[0.0029758],	||	 ndcg_15	[0.0029482]
AUC per user type	[0.2153291]
Metrics for user type	 F
precision_1	[0.0036630],	||	 precision_5	[0.0021978],	||	 precision_10	[0.0018315],	||	 precision_15	[0.0019536]
recall_1	[0.0000280],	||	 recall_5	[0.0001908],	||	 recall_10	[0.0005009],	||	 recall_15	[0.0015230]
ndcg_1	[0.0036630],	||	 ndcg_5	[0.0025068],	||	 ndcg_10	[0.0021025],	||	 ndcg_15	[0.0023486]
AUC per user type	[0.2357075]
AUC global is:  0.2212286465983697
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
Training // Epoch 23 //  Total r_cost = -180929492.34375  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00010 Training time : 8233 ms negative Sampling time : 7825 ms negative samples : 400730

precision_1	[0.0010604],	||	 precision_5	[0.0027572],	||	 precision_10	[0.0025451],	||	 precision_15	[0.0027572]
recall_1   	[0.0000081],	||	 recall_5   	[0.0007127],	||	 recall_10   	[0.0013999],	||	 recall_15   	[0.0021877]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0011326],	||	 f_measure_10	[0.0018063],	||	 f_measure_15	[0.0024396]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0024171],	||	 ndcg_10     	[0.0025381],	||	 ndcg_15     	[0.0029091]
Metrics for user type	 M
precision_1	[0.0000000],	||	 precision_5	[0.0020896],	||	 precision_10	[0.0019403],	||	 precision_15	[0.0022886]
recall_1	[0.0000000],	||	 recall_5	[0.0005696],	||	 recall_10	[0.0010283],	||	 recall_15	[0.0019042]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0016915],	||	 ndcg_10	[0.0018671],	||	 ndcg_15	[0.0023194]
AUC per user type	[0.2011643]
Metrics for user type	 F
precision_1	[0.0036630],	||	 precision_5	[0.0043956],	||	 precision_10	[0.0040293],	||	 precision_15	[0.0039072]
recall_1	[0.0000280],	||	 recall_5	[0.0010637],	||	 recall_10	[0.0023119],	||	 recall_15	[0.0028834]
ndcg_1	[0.0036630],	||	 ndcg_5	[0.0041981],	||	 ndcg_10	[0.0041849],	||	 ndcg_15	[0.0043564]
AUC per user type	[0.2235995]
AUC global is:  0.20765932758863315
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00146484375
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
Training // Epoch 24 //  Total r_cost = -184209470.46875  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00010 Training time : 8119 ms negative Sampling time : 8152 ms negative samples : 400730
precision_1	[0.0010604],	||	 precision_5	[0.0029692],	||	 precision_10	[0.0026511],	||	 precision_15	[0.0024744]
recall_1   	[0.0000081],	||	 recall_5   	[0.0005648],	||	 recall_10   	[0.0008024],	||	 recall_15   	[0.0011928]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0009491],	||	 f_measure_10	[0.0012319],	||	 f_measure_15	[0.0016096]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0025341],	||	 ndcg_10     	[0.0025320],	||	 ndcg_15     	[0.0025227]
Metrics for user type	 M
precision_1	[0.0000000],	||	 precision_5	[0.0029851],	||	 precision_10	[0.0025373],	||	 precision_15	[0.0022886]
recall_1	[0.0000000],	||	 recall_5	[0.0007105],	||	 recall_10	[0.0009598],	||	 recall_15	[0.0013848]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0023935],	||	 ndcg_10	[0.0023954],	||	 ndcg_15	[0.0023768]
AUC per user type	[0.1967832]
Metrics for user type	 F
precision_1	[0.0036630],	||	 precision_5	[0.0029304],	||	 precision_10	[0.0029304],	||	 precision_15	[0.0029304]
recall_1	[0.0000280],	||	 recall_5	[0.0002071],	||	 recall_10	[0.0004161],	||	 recall_15	[0.0007215]
ndcg_1	[0.0036630],	||	 ndcg_5	[0.0028792],	||	 ndcg_10	[0.0028672],	||	 ndcg_15	[0.0028807]
AUC per user type	[0.2203955]
AUC global is:  0.2036189955162195
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin

post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0009765625
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.00048828125
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
post adversarial -- adversaire dejoue after one re-training of main model  0.0
boucle adversarial fin
Training // Epoch 25 //  Total r_cost = -186794134.60938  Total a_cost = 0.00000 total pre adversarial accuracy = 0.00000 total pre adversarial accuracy = 0.00000 total post adversarial accuracy = 0.00009 Training time : 8267 ms negative Sampling time : 8160 ms negative samples : 400730
precision_1	[0.0010604],	||	 precision_5	[0.0027572],	||	 precision_10	[0.0020148],	||	 precision_15	[0.0020502]
recall_1   	[0.0000081],	||	 recall_5   	[0.0008927],	||	 recall_10   	[0.0012366],	||	 recall_15   	[0.0014567]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0013488],	||	 f_measure_10	[0.0015326],	||	 f_measure_15	[0.0017033]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0024224],	||	 ndcg_10     	[0.0022308],	||	 ndcg_15     	[0.0023621]
Metrics for user type	 M
precision_1	[0.0000000],	||	 precision_5	[0.0023881],	||	 precision_10	[0.0014925],	||	 precision_15	[0.0017910]
recall_1	[0.0000000],	||	 recall_5	[0.0009540],	||	 recall_10	[0.0010078],	||	 recall_15	[0.0012707]
ndcg_1	[0.0000000],	||	 ndcg_5	[0.0019169],	||	 ndcg_10	[0.0016239],	||	 ndcg_15	[0.0019281]
AUC per user type	[0.1981583]
Metrics for user type	 F
precision_1	[0.0036630],	||	 precision_5	[0.0036630],	||	 precision_10	[0.0032967],	||	 precision_15	[0.0026862]
recall_1	[0.0000280],	||	 recall_5	[0.0007423],	||	 recall_10	[0.0017980],	||	 recall_15	[0.0019133]
ndcg_1	[0.0036630],	||	 ndcg_5	[0.0036630],	||	 ndcg_10	[0.0037203],	||	 ndcg_15	[0.0034272]
AUC per user type	[0.2196606]
AUC global is:  0.20438324054071522
precision_1	[0.0010604],	||	 precision_5	[0.0027572],	||	 precision_10	[0.0020148],	||	 precision_15	[0.0020502]
recall_1   	[0.0000081],	||	 recall_5   	[0.0008927],	||	 recall_10   	[0.0012366],	||	 recall_15   	[0.0014567]
f_measure_1	[0.0000161],	||	 f_measure_5	[0.0013488],	||	 f_measure_10	[0.0015326],	||	 f_measure_15	[0.0017033]
ndcg_1     	[0.0010604],	||	 ndcg_5     	[0.0024224],	||	 ndcg_10     	[0.0022308],	||	 ndcg_15     	[0.0023621]

In [179]:
                    #measure adversary accuracy
                    
#                     m = tf.keras.metrics.Accuracy()
#                     m.update_state(self.user_type[user_idx_list,:], adv_output)
#                     m = m.result()
#                    print('accu adv',acc_adv)
#                     accuracy_adv.append(tf.reduce_sum(m.result()))
                    
#                 #sauvegarde prediction adversaire
#                 filename = './const_IembfairAdvBPR_new_results/epoch'+ str(itr) +'_adv_' + self.dataname + '_advAccuracy.npy'
#                 os.makedirs(os.path.dirname(filename), exist_ok=True)           
#                 with open(filename, "wb") as f:
#                     np.save(f, sum(accuracy_adv)/len(accuracy_adv))

In [180]:
import matplotlib.pyplot as plt
import pandas as pd
from colour import Color

def savepdf_barplot_color_gradient(ymin = 0.5, ymax = 0.7, whis = 5, start_color='pink',end_color='blue',num_color=5, title='',axis_x = None, xlabel = '', axis_y1 = None, ylabel ='', plot_file = ''):
    
    fig = plt.figure()
    gs = fig.add_gridspec(1, 2, hspace=0, wspace=0)
    (ax1, ax2) = gs.subplots(sharex='col', sharey='row')
    
    red = Color(start_color)
    colors = list(red.range_to(Color(end_color), num_color))
    colors = [color.rgb for color in colors]
    
    X_axis = np.arange(len(axis_x))
    ax1.bar(X_axis, axis_y1, color=colors)
    ax1.hlines(y=axis_y1[0], xmin = 0, xmax = len(axis_x)-1, colors='black', linestyles='--', lw=1)
    
    plt.sca(ax1)
    plt.xticks(X_axis, axis_x, rotation =50)
    #plt.xlabel(xlabel)
    #fig.suptitle(title)
    plt.ylabel(ylabel, fontsize=18)
    plt.rcParams.update({'font.size': 13}) 
    plt.grid()
    
    plt.sca(ax2)
    ax2.boxplot(axis_y1, whis = whis)
    ax1.set_ylim(ymin, ymax)
    
    plt.tight_layout()                                    
    plt.savefig(plot_file)

def savepdf_barplot_color_gradient2(start_color='pink',end_color='blue',num_color=20, title='',axis_x = None, xlabel = '', axis_y1 = None, ylabel ='', plot_file = ''):
    
    red = Color(start_color)
    colors = list(red.range_to(Color(end_color), num_color))
    colors = [color.rgb for color in colors]
    
    X_axis = np.arange(len(axis_x))
    plt.bar(X_axis, axis_y1, color=colors)
    
    
    plt.xticks(X_axis, axis_x, rotation =70)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid()
    
   # plt.tight_layout()
    plt.savefig(plot_file)